// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.Models;
using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.Common.Enums;

/// <summary>
/// Criteria used to select the winning bid - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<AwardCriteria>))]
public sealed class AwardCriteria : Enumeration
{
    /// <summary>
    /// Lowest price wins
    /// </summary>
    public static readonly AwardCriteria LowestCost = new(nameof(LowestCost), 0);

    /// <summary>
    /// Best rated proposal wins
    /// </summary>
    public static readonly AwardCriteria RatedCriteria = new(nameof(RatedCriteria), 1);

    /// <summary>
    /// Best overall proposal wins
    /// </summary>
    public static readonly AwardCriteria BestProposal = new(nameof(BestProposal), 2);

    private AwardCriteria(string name, int value) : base(name, value) { }

    public static AwardCriteria FromName(string name) => FromNameOrThrow<AwardCriteria>(name);
    public static AwardCriteria FromValue(int value) => FromValueOrThrow<AwardCriteria>(value);
    public static IEnumerable<AwardCriteria> GetAll() => Enumeration.GetAll<AwardCriteria>();
}
