// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.Models;
using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.Common.Enums;

/// <summary>
/// Status of a tender award decision - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<AwardStatus>))]
public sealed class AwardStatus : Enumeration
{
    /// <summary>
    /// Award is under review
    /// </summary>
    public static readonly AwardStatus Pending = new(nameof(Pending), 0);

    /// <summary>
    /// Award is confirmed active
    /// </summary>
    public static readonly AwardStatus Active = new(nameof(Active), 1);

    /// <summary>
    /// Award was unsuccessful
    /// </summary>
    public static readonly AwardStatus Unsuccessful = new(nameof(Unsuccessful), 2);

    /// <summary>
    /// Award was cancelled
    /// </summary>
    public static readonly AwardStatus Cancelled = new(nameof(Cancelled), 3);

    private AwardStatus(string name, int value) : base(name, value) { }

    public static AwardStatus FromName(string name) => FromNameOrThrow<AwardStatus>(name);
    public static AwardStatus FromValue(int value) => FromValueOrThrow<AwardStatus>(value);
    public static IEnumerable<AwardStatus> GetAll() => Enumeration.GetAll<AwardStatus>();
}
