// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.Models;
using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.Common.Enums;

/// <summary>
/// Status of a submitted bid - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<BidStatus>))]
public sealed class BidStatus : Enumeration
{
    /// <summary>
    /// Bid is being composed
    /// </summary>
    public static readonly BidStatus Draft = new(nameof(Draft), 0);

    /// <summary>
    /// Bid is valid and submitted
    /// </summary>
    public static readonly BidStatus Active = new(nameof(Active), 1);

    /// <summary>
    /// Bid was disqualified
    /// </summary>
    public static readonly BidStatus Invalid = new(nameof(Invalid), 2);

    /// <summary>
    /// Bid was withdrawn
    /// </summary>
    public static readonly BidStatus Deleted = new(nameof(Deleted), 3);

    private BidStatus(string name, int value) : base(name, value) { }

    public static BidStatus FromName(string name) => FromNameOrThrow<BidStatus>(name);
    public static BidStatus FromValue(int value) => FromValueOrThrow<BidStatus>(value);
    public static IEnumerable<BidStatus> GetAll() => Enumeration.GetAll<BidStatus>();
}
