// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.Models;
using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.Common.Enums;

/// <summary>
/// Status of a procurement contract - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<ContractStatus>))]
public sealed class ContractStatus : Enumeration
{
    /// <summary>
    /// Contract awaiting signature
    /// </summary>
    public static readonly ContractStatus Pending = new(nameof(Pending), 0);

    /// <summary>
    /// Contract is live and operative
    /// </summary>
    public static readonly ContractStatus Active = new(nameof(Active), 1);

    /// <summary>
    /// Contract was terminated early
    /// </summary>
    public static readonly ContractStatus Terminated = new(nameof(Terminated), 2);

    /// <summary>
    /// Contract was cancelled
    /// </summary>
    public static readonly ContractStatus Cancelled = new(nameof(Cancelled), 3);

    private ContractStatus(string name, int value) : base(name, value) { }

    public static ContractStatus FromName(string name) => FromNameOrThrow<ContractStatus>(name);
    public static ContractStatus FromValue(int value) => FromValueOrThrow<ContractStatus>(value);
    public static IEnumerable<ContractStatus> GetAll() => Enumeration.GetAll<ContractStatus>();
}
