// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.Models;
using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.Common.Enums;

/// <summary>
/// Size classification of a tenderer organization - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<OrganizationScale>))]
public sealed class OrganizationScale : Enumeration
{
    /// <summary>
    /// Micro enterprise (&lt; 10 employees)
    /// </summary>
    public static readonly OrganizationScale Micro = new(nameof(Micro), 0);

    /// <summary>
    /// Small or medium enterprise
    /// </summary>
    public static readonly OrganizationScale Sme = new(nameof(Sme), 1);

    /// <summary>
    /// Mid-size company
    /// </summary>
    public static readonly OrganizationScale Mid = new(nameof(Mid), 2);

    /// <summary>
    /// Large enterprise
    /// </summary>
    public static readonly OrganizationScale Large = new(nameof(Large), 3);

    /// <summary>
    /// Scale not declared
    /// </summary>
    public static readonly OrganizationScale NotSpecified = new(nameof(NotSpecified), 4);

    private OrganizationScale(string name, int value) : base(name, value) { }

    public static OrganizationScale FromName(string name) => FromNameOrThrow<OrganizationScale>(name);
    public static OrganizationScale FromValue(int value) => FromValueOrThrow<OrganizationScale>(value);
    public static IEnumerable<OrganizationScale> GetAll() => Enumeration.GetAll<OrganizationScale>();
}
