// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for Award entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class AwardProjectionMapper : ProjectionMapperBase<Award, AwardProjection>, IAwardProjectionMapper
{
    private readonly ITenderProjectionMapper _tenderMapper;
    private readonly IOrganizationProjectionMapper _organizationMapper;

    public AwardProjectionMapper(
        ITenderProjectionMapper tenderMapper,
        IOrganizationProjectionMapper organizationMapper
    )
    {
        _tenderMapper = tenderMapper;
        _organizationMapper = organizationMapper;
    }

    protected override Expression<Func<Award, AwardProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new AwardProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            ExternalId = entity.ExternalId,
            Status = entity.Status,
            AwardDate = entity.AwardDate,
            Amount = entity.Amount,
            Currency = entity.Currency,
            Qualified = entity.Qualified,
            PeriodStart = entity.PeriodStart,
            PeriodEnd = entity.PeriodEnd,
            BidExternalId = entity.BidExternalId,
            Tender = deep && depth > 0 && entity.Tender != null
                ? new TenderProjection
                {
                    Id = entity.Tender.Id,
                }
                : null,
            Supplier = deep && depth > 0 && entity.Supplier != null
                ? new OrganizationProjection
                {
                    Id = entity.Supplier.Id,
                }
                : null,
        };
    }

    protected override Expression<Func<Award, AwardProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasStatus = requestedFields.Contains("Status");
        var hasAwardDate = requestedFields.Contains("AwardDate");
        var hasAmount = requestedFields.Contains("Amount");
        var hasCurrency = requestedFields.Contains("Currency");
        var hasQualified = requestedFields.Contains("Qualified");
        var hasPeriodStart = requestedFields.Contains("PeriodStart");
        var hasPeriodEnd = requestedFields.Contains("PeriodEnd");
        var hasBidExternalId = requestedFields.Contains("BidExternalId");
        var hasTender = requestedFields.Contains("Tender.Id") || requestedFields.Contains("Tender.Name");
        var hasSupplier = requestedFields.Contains("Supplier.Id") || requestedFields.Contains("Supplier.Name");

        // Use boolean constants in expression tree
        return entity => new AwardProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            Status = hasStatus ? entity.Status : null,
            AwardDate = hasAwardDate ? entity.AwardDate : null,
            Amount = hasAmount ? entity.Amount : null,
            Currency = hasCurrency ? entity.Currency : null,
            Qualified = hasQualified ? entity.Qualified : null,
            PeriodStart = hasPeriodStart ? entity.PeriodStart : null,
            PeriodEnd = hasPeriodEnd ? entity.PeriodEnd : null,
            BidExternalId = hasBidExternalId ? entity.BidExternalId : null,
            Tender = hasTender && entity.Tender != null
                ? new TenderProjection
                {
                    Id = entity.Tender.Id,
                }
                : null,
            Supplier = hasSupplier && entity.Supplier != null
                ? new OrganizationProjection
                {
                    Id = entity.Supplier.Id,
                }
                : null,
        };
    }

    protected override void MapAllFields(
        Award entity,
        AwardProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.ExternalId = entity.ExternalId;
        result.Status = entity.Status;
        result.AwardDate = entity.AwardDate;
        result.Amount = entity.Amount;
        result.Currency = entity.Currency;
        result.Qualified = entity.Qualified;
        result.PeriodStart = entity.PeriodStart;
        result.PeriodEnd = entity.PeriodEnd;
        result.BidExternalId = entity.BidExternalId;

        // Map related entities with depth control
        if (deep && currentDepth < maxDepth && entity.Tender != null)
        {
            var tenderProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.Tender = _tenderMapper.Map(
                entity.Tender,
                tenderProjection,
                currentDepth + 1
            );
        }
        if (deep && currentDepth < maxDepth && entity.Supplier != null)
        {
            var supplierProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.Supplier = _organizationMapper.Map(
                entity.Supplier,
                supplierProjection,
                currentDepth + 1
            );
        }
    }

    protected override void MapField(
        Award entity,
        AwardProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "status":
                result.Status = entity.Status;
                break;
            case "awardDate":
                result.AwardDate = entity.AwardDate;
                break;
            case "amount":
                result.Amount = entity.Amount;
                break;
            case "currency":
                result.Currency = entity.Currency;
                break;
            case "qualified":
                result.Qualified = entity.Qualified;
                break;
            case "periodStart":
                result.PeriodStart = entity.PeriodStart;
                break;
            case "periodEnd":
                result.PeriodEnd = entity.PeriodEnd;
                break;
            case "bidExternalId":
                result.BidExternalId = entity.BidExternalId;
                break;
            case "tender.id":
                if (entity.Tender != null)
                {
                    result.Tender ??= new TenderProjection();
                    result.Tender.Id = entity.Tender.Id;
                }
                break;
            case "tender.name":
                if (entity.Tender != null)
                {
                    result.Tender ??= new TenderProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
            case "supplier.id":
                if (entity.Supplier != null)
                {
                    result.Supplier ??= new OrganizationProjection();
                    result.Supplier.Id = entity.Supplier.Id;
                }
                break;
            case "supplier.name":
                if (entity.Supplier != null)
                {
                    result.Supplier ??= new OrganizationProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
        }
    }
}
