// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for ContractChangeRationaleType entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class ContractChangeRationaleTypeProjectionMapper : ProjectionMapperBase<ContractChangeRationaleType, ContractChangeRationaleTypeProjection>, IContractChangeRationaleTypeProjectionMapper
{

    protected override Expression<Func<ContractChangeRationaleType, ContractChangeRationaleTypeProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new ContractChangeRationaleTypeProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            Code = entity.Code,
            TitleEn = entity.TitleEn,
            TitleUk = entity.TitleUk,
            DescriptionEn = entity.DescriptionEn,
            DescriptionUk = entity.DescriptionUk,
        };
    }

    protected override Expression<Func<ContractChangeRationaleType, ContractChangeRationaleTypeProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasCode = requestedFields.Contains("Code");
        var hasTitleEn = requestedFields.Contains("TitleEn");
        var hasTitleUk = requestedFields.Contains("TitleUk");
        var hasDescriptionEn = requestedFields.Contains("DescriptionEn");
        var hasDescriptionUk = requestedFields.Contains("DescriptionUk");

        // Use boolean constants in expression tree
        return entity => new ContractChangeRationaleTypeProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            Code = hasCode ? entity.Code : null,
            TitleEn = hasTitleEn ? entity.TitleEn : null,
            TitleUk = hasTitleUk ? entity.TitleUk : null,
            DescriptionEn = hasDescriptionEn ? entity.DescriptionEn : null,
            DescriptionUk = hasDescriptionUk ? entity.DescriptionUk : null,
        };
    }

    protected override void MapAllFields(
        ContractChangeRationaleType entity,
        ContractChangeRationaleTypeProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.Code = entity.Code;
        result.TitleEn = entity.TitleEn;
        result.TitleUk = entity.TitleUk;
        result.DescriptionEn = entity.DescriptionEn;
        result.DescriptionUk = entity.DescriptionUk;

    }

    protected override void MapField(
        ContractChangeRationaleType entity,
        ContractChangeRationaleTypeProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "code":
                result.Code = entity.Code;
                break;
            case "titleEn":
                result.TitleEn = entity.TitleEn;
                break;
            case "titleUk":
                result.TitleUk = entity.TitleUk;
                break;
            case "descriptionEn":
                result.DescriptionEn = entity.DescriptionEn;
                break;
            case "descriptionUk":
                result.DescriptionUk = entity.DescriptionUk;
                break;
        }
    }
}
