// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for Contract entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class ContractProjectionMapper : ProjectionMapperBase<Contract, ContractProjection>, IContractProjectionMapper
{
    private readonly ITenderProjectionMapper _tenderMapper;

    public ContractProjectionMapper(
        ITenderProjectionMapper tenderMapper
    )
    {
        _tenderMapper = tenderMapper;
    }

    protected override Expression<Func<Contract, ContractProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new ContractProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            ExternalId = entity.ExternalId,
            ContractNumber = entity.ContractNumber,
            Title = entity.Title,
            Description = entity.Description,
            Status = entity.Status,
            ContractDate = entity.ContractDate,
            Amount = entity.Amount,
            Currency = entity.Currency,
            AwardExternalId = entity.AwardExternalId,
            Tender = deep && depth > 0 && entity.Tender != null
                ? new TenderProjection
                {
                    Id = entity.Tender.Id,
                }
                : null,
        };
    }

    protected override Expression<Func<Contract, ContractProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasContractNumber = requestedFields.Contains("ContractNumber");
        var hasTitle = requestedFields.Contains("Title");
        var hasDescription = requestedFields.Contains("Description");
        var hasStatus = requestedFields.Contains("Status");
        var hasContractDate = requestedFields.Contains("ContractDate");
        var hasAmount = requestedFields.Contains("Amount");
        var hasCurrency = requestedFields.Contains("Currency");
        var hasAwardExternalId = requestedFields.Contains("AwardExternalId");
        var hasTender = requestedFields.Contains("Tender.Id") || requestedFields.Contains("Tender.Name");

        // Use boolean constants in expression tree
        return entity => new ContractProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            ContractNumber = hasContractNumber ? entity.ContractNumber : null,
            Title = hasTitle ? entity.Title : null,
            Description = hasDescription ? entity.Description : null,
            Status = hasStatus ? entity.Status : null,
            ContractDate = hasContractDate ? entity.ContractDate : null,
            Amount = hasAmount ? entity.Amount : null,
            Currency = hasCurrency ? entity.Currency : null,
            AwardExternalId = hasAwardExternalId ? entity.AwardExternalId : null,
            Tender = hasTender && entity.Tender != null
                ? new TenderProjection
                {
                    Id = entity.Tender.Id,
                }
                : null,
        };
    }

    protected override void MapAllFields(
        Contract entity,
        ContractProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.ExternalId = entity.ExternalId;
        result.ContractNumber = entity.ContractNumber;
        result.Title = entity.Title;
        result.Description = entity.Description;
        result.Status = entity.Status;
        result.ContractDate = entity.ContractDate;
        result.Amount = entity.Amount;
        result.Currency = entity.Currency;
        result.AwardExternalId = entity.AwardExternalId;

        // Map related entities with depth control
        if (deep && currentDepth < maxDepth && entity.Tender != null)
        {
            var tenderProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.Tender = _tenderMapper.Map(
                entity.Tender,
                tenderProjection,
                currentDepth + 1
            );
        }
    }

    protected override void MapField(
        Contract entity,
        ContractProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "contractNumber":
                result.ContractNumber = entity.ContractNumber;
                break;
            case "title":
                result.Title = entity.Title;
                break;
            case "description":
                result.Description = entity.Description;
                break;
            case "status":
                result.Status = entity.Status;
                break;
            case "contractDate":
                result.ContractDate = entity.ContractDate;
                break;
            case "amount":
                result.Amount = entity.Amount;
                break;
            case "currency":
                result.Currency = entity.Currency;
                break;
            case "awardExternalId":
                result.AwardExternalId = entity.AwardExternalId;
                break;
            case "tender.id":
                if (entity.Tender != null)
                {
                    result.Tender ??= new TenderProjection();
                    result.Tender.Id = entity.Tender.Id;
                }
                break;
            case "tender.name":
                if (entity.Tender != null)
                {
                    result.Tender ??= new TenderProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
        }
    }
}
