// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for Criterion entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class CriterionProjectionMapper : ProjectionMapperBase<Criterion, CriterionProjection>, ICriterionProjectionMapper
{
    private readonly ITenderProjectionMapper _tenderMapper;

    public CriterionProjectionMapper(
        ITenderProjectionMapper tenderMapper
    )
    {
        _tenderMapper = tenderMapper;
    }

    protected override Expression<Func<Criterion, CriterionProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new CriterionProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Description = entity.Description,
            Source = entity.Source,
            RelatesTo = entity.RelatesTo,
            RelatedItem = entity.RelatedItem,
            ClassificationScheme = entity.ClassificationScheme,
            ClassificationId = entity.ClassificationId,
            Tender = deep && depth > 0 && entity.Tender != null
                ? new TenderProjection
                {
                    Id = entity.Tender.Id,
                }
                : null,
        };
    }

    protected override Expression<Func<Criterion, CriterionProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasTitle = requestedFields.Contains("Title");
        var hasDescription = requestedFields.Contains("Description");
        var hasSource = requestedFields.Contains("Source");
        var hasRelatesTo = requestedFields.Contains("RelatesTo");
        var hasRelatedItem = requestedFields.Contains("RelatedItem");
        var hasClassificationScheme = requestedFields.Contains("ClassificationScheme");
        var hasClassificationId = requestedFields.Contains("ClassificationId");
        var hasTender = requestedFields.Contains("Tender.Id") || requestedFields.Contains("Tender.Name");

        // Use boolean constants in expression tree
        return entity => new CriterionProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            Title = hasTitle ? entity.Title : null,
            Description = hasDescription ? entity.Description : null,
            Source = hasSource ? entity.Source : null,
            RelatesTo = hasRelatesTo ? entity.RelatesTo : null,
            RelatedItem = hasRelatedItem ? entity.RelatedItem : null,
            ClassificationScheme = hasClassificationScheme ? entity.ClassificationScheme : null,
            ClassificationId = hasClassificationId ? entity.ClassificationId : null,
            Tender = hasTender && entity.Tender != null
                ? new TenderProjection
                {
                    Id = entity.Tender.Id,
                }
                : null,
        };
    }

    protected override void MapAllFields(
        Criterion entity,
        CriterionProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.ExternalId = entity.ExternalId;
        result.Title = entity.Title;
        result.Description = entity.Description;
        result.Source = entity.Source;
        result.RelatesTo = entity.RelatesTo;
        result.RelatedItem = entity.RelatedItem;
        result.ClassificationScheme = entity.ClassificationScheme;
        result.ClassificationId = entity.ClassificationId;

        // Map related entities with depth control
        if (deep && currentDepth < maxDepth && entity.Tender != null)
        {
            var tenderProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.Tender = _tenderMapper.Map(
                entity.Tender,
                tenderProjection,
                currentDepth + 1
            );
        }
    }

    protected override void MapField(
        Criterion entity,
        CriterionProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "title":
                result.Title = entity.Title;
                break;
            case "description":
                result.Description = entity.Description;
                break;
            case "source":
                result.Source = entity.Source;
                break;
            case "relatesTo":
                result.RelatesTo = entity.RelatesTo;
                break;
            case "relatedItem":
                result.RelatedItem = entity.RelatedItem;
                break;
            case "classificationScheme":
                result.ClassificationScheme = entity.ClassificationScheme;
                break;
            case "classificationId":
                result.ClassificationId = entity.ClassificationId;
                break;
            case "tender.id":
                if (entity.Tender != null)
                {
                    result.Tender ??= new TenderProjection();
                    result.Tender.Id = entity.Tender.Id;
                }
                break;
            case "tender.name":
                if (entity.Tender != null)
                {
                    result.Tender ??= new TenderProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
        }
    }
}
