// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for Organization entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class OrganizationProjectionMapper : ProjectionMapperBase<Organization, OrganizationProjection>, IOrganizationProjectionMapper
{

    protected override Expression<Func<Organization, OrganizationProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new OrganizationProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            ExternalId = entity.ExternalId,
            IdentifierScheme = entity.IdentifierScheme,
            Name = entity.Name,
            NameEn = entity.NameEn,
            LegalName = entity.LegalName,
            LegalNameEn = entity.LegalNameEn,
            Kind = entity.Kind,
            Scale = entity.Scale,
            StreetAddress = entity.StreetAddress,
            Locality = entity.Locality,
            Region = entity.Region,
            PostalCode = entity.PostalCode,
            CountryName = entity.CountryName,
            ContactName = entity.ContactName,
            ContactEmail = entity.ContactEmail,
            ContactPhone = entity.ContactPhone,
            ContactUrl = entity.ContactUrl,
        };
    }

    protected override Expression<Func<Organization, OrganizationProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasIdentifierScheme = requestedFields.Contains("IdentifierScheme");
        var hasName = requestedFields.Contains("Name");
        var hasNameEn = requestedFields.Contains("NameEn");
        var hasLegalName = requestedFields.Contains("LegalName");
        var hasLegalNameEn = requestedFields.Contains("LegalNameEn");
        var hasKind = requestedFields.Contains("Kind");
        var hasScale = requestedFields.Contains("Scale");
        var hasStreetAddress = requestedFields.Contains("StreetAddress");
        var hasLocality = requestedFields.Contains("Locality");
        var hasRegion = requestedFields.Contains("Region");
        var hasPostalCode = requestedFields.Contains("PostalCode");
        var hasCountryName = requestedFields.Contains("CountryName");
        var hasContactName = requestedFields.Contains("ContactName");
        var hasContactEmail = requestedFields.Contains("ContactEmail");
        var hasContactPhone = requestedFields.Contains("ContactPhone");
        var hasContactUrl = requestedFields.Contains("ContactUrl");

        // Use boolean constants in expression tree
        return entity => new OrganizationProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            IdentifierScheme = hasIdentifierScheme ? entity.IdentifierScheme : null,
            Name = hasName ? entity.Name : null,
            NameEn = hasNameEn ? entity.NameEn : null,
            LegalName = hasLegalName ? entity.LegalName : null,
            LegalNameEn = hasLegalNameEn ? entity.LegalNameEn : null,
            Kind = hasKind ? entity.Kind : null,
            Scale = hasScale ? entity.Scale : null,
            StreetAddress = hasStreetAddress ? entity.StreetAddress : null,
            Locality = hasLocality ? entity.Locality : null,
            Region = hasRegion ? entity.Region : null,
            PostalCode = hasPostalCode ? entity.PostalCode : null,
            CountryName = hasCountryName ? entity.CountryName : null,
            ContactName = hasContactName ? entity.ContactName : null,
            ContactEmail = hasContactEmail ? entity.ContactEmail : null,
            ContactPhone = hasContactPhone ? entity.ContactPhone : null,
            ContactUrl = hasContactUrl ? entity.ContactUrl : null,
        };
    }

    protected override void MapAllFields(
        Organization entity,
        OrganizationProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.ExternalId = entity.ExternalId;
        result.IdentifierScheme = entity.IdentifierScheme;
        result.Name = entity.Name;
        result.NameEn = entity.NameEn;
        result.LegalName = entity.LegalName;
        result.LegalNameEn = entity.LegalNameEn;
        result.Kind = entity.Kind;
        result.Scale = entity.Scale;
        result.StreetAddress = entity.StreetAddress;
        result.Locality = entity.Locality;
        result.Region = entity.Region;
        result.PostalCode = entity.PostalCode;
        result.CountryName = entity.CountryName;
        result.ContactName = entity.ContactName;
        result.ContactEmail = entity.ContactEmail;
        result.ContactPhone = entity.ContactPhone;
        result.ContactUrl = entity.ContactUrl;

    }

    protected override void MapField(
        Organization entity,
        OrganizationProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "identifierScheme":
                result.IdentifierScheme = entity.IdentifierScheme;
                break;
            case "name":
                result.Name = entity.Name;
                break;
            case "nameEn":
                result.NameEn = entity.NameEn;
                break;
            case "legalName":
                result.LegalName = entity.LegalName;
                break;
            case "legalNameEn":
                result.LegalNameEn = entity.LegalNameEn;
                break;
            case "kind":
                result.Kind = entity.Kind;
                break;
            case "scale":
                result.Scale = entity.Scale;
                break;
            case "streetAddress":
                result.StreetAddress = entity.StreetAddress;
                break;
            case "locality":
                result.Locality = entity.Locality;
                break;
            case "region":
                result.Region = entity.Region;
                break;
            case "postalCode":
                result.PostalCode = entity.PostalCode;
                break;
            case "countryName":
                result.CountryName = entity.CountryName;
                break;
            case "contactName":
                result.ContactName = entity.ContactName;
                break;
            case "contactEmail":
                result.ContactEmail = entity.ContactEmail;
                break;
            case "contactPhone":
                result.ContactPhone = entity.ContactPhone;
                break;
            case "contactUrl":
                result.ContactUrl = entity.ContactUrl;
                break;
        }
    }
}
