// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for Requirement entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class RequirementProjectionMapper : ProjectionMapperBase<Requirement, RequirementProjection>, IRequirementProjectionMapper
{
    private readonly IRequirementGroupProjectionMapper _requirementGroupMapper;

    public RequirementProjectionMapper(
        IRequirementGroupProjectionMapper requirementGroupMapper
    )
    {
        _requirementGroupMapper = requirementGroupMapper;
    }

    protected override Expression<Func<Requirement, RequirementProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new RequirementProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            DataType = entity.DataType,
            Status = entity.Status,
            ExpectedValue = entity.ExpectedValue,
            ExpectedValuesJson = entity.ExpectedValuesJson,
            ExpectedMinItems = entity.ExpectedMinItems,
            ExpectedMaxItems = entity.ExpectedMaxItems,
            DatePublished = entity.DatePublished,
            RequirementGroup = deep && depth > 0 && entity.RequirementGroup != null
                ? new RequirementGroupProjection
                {
                    Id = entity.RequirementGroup.Id,
                }
                : null,
        };
    }

    protected override Expression<Func<Requirement, RequirementProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasTitle = requestedFields.Contains("Title");
        var hasDataType = requestedFields.Contains("DataType");
        var hasStatus = requestedFields.Contains("Status");
        var hasExpectedValue = requestedFields.Contains("ExpectedValue");
        var hasExpectedValuesJson = requestedFields.Contains("ExpectedValuesJson");
        var hasExpectedMinItems = requestedFields.Contains("ExpectedMinItems");
        var hasExpectedMaxItems = requestedFields.Contains("ExpectedMaxItems");
        var hasDatePublished = requestedFields.Contains("DatePublished");
        var hasRequirementGroup = requestedFields.Contains("RequirementGroup.Id") || requestedFields.Contains("RequirementGroup.Name");

        // Use boolean constants in expression tree
        return entity => new RequirementProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            Title = hasTitle ? entity.Title : null,
            DataType = hasDataType ? entity.DataType : null,
            Status = hasStatus ? entity.Status : null,
            ExpectedValue = hasExpectedValue ? entity.ExpectedValue : null,
            ExpectedValuesJson = hasExpectedValuesJson ? entity.ExpectedValuesJson : null,
            ExpectedMinItems = hasExpectedMinItems ? entity.ExpectedMinItems : null,
            ExpectedMaxItems = hasExpectedMaxItems ? entity.ExpectedMaxItems : null,
            DatePublished = hasDatePublished ? entity.DatePublished : null,
            RequirementGroup = hasRequirementGroup && entity.RequirementGroup != null
                ? new RequirementGroupProjection
                {
                    Id = entity.RequirementGroup.Id,
                }
                : null,
        };
    }

    protected override void MapAllFields(
        Requirement entity,
        RequirementProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.ExternalId = entity.ExternalId;
        result.Title = entity.Title;
        result.DataType = entity.DataType;
        result.Status = entity.Status;
        result.ExpectedValue = entity.ExpectedValue;
        result.ExpectedValuesJson = entity.ExpectedValuesJson;
        result.ExpectedMinItems = entity.ExpectedMinItems;
        result.ExpectedMaxItems = entity.ExpectedMaxItems;
        result.DatePublished = entity.DatePublished;

        // Map related entities with depth control
        if (deep && currentDepth < maxDepth && entity.RequirementGroup != null)
        {
            var requirementGroupProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.RequirementGroup = _requirementGroupMapper.Map(
                entity.RequirementGroup,
                requirementGroupProjection,
                currentDepth + 1
            );
        }
    }

    protected override void MapField(
        Requirement entity,
        RequirementProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "title":
                result.Title = entity.Title;
                break;
            case "dataType":
                result.DataType = entity.DataType;
                break;
            case "status":
                result.Status = entity.Status;
                break;
            case "expectedValue":
                result.ExpectedValue = entity.ExpectedValue;
                break;
            case "expectedValuesJson":
                result.ExpectedValuesJson = entity.ExpectedValuesJson;
                break;
            case "expectedMinItems":
                result.ExpectedMinItems = entity.ExpectedMinItems;
                break;
            case "expectedMaxItems":
                result.ExpectedMaxItems = entity.ExpectedMaxItems;
                break;
            case "datePublished":
                result.DatePublished = entity.DatePublished;
                break;
            case "requirementGroup.id":
                if (entity.RequirementGroup != null)
                {
                    result.RequirementGroup ??= new RequirementGroupProjection();
                    result.RequirementGroup.Id = entity.RequirementGroup.Id;
                }
                break;
            case "requirementGroup.name":
                if (entity.RequirementGroup != null)
                {
                    result.RequirementGroup ??= new RequirementGroupProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
        }
    }
}
