// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for RequirementGroup entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class RequirementGroupProjectionMapper : ProjectionMapperBase<RequirementGroup, RequirementGroupProjection>, IRequirementGroupProjectionMapper
{
    private readonly ICriterionProjectionMapper _criterionMapper;

    public RequirementGroupProjectionMapper(
        ICriterionProjectionMapper criterionMapper
    )
    {
        _criterionMapper = criterionMapper;
    }

    protected override Expression<Func<RequirementGroup, RequirementGroupProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new RequirementGroupProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            ExternalId = entity.ExternalId,
            Description = entity.Description,
            Criterion = deep && depth > 0 && entity.Criterion != null
                ? new CriterionProjection
                {
                    Id = entity.Criterion.Id,
                }
                : null,
        };
    }

    protected override Expression<Func<RequirementGroup, RequirementGroupProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasDescription = requestedFields.Contains("Description");
        var hasCriterion = requestedFields.Contains("Criterion.Id") || requestedFields.Contains("Criterion.Name");

        // Use boolean constants in expression tree
        return entity => new RequirementGroupProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            Description = hasDescription ? entity.Description : null,
            Criterion = hasCriterion && entity.Criterion != null
                ? new CriterionProjection
                {
                    Id = entity.Criterion.Id,
                }
                : null,
        };
    }

    protected override void MapAllFields(
        RequirementGroup entity,
        RequirementGroupProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.ExternalId = entity.ExternalId;
        result.Description = entity.Description;

        // Map related entities with depth control
        if (deep && currentDepth < maxDepth && entity.Criterion != null)
        {
            var criterionProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.Criterion = _criterionMapper.Map(
                entity.Criterion,
                criterionProjection,
                currentDepth + 1
            );
        }
    }

    protected override void MapField(
        RequirementGroup entity,
        RequirementGroupProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "description":
                result.Description = entity.Description;
                break;
            case "criterion.id":
                if (entity.Criterion != null)
                {
                    result.Criterion ??= new CriterionProjection();
                    result.Criterion.Id = entity.Criterion.Id;
                }
                break;
            case "criterion.name":
                if (entity.Criterion != null)
                {
                    result.Criterion ??= new CriterionProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
        }
    }
}
