// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Override methods in partial class for custom projection logic.
// </auto-generated>

using System.Linq.Expressions;
using Onward.Base.Abstractions;
using Onward.Base.ADTs;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.BL.Mappers.Projection;

/// <summary>
/// Projection mapper for Tender entity.
/// Implements template methods for EF Core expressions and in-memory mapping.
/// </summary>
public class TenderProjectionMapper : ProjectionMapperBase<Tender, TenderProjection>, ITenderProjectionMapper
{
    private readonly IOrganizationProjectionMapper _organizationMapper;

    public TenderProjectionMapper(
        IOrganizationProjectionMapper organizationMapper
    )
    {
        _organizationMapper = organizationMapper;
    }

    protected override Expression<Func<Tender, TenderProjection>> GetAllFieldsProjection(bool deep, int depth)
    {
        return entity => new TenderProjection
        {
            Id = entity.Id,
            CreatedAt = entity.CreatedAt,
            UpdatedAt = entity.UpdatedAt,
            ExternalId = entity.ExternalId,
            TenderNumber = entity.TenderNumber,
            Title = entity.Title,
            Description = entity.Description,
            Owner = entity.Owner,
            Status = entity.Status,
            ProcurementMethodType = entity.ProcurementMethodType,
            AwardCriteria = entity.AwardCriteria,
            ProcurementMethod = entity.ProcurementMethod,
            MainProcurementCategory = entity.MainProcurementCategory,
            TotalAmount = entity.TotalAmount,
            Currency = entity.Currency,
            ValueAddedTaxIncluded = entity.ValueAddedTaxIncluded,
            TenderPeriodStart = entity.TenderPeriodStart,
            TenderPeriodEnd = entity.TenderPeriodEnd,
            AwardPeriodStart = entity.AwardPeriodStart,
            AwardPeriodEnd = entity.AwardPeriodEnd,
            NoticePublicationDate = entity.NoticePublicationDate,
            TenderDate = entity.TenderDate,
            AgreementId = entity.AgreementId,
            ProcuringEntity = deep && depth > 0 && entity.ProcuringEntity != null
                ? new OrganizationProjection
                {
                    Id = entity.ProcuringEntity.Id,
                }
                : null,
        };
    }

    protected override Expression<Func<Tender, TenderProjection>> BuildSelectiveProjection(
        ProjectionRequest projection)
    {
        // Evaluate field checks OUTSIDE expression tree for EF Core compatibility
        var requestedFields = new HashSet<string>(
            projection.Fields.Select(f => f.FieldName),
            StringComparer.OrdinalIgnoreCase);

        var hasId = requestedFields.Contains("Id");
        var hasCreatedAt = requestedFields.Contains("CreatedAt");
        var hasUpdatedAt = requestedFields.Contains("UpdatedAt");
        var hasExternalId = requestedFields.Contains("ExternalId");
        var hasTenderNumber = requestedFields.Contains("TenderNumber");
        var hasTitle = requestedFields.Contains("Title");
        var hasDescription = requestedFields.Contains("Description");
        var hasOwner = requestedFields.Contains("Owner");
        var hasStatus = requestedFields.Contains("Status");
        var hasProcurementMethodType = requestedFields.Contains("ProcurementMethodType");
        var hasAwardCriteria = requestedFields.Contains("AwardCriteria");
        var hasProcurementMethod = requestedFields.Contains("ProcurementMethod");
        var hasMainProcurementCategory = requestedFields.Contains("MainProcurementCategory");
        var hasTotalAmount = requestedFields.Contains("TotalAmount");
        var hasCurrency = requestedFields.Contains("Currency");
        var hasValueAddedTaxIncluded = requestedFields.Contains("ValueAddedTaxIncluded");
        var hasTenderPeriodStart = requestedFields.Contains("TenderPeriodStart");
        var hasTenderPeriodEnd = requestedFields.Contains("TenderPeriodEnd");
        var hasAwardPeriodStart = requestedFields.Contains("AwardPeriodStart");
        var hasAwardPeriodEnd = requestedFields.Contains("AwardPeriodEnd");
        var hasNoticePublicationDate = requestedFields.Contains("NoticePublicationDate");
        var hasTenderDate = requestedFields.Contains("TenderDate");
        var hasAgreementId = requestedFields.Contains("AgreementId");
        var hasProcuringEntity = requestedFields.Contains("ProcuringEntity.Id") || requestedFields.Contains("ProcuringEntity.Name");

        // Use boolean constants in expression tree
        return entity => new TenderProjection
        {
            Id = hasId ? entity.Id : null,
            CreatedAt = hasCreatedAt ? entity.CreatedAt : null,
            UpdatedAt = hasUpdatedAt ? entity.UpdatedAt : null,
            ExternalId = hasExternalId ? entity.ExternalId : null,
            TenderNumber = hasTenderNumber ? entity.TenderNumber : null,
            Title = hasTitle ? entity.Title : null,
            Description = hasDescription ? entity.Description : null,
            Owner = hasOwner ? entity.Owner : null,
            Status = hasStatus ? entity.Status : null,
            ProcurementMethodType = hasProcurementMethodType ? entity.ProcurementMethodType : null,
            AwardCriteria = hasAwardCriteria ? entity.AwardCriteria : null,
            ProcurementMethod = hasProcurementMethod ? entity.ProcurementMethod : null,
            MainProcurementCategory = hasMainProcurementCategory ? entity.MainProcurementCategory : null,
            TotalAmount = hasTotalAmount ? entity.TotalAmount : null,
            Currency = hasCurrency ? entity.Currency : null,
            ValueAddedTaxIncluded = hasValueAddedTaxIncluded ? entity.ValueAddedTaxIncluded : null,
            TenderPeriodStart = hasTenderPeriodStart ? entity.TenderPeriodStart : null,
            TenderPeriodEnd = hasTenderPeriodEnd ? entity.TenderPeriodEnd : null,
            AwardPeriodStart = hasAwardPeriodStart ? entity.AwardPeriodStart : null,
            AwardPeriodEnd = hasAwardPeriodEnd ? entity.AwardPeriodEnd : null,
            NoticePublicationDate = hasNoticePublicationDate ? entity.NoticePublicationDate : null,
            TenderDate = hasTenderDate ? entity.TenderDate : null,
            AgreementId = hasAgreementId ? entity.AgreementId : null,
            ProcuringEntity = hasProcuringEntity && entity.ProcuringEntity != null
                ? new OrganizationProjection
                {
                    Id = entity.ProcuringEntity.Id,
                }
                : null,
        };
    }

    protected override void MapAllFields(
        Tender entity,
        TenderProjection result,
        bool deep,
        int maxDepth,
        int currentDepth)
    {
        // Map all scalar properties
        result.Id = entity.Id;
        result.CreatedAt = entity.CreatedAt;
        result.UpdatedAt = entity.UpdatedAt;
        result.ExternalId = entity.ExternalId;
        result.TenderNumber = entity.TenderNumber;
        result.Title = entity.Title;
        result.Description = entity.Description;
        result.Owner = entity.Owner;
        result.Status = entity.Status;
        result.ProcurementMethodType = entity.ProcurementMethodType;
        result.AwardCriteria = entity.AwardCriteria;
        result.ProcurementMethod = entity.ProcurementMethod;
        result.MainProcurementCategory = entity.MainProcurementCategory;
        result.TotalAmount = entity.TotalAmount;
        result.Currency = entity.Currency;
        result.ValueAddedTaxIncluded = entity.ValueAddedTaxIncluded;
        result.TenderPeriodStart = entity.TenderPeriodStart;
        result.TenderPeriodEnd = entity.TenderPeriodEnd;
        result.AwardPeriodStart = entity.AwardPeriodStart;
        result.AwardPeriodEnd = entity.AwardPeriodEnd;
        result.NoticePublicationDate = entity.NoticePublicationDate;
        result.TenderDate = entity.TenderDate;
        result.AgreementId = entity.AgreementId;

        // Map related entities with depth control
        if (deep && currentDepth < maxDepth && entity.ProcuringEntity != null)
        {
            var procuringEntityProjection = ProjectionRequest.AllDeep(maxDepth - currentDepth - 1);
            result.ProcuringEntity = _organizationMapper.Map(
                entity.ProcuringEntity,
                procuringEntityProjection,
                currentDepth + 1
            );
        }
    }

    protected override void MapField(
        Tender entity,
        TenderProjection result,
        FieldProjection field,
        int currentDepth)
    {
        var fieldName = field.FieldName.ToLower();
        
        switch (fieldName)
        {
            case "id":
                result.Id = entity.Id;
                break;
            case "createdAt":
                result.CreatedAt = entity.CreatedAt;
                break;
            case "updatedAt":
                result.UpdatedAt = entity.UpdatedAt;
                break;
            case "externalId":
                result.ExternalId = entity.ExternalId;
                break;
            case "tenderNumber":
                result.TenderNumber = entity.TenderNumber;
                break;
            case "title":
                result.Title = entity.Title;
                break;
            case "description":
                result.Description = entity.Description;
                break;
            case "owner":
                result.Owner = entity.Owner;
                break;
            case "status":
                result.Status = entity.Status;
                break;
            case "procurementMethodType":
                result.ProcurementMethodType = entity.ProcurementMethodType;
                break;
            case "awardCriteria":
                result.AwardCriteria = entity.AwardCriteria;
                break;
            case "procurementMethod":
                result.ProcurementMethod = entity.ProcurementMethod;
                break;
            case "mainProcurementCategory":
                result.MainProcurementCategory = entity.MainProcurementCategory;
                break;
            case "totalAmount":
                result.TotalAmount = entity.TotalAmount;
                break;
            case "currency":
                result.Currency = entity.Currency;
                break;
            case "valueAddedTaxIncluded":
                result.ValueAddedTaxIncluded = entity.ValueAddedTaxIncluded;
                break;
            case "tenderPeriodStart":
                result.TenderPeriodStart = entity.TenderPeriodStart;
                break;
            case "tenderPeriodEnd":
                result.TenderPeriodEnd = entity.TenderPeriodEnd;
                break;
            case "awardPeriodStart":
                result.AwardPeriodStart = entity.AwardPeriodStart;
                break;
            case "awardPeriodEnd":
                result.AwardPeriodEnd = entity.AwardPeriodEnd;
                break;
            case "noticePublicationDate":
                result.NoticePublicationDate = entity.NoticePublicationDate;
                break;
            case "tenderDate":
                result.TenderDate = entity.TenderDate;
                break;
            case "agreementId":
                result.AgreementId = entity.AgreementId;
                break;
            case "procuringEntity.id":
                if (entity.ProcuringEntity != null)
                {
                    result.ProcuringEntity ??= new OrganizationProjection();
                    result.ProcuringEntity.Id = entity.ProcuringEntity.Id;
                }
                break;
            case "procuringEntity.name":
                if (entity.ProcuringEntity != null)
                {
                    result.ProcuringEntity ??= new OrganizationProjection();
                    // Assuming related entity has Name property
                    // Adjust if needed
                }
                break;
        }
    }
}
