// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-618b8d7c
//     Generated: 2026-02-14 15:54:12 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;
using Inventorization.Commerce.Common.Enums;

namespace Inventorization.Commerce.DTO.Address;

/// <summary>
/// DTO for searching/filtering Address entities
/// </summary>
public class AddressSearchDTO : SearchDTO
{
    /// <summary>
    /// Customer ID
    /// </summary>
    public Guid? CustomerId { get; set; }

    /// <summary>
    /// Address type (Shipping or Billing)
    /// </summary>
    public AddressType AddressType { get; set; }

    /// <summary>
    /// Street address
    /// </summary>
    public string Street { get; set; }

    /// <summary>
    /// City
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// State or province
    /// </summary>
    public string State { get; set; }

    /// <summary>
    /// Postal or ZIP code
    /// </summary>
    public string PostalCode { get; set; }

    /// <summary>
    /// Country
    /// </summary>
    public string Country { get; set; }

    /// <summary>
    /// Whether this is the default address
    /// </summary>
    public bool? IsDefault { get; set; }

}
