// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Address;

/// <summary>
/// DTO for deleting a Address
/// </summary>
public class DeleteAddressDTO : DeleteDTO
{
    // Inherits Id from DeleteDTO base class
}
