// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-717476ad
//     Generated: 2026-02-15 18:29:05 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Inventorization.Commerce.Domain.Validators;
using Inventorization.Commerce.DTO.Customer;

namespace Inventorization.Commerce.API.Tests.Validators;

public class CustomerValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateCustomerValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateCustomerDTO dto)
    {
        var validator = new CreateCustomerValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateCustomerValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateCustomerDTO dto)
    {
        var validator = new UpdateCustomerValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.FirstName = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.FirstName = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.LastName = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.LastName = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Email = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.Email = new string('a', 256)) },
        new object[] { CreateValidCreateDto(dto => dto.Email = "invalid-email") },
        new object[] { CreateValidCreateDto(dto => dto.Phone = new string('a', 21)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.FirstName = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.FirstName = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.LastName = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.LastName = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Email = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Email = new string('a', 256)) },
        new object[] { CreateValidUpdateDto(dto => dto.Email = "invalid-email") },
        new object[] { CreateValidUpdateDto(dto => dto.Phone = new string('a', 21)) },
    };

    private static CreateCustomerDTO CreateValidCreateDto(Action<CreateCustomerDTO>? mutate = null)
    {
        var dto = new CreateCustomerDTO
        {
            FirstName = new string('a', 1),
            LastName = new string('a', 1),
            Email = "user@example.com",
            Phone = new string('a', 1),
            IsActive = true,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateCustomerDTO CreateValidUpdateDto(Action<UpdateCustomerDTO>? mutate = null)
    {
        var dto = new UpdateCustomerDTO
        {
            Id = Guid.NewGuid(),
            FirstName = new string('a', 1),
            LastName = new string('a', 1),
            Email = "user@example.com",
            Phone = new string('a', 1),
            IsActive = true,
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
