// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Inventorization.Commerce.Domain.Validators;
using Inventorization.Commerce.DTO.Order;

namespace Inventorization.Commerce.API.Tests.Validators;

public class OrderValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateOrderValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateOrderDTO dto)
    {
        var validator = new CreateOrderValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateOrderValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateOrderDTO dto)
    {
        var validator = new UpdateOrderValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.OrderNumber = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.OrderNumber = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.OrderNumber = "invalid") },
        new object[] { CreateValidCreateDto(dto => dto.TotalAmount = (0m - 1m)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.OrderNumber = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.OrderNumber = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.OrderNumber = "invalid") },
        new object[] { CreateValidUpdateDto(dto => dto.TotalAmount = (0m - 1m)) },
    };

    private static CreateOrderDTO CreateValidCreateDto(Action<CreateOrderDTO>? mutate = null)
    {
        var dto = new CreateOrderDTO
        {
            OrderNumber = "ORD-00000001",
            OrderDate = DateTime.UtcNow,
            TotalAmount = 0m,
            Status = OrderStatus.Pending,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateOrderDTO CreateValidUpdateDto(Action<UpdateOrderDTO>? mutate = null)
    {
        var dto = new UpdateOrderDTO
        {
            Id = Guid.NewGuid(),
            OrderNumber = "ORD-00000001",
            OrderDate = DateTime.UtcNow,
            TotalAmount = 0m,
            Status = OrderStatus.Pending,
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
