// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.DTO.TenderPlan;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Validators;

/// <summary>
/// Validator for UpdateTenderPlanDTO
/// </summary>
public class UpdateTenderPlanValidator : IValidator<UpdateTenderPlanDTO>
{
    public Task<ValidationResult> ValidateAsync(
        UpdateTenderPlanDTO dto,
        CancellationToken cancellationToken = default)
    {
        if (dto == null)
            return Task.FromResult(ValidationResult.WithErrors("DTO cannot be null"));

        var errors = new List<string>(8);

        if (dto.Id == Guid.Empty)
    errors.Add("Id is required");

        if (string.IsNullOrWhiteSpace(dto.PlanExternalId))
    errors.Add("PlanExternalId is required");

        if (!string.IsNullOrEmpty(dto.PlanExternalId) && dto.PlanExternalId.Length > 100)
    errors.Add("PlanExternalId cannot exceed 100 characters");


        return Task.FromResult(errors.Any()
            ? ValidationResult.WithErrors(errors.ToArray())
            : ValidationResult.Ok());
    }
}
