// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Validators;

/// <summary>
/// Validator for UpdateContractChangeRationaleTypeDTO
/// </summary>
public class UpdateContractChangeRationaleTypeValidator : IValidator<UpdateContractChangeRationaleTypeDTO>
{
    public Task<ValidationResult> ValidateAsync(
        UpdateContractChangeRationaleTypeDTO dto,
        CancellationToken cancellationToken = default)
    {
        if (dto == null)
            return Task.FromResult(ValidationResult.WithErrors("DTO cannot be null"));

        var errors = new List<string>(8);

        if (dto.Id == Guid.Empty)
    errors.Add("Id is required");

        if (string.IsNullOrWhiteSpace(dto.Code))
    errors.Add("Code is required");

        if (!string.IsNullOrEmpty(dto.Code) && dto.Code.Length > 100)
    errors.Add("Code cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.TitleEn) && dto.TitleEn.Length > 500)
    errors.Add("TitleEn cannot exceed 500 characters");

        if (!string.IsNullOrEmpty(dto.TitleUk) && dto.TitleUk.Length > 500)
    errors.Add("TitleUk cannot exceed 500 characters");

        if (!string.IsNullOrEmpty(dto.DescriptionEn) && dto.DescriptionEn.Length > 2000)
    errors.Add("DescriptionEn cannot exceed 2000 characters");

        if (!string.IsNullOrEmpty(dto.DescriptionUk) && dto.DescriptionUk.Length > 2000)
    errors.Add("DescriptionUk cannot exceed 2000 characters");


        return Task.FromResult(errors.Any()
            ? ValidationResult.WithErrors(errors.ToArray())
            : ValidationResult.Ok());
    }
}
