// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.DTO.Contract;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Validators;

/// <summary>
/// Validator for UpdateContractDTO
/// </summary>
public class UpdateContractValidator : IValidator<UpdateContractDTO>
{
    public Task<ValidationResult> ValidateAsync(
        UpdateContractDTO dto,
        CancellationToken cancellationToken = default)
    {
        if (dto == null)
            return Task.FromResult(ValidationResult.WithErrors("DTO cannot be null"));

        var errors = new List<string>(8);

        if (dto.Id == Guid.Empty)
    errors.Add("Id is required");

        if (string.IsNullOrWhiteSpace(dto.ExternalId))
    errors.Add("ExternalId is required");

        if (!string.IsNullOrEmpty(dto.ExternalId) && dto.ExternalId.Length > 100)
    errors.Add("ExternalId cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.ContractNumber) && dto.ContractNumber.Length > 100)
    errors.Add("ContractNumber cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.Title) && dto.Title.Length > 1000)
    errors.Add("Title cannot exceed 1000 characters");

        if (!string.IsNullOrEmpty(dto.Description) && dto.Description.Length > 4000)
    errors.Add("Description cannot exceed 4000 characters");

        if (!string.IsNullOrEmpty(dto.Currency) && dto.Currency.Length > 10)
    errors.Add("Currency cannot exceed 10 characters");

        if (!string.IsNullOrEmpty(dto.AwardExternalId) && dto.AwardExternalId.Length > 100)
    errors.Add("AwardExternalId cannot exceed 100 characters");


        return Task.FromResult(errors.Any()
            ? ValidationResult.WithErrors(errors.ToArray())
            : ValidationResult.Ok());
    }
}
