// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.DTO.Criterion;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Validators;

/// <summary>
/// Validator for UpdateCriterionDTO
/// </summary>
public class UpdateCriterionValidator : IValidator<UpdateCriterionDTO>
{
    public Task<ValidationResult> ValidateAsync(
        UpdateCriterionDTO dto,
        CancellationToken cancellationToken = default)
    {
        if (dto == null)
            return Task.FromResult(ValidationResult.WithErrors("DTO cannot be null"));

        var errors = new List<string>(8);

        if (dto.Id == Guid.Empty)
    errors.Add("Id is required");

        if (string.IsNullOrWhiteSpace(dto.ExternalId))
    errors.Add("ExternalId is required");

        if (!string.IsNullOrEmpty(dto.ExternalId) && dto.ExternalId.Length > 100)
    errors.Add("ExternalId cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.Title) && dto.Title.Length > 500)
    errors.Add("Title cannot exceed 500 characters");

        if (!string.IsNullOrEmpty(dto.Description) && dto.Description.Length > 2000)
    errors.Add("Description cannot exceed 2000 characters");

        if (!string.IsNullOrEmpty(dto.Source) && dto.Source.Length > 100)
    errors.Add("Source cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.RelatesTo) && dto.RelatesTo.Length > 100)
    errors.Add("RelatesTo cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.RelatedItem) && dto.RelatedItem.Length > 100)
    errors.Add("RelatedItem cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.ClassificationScheme) && dto.ClassificationScheme.Length > 100)
    errors.Add("ClassificationScheme cannot exceed 100 characters");

        if (!string.IsNullOrEmpty(dto.ClassificationId) && dto.ClassificationId.Length > 100)
    errors.Add("ClassificationId cannot exceed 100 characters");


        return Task.FromResult(errors.Any()
            ? ValidationResult.WithErrors(errors.ToArray())
            : ValidationResult.Ok());
    }
}
