// <auto-generated>
//     This file is generated by the code generator.
//     Any changes made to this file will be overwritten.
// </auto-generated>

global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;





global using Xunit;
global using FluentAssertions;
global using Moq;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Inventorization.Base.Abstractions;
global using Inventorization.Base.DataAccess;
global using Inventorization.Base.Services;
global using Inventorization.Base.ADTs;
global using Inventorization.Commerce.Domain;
global using Inventorization.Commerce.DTO;
global using Inventorization.Commerce.Common.Enums;

