// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.DTOs;

namespace EnergyBrockerage.Prozorro.DTO.BidItem;

/// <summary>
/// DTO for searching/filtering BidItem entities
/// </summary>
public class BidItemSearchDTO : SearchDTO
{
    /// <summary>
    /// References the corresponding TenderItem external ID
    /// </summary>
    public string ExternalId { get; set; }

    /// <summary>
    /// Item description as stated in the bid
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Quantity offered
    /// </summary>
    public decimal? Quantity { get; set; }

    /// <summary>
    /// Unit of measurement name
    /// </summary>
    public string UnitName { get; set; }

    /// <summary>
    /// UN/CEFACT unit code
    /// </summary>
    public string UnitCode { get; set; }

    /// <summary>
    /// Price per unit (net)
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// Currency for the unit price
    /// </summary>
    public string UnitPriceCurrency { get; set; }

    /// <summary>
    /// Parent bid
    /// </summary>
    public Guid? BidId { get; set; }

}
