// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.DTOs;

namespace EnergyBrockerage.Prozorro.DTO.AwardDocument;

/// <summary>
/// DTO with detailed information about a AwardDocument
/// </summary>
public class AwardDocumentDetailsDTO : DetailsDTO<Guid>
{
}
