// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.OrderItem;

/// <summary>
/// DTO with detailed information about a OrderItem
/// </summary>
public class OrderItemDetailsDTO : DetailsDTO
{
    /// <summary>
    /// Order ID
    /// </summary>
    public Guid OrderId { get; set; }

    /// <summary>
    /// Product ID
    /// </summary>
    public Guid ProductId { get; set; }

    /// <summary>
    /// Quantity ordered
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// Price per unit at time of order
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Total price for this line item
    /// </summary>
    public decimal TotalPrice { get; set; }

}
