// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-76e7efc9
//     Generated: 2026-02-14 15:34:46 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.Text.Json.Serialization;

namespace Inventorization.Commerce.DTO.ADTs;

/// <summary>
/// Projection DTO for Address entity.
/// All properties are nullable to support selective projection.
/// </summary>
public class AddressProjection
{
    [JsonPropertyName("addressType")]
    public int? AddressType { get; set; }

    [JsonPropertyName("street")]
    public string Street { get; set; }

    [JsonPropertyName("city")]
    public string City { get; set; }

    [JsonPropertyName("state")]
    public string State { get; set; }

    [JsonPropertyName("postalCode")]
    public string PostalCode { get; set; }

    [JsonPropertyName("country")]
    public string Country { get; set; }

    [JsonPropertyName("isDefault")]
    public bool? IsDefault { get; set; }

    [JsonPropertyName("customer")]
    public CustomerProjection? Customer { get; set; }

}
