// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace Inventorization.Commerce.Domain.Constants;

/// <summary>
/// Searchable field names for Address entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class AddressSearchFields
{
    // Direct properties
    public const string CustomerId = "CustomerId";
    public const string AddressType = "AddressType";
    public const string Street = "Street";
    public const string City = "City";
    public const string State = "State";
    public const string PostalCode = "PostalCode";
    public const string Country = "Country";
    public const string IsDefault = "IsDefault";


    /// <summary>
    /// All valid search fields for Address.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        CustomerId,
        AddressType,
        Street,
        City,
        State,
        PostalCode,
        Country,
        IsDefault,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
