// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-b67fcc4b
//     Generated: 2026-02-14 16:17:38 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace Inventorization.Commerce.DTO.ADTs;

/// <summary>
/// Projection DTO for Category entity.
/// All properties are nullable to support selective projection.
/// </summary>
public class CategoryProjection
{
    [JsonPropertyName("id")]
    public Guid? Id { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTime? CreatedAt { get; set; }

    [JsonPropertyName("updatedAt")]
    public DateTime? UpdatedAt { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("isActive")]
    public bool? IsActive { get; set; }

}
