// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace Inventorization.Commerce.Domain.Constants;

/// <summary>
/// Searchable field names for Category entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class CategorySearchFields
{
    // Direct properties
    public const string Name = "Name";
    public const string Description = "Description";
    public const string IsActive = "IsActive";


    /// <summary>
    /// All valid search fields for Category.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        Name,
        Description,
        IsActive,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
