// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-e497403a
//     Generated: 2026-02-14 16:34:58 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace Inventorization.Commerce.Domain.Constants;

/// <summary>
/// Searchable field names for Customer entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class CustomerSearchFields
{
    // Direct properties
    public const string FirstName = "FirstName";
    public const string LastName = "LastName";
    public const string Email = "Email";
    public const string Phone = "Phone";
    public const string IsActive = "IsActive";


    /// <summary>
    /// All valid search fields for Customer.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        FirstName,
        LastName,
        Email,
        Phone,
        IsActive,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
