// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace Inventorization.Commerce.Domain.Constants;

/// <summary>
/// Searchable field names for Order entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class OrderSearchFields
{
    // Direct properties
    public const string CustomerId = "CustomerId";
    public const string OrderNumber = "OrderNumber";
    public const string OrderDate = "OrderDate";
    public const string TotalAmount = "TotalAmount";
    public const string Status = "Status";
    public const string ShippingAddressId = "ShippingAddressId";


    /// <summary>
    /// All valid search fields for Order.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        CustomerId,
        OrderNumber,
        OrderDate,
        TotalAmount,
        Status,
        ShippingAddressId,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
