// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-618b8d7c
//     Generated: 2026-02-14 15:54:12 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace Inventorization.Commerce.Domain.Constants;

/// <summary>
/// Searchable field names for Product entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class ProductSearchFields
{
    // Direct properties
    public const string Name = "Name";
    public const string SKU = "SKU";
    public const string Description = "Description";
    public const string Price = "Price";
    public const string StockQuantity = "StockQuantity";
    public const string CategoryId = "CategoryId";
    public const string Status = "Status";
    public const string IsActive = "IsActive";


    /// <summary>
    /// All valid search fields for Product.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        Name,
        SKU,
        Description,
        Price,
        StockQuantity,
        CategoryId,
        Status,
        IsActive,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
