// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.DTO.Address;
using Inventorization.Base.Services;
using Inventorization.Base.DataAccess;
using Inventorization.Base.Abstractions;
using Inventorization.Base.Ownership;
using Microsoft.Extensions.Logging;

namespace Inventorization.Commerce.BL.DataServices;

/// <summary>
/// Data service interface for Address
/// </summary>
public interface IAddressDataService : IDataService<Address, CreateAddressDTO, UpdateAddressDTO, DeleteAddressDTO, InitAddressDTO, AddressDetailsDTO, AddressSearchDTO>
{
}

/// <summary>
/// Data service implementation for Address
/// </summary>
public class AddressDataService : DataServiceBase<UserTenantOwnership, Address, CreateAddressDTO, UpdateAddressDTO, DeleteAddressDTO, InitAddressDTO, AddressDetailsDTO, AddressSearchDTO>, IAddressDataService
{
    public AddressDataService(
        Inventorization.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<Address> repository,
        IServiceProvider serviceProvider,
        ICurrentIdentityContext<UserTenantOwnership> identityContext,
        ILogger<AddressDataService> logger)
        : base(unitOfWork, repository, serviceProvider, identityContext, logger)
    {
    }
}
