// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

using Inventorization.Base.Abstractions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.ADTs;

namespace Inventorization.Commerce.Domain.Mappers.Projection;

/// <summary>
/// Marker interface for Customer projection mapper.
/// Enables type-safe dependency injection for nested mappers.
/// </summary>
public interface ICustomerProjectionMapper : IProjectionMapper<Customer, CustomerProjection> 
{ 
}
