// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-618b8d7c
//     Generated: 2026-02-14 15:54:12 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

using Inventorization.Base.Abstractions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.ADTs;

namespace Inventorization.Commerce.Domain.Mappers.Projection;

/// <summary>
/// Marker interface for Order projection mapper.
/// Enables type-safe dependency injection for nested mappers.
/// </summary>
public interface IOrderProjectionMapper : IProjectionMapper<Order, OrderProjection> 
{ 
}
