// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-38d150ed
//     Generated: 2026-02-15 09:53:00 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

using Inventorization.Base.Abstractions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.ADTs;

namespace Inventorization.Commerce.Domain.Mappers.Projection;

/// <summary>
/// Marker interface for OrderItem projection mapper.
/// Enables type-safe dependency injection for nested mappers.
/// </summary>
public interface IOrderItemProjectionMapper : IProjectionMapper<OrderItem, OrderItemProjection> 
{ 
}
