// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Entities;

/// <summary>
/// Junction entity representing the many-to-many relationship between Award and Document
/// </summary>
public class AwardDocument : JunctionEntityBase<Guid, Guid>
{
    /// <summary>
    /// Private parameterless constructor for EF Core
    /// </summary>
    private AwardDocument() : base(default(Guid)!, default(Guid)!) { }

    /// <summary>
    /// Creates a new instance of AwardDocument
    /// </summary>
    /// <param name="awardId">ID of the Award</param>
    /// <param name="documentId">ID of the Document</param>
    public AwardDocument(
        Guid awardId,
        Guid documentId
    ) : base(awardId, documentId)
    {
    }

    /// <summary>
    /// Gets the Award ID (alias for EntityId)
    /// </summary>
    public Guid AwardId => EntityId;

    /// <summary>
    /// Gets the Document ID (alias for RelatedEntityId)
    /// </summary>
    public Guid DocumentId => RelatedEntityId;

    /// <summary>
    /// Navigation property to Award
    /// </summary>
    public Award Award { get; } = null!;

    /// <summary>
    /// Navigation property to Document
    /// </summary>
    public Document Document { get; } = null!;
}
