// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Onward.Base.Models;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.BL.Entities;

/// <summary>
/// Award decision issued to a supplier after bid evaluation
/// </summary>
public class Award : BaseEntity
{
    /// <summary>
    /// Private parameterless constructor for EF Core
    /// </summary>
    private Award() { }

    /// <summary>
    /// Creates a new instance of Award
    /// </summary>
    /// <param name="externalId">Prozorro award ID</param>
    /// <param name="status">Award status</param>
    /// <param name="awardDate">Date the award was issued</param>
    /// <param name="amount">Awarded contract value</param>
    /// <param name="currency">Award currency code</param>
    /// <param name="qualified">Whether the award passed qualification check</param>
    /// <param name="periodStart">Start of the award acceptance period</param>
    /// <param name="periodEnd">End of the award acceptance period</param>
    /// <param name="bidExternalId">External ID of the winning bid (from Prozorro)</param>
    /// <param name="tenderId">Parent tender</param>
    /// <param name="supplierId">Organization that received this award</param>
    public Award(
        string externalId,
        AwardStatus status,
        DateTimeWithOffset? awardDate,
        decimal? amount,
        string currency,
        bool? qualified,
        DateTimeWithOffset? periodStart,
        DateTimeWithOffset? periodEnd,
        string bidExternalId,
        Guid tenderId,
        Guid supplierId
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (currency.Length > 10) throw new ArgumentException("Currency cannot exceed 10 characters", nameof(currency));
        if (bidExternalId.Length > 100) throw new ArgumentException("BidExternalId cannot exceed 100 characters", nameof(bidExternalId));

        ExternalId = externalId;
        Status = status;
        AwardDate = awardDate;
        Amount = amount;
        Currency = currency;
        Qualified = qualified;
        PeriodStart = periodStart;
        PeriodEnd = periodEnd;
        BidExternalId = bidExternalId;
        TenderId = tenderId;
        SupplierId = supplierId;

        Id = Guid.NewGuid();
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Prozorro award ID
    /// </summary>
    public string ExternalId { get; private set; }

    /// <summary>
    /// Award status
    /// </summary>
    public AwardStatus Status { get; private set; } = AwardStatus.Pending;

    /// <summary>
    /// Date the award was issued
    /// </summary>
    public DateTimeWithOffset? AwardDate { get; private set; }

    /// <summary>
    /// Awarded contract value
    /// </summary>
    public decimal? Amount { get; private set; }

    /// <summary>
    /// Award currency code
    /// </summary>
    public string Currency { get; private set; }

    /// <summary>
    /// Whether the award passed qualification check
    /// </summary>
    public bool? Qualified { get; private set; } = false;

    /// <summary>
    /// Start of the award acceptance period
    /// </summary>
    public DateTimeWithOffset? PeriodStart { get; private set; }

    /// <summary>
    /// End of the award acceptance period
    /// </summary>
    public DateTimeWithOffset? PeriodEnd { get; private set; }

    /// <summary>
    /// External ID of the winning bid (from Prozorro)
    /// </summary>
    public string BidExternalId { get; private set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid TenderId { get; private set; }

    /// <summary>
    /// Organization that received this award
    /// </summary>
    public Guid SupplierId { get; private set; }

    /// <summary>
    /// Navigation to Tender
    /// </summary>
    public Tender Tender { get; } = null!;

    /// <summary>
    /// Navigation to Organization
    /// </summary>
    public Organization Supplier { get; } = null!;

    /// <summary>
    /// Junction collection: documents attached to this award
    /// </summary>
    public ICollection<AwardDocument> AwardDocuments { get; } = new List<AwardDocument>(10);

    /// <summary>
    /// Timestamp when the entity was created
    /// </summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// Updates Award with new values
    /// </summary>
    /// <param name="externalId">Prozorro award ID</param>
    /// <param name="status">Award status</param>
    /// <param name="awardDate">Date the award was issued</param>
    /// <param name="amount">Awarded contract value</param>
    /// <param name="currency">Award currency code</param>
    /// <param name="qualified">Whether the award passed qualification check</param>
    /// <param name="periodStart">Start of the award acceptance period</param>
    /// <param name="periodEnd">End of the award acceptance period</param>
    /// <param name="bidExternalId">External ID of the winning bid (from Prozorro)</param>
    public void Update(
        string externalId,
        AwardStatus status,
        DateTimeWithOffset? awardDate,
        decimal? amount,
        string currency,
        bool? qualified,
        DateTimeWithOffset? periodStart,
        DateTimeWithOffset? periodEnd,
        string bidExternalId
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (currency.Length > 10) throw new ArgumentException("Currency cannot exceed 10 characters", nameof(currency));
        if (bidExternalId.Length > 100) throw new ArgumentException("BidExternalId cannot exceed 100 characters", nameof(bidExternalId));

        ExternalId = externalId;
        Status = status;
        AwardDate = awardDate;
        Amount = amount;
        Currency = currency;
        Qualified = qualified;
        PeriodStart = periodStart;
        PeriodEnd = periodEnd;
        BidExternalId = bidExternalId;

    }

    /// <summary>
    /// Parent tender
    /// </summary>
    /// <param name="tenderId">Tender identifier</param>
    public void SetTender(Guid tenderId)
    {
        TenderId = tenderId;
    }

    /// <summary>
    /// Organization that received this award
    /// </summary>
    /// <param name="supplierId">Organization identifier</param>
    public void SetOrganization(Guid supplierId)
    {
        SupplierId = supplierId;
    }

}
