// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Onward.Base.Models;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.BL.Entities;

/// <summary>
/// Bid submitted by a tenderer in response to a tender
/// </summary>
public class Bid : BaseEntity
{
    /// <summary>
    /// Private parameterless constructor for EF Core
    /// </summary>
    private Bid() { }

    /// <summary>
    /// Creates a new instance of Bid
    /// </summary>
    /// <param name="externalId">Prozorro bid ID</param>
    /// <param name="status">Bid status</param>
    /// <param name="bidDate">Date the bid record was created</param>
    /// <param name="submissionDate">Date the bid was officially submitted</param>
    /// <param name="amount">Bid price amount</param>
    /// <param name="currency">Bid currency code</param>
    /// <param name="valueAddedTaxIncluded">Whether the bid amount includes VAT</param>
    /// <param name="initialAmount">Initial bid amount before any auction changes</param>
    /// <param name="tenderId">Parent tender</param>
    /// <param name="tendererId">Organization that submitted this bid</param>
    public Bid(
        string externalId,
        BidStatus status,
        DateTimeWithOffset? bidDate,
        DateTimeWithOffset? submissionDate,
        decimal? amount,
        string currency,
        bool? valueAddedTaxIncluded,
        decimal? initialAmount,
        Guid tenderId,
        Guid tendererId
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (currency.Length > 10) throw new ArgumentException("Currency cannot exceed 10 characters", nameof(currency));

        ExternalId = externalId;
        Status = status;
        BidDate = bidDate;
        SubmissionDate = submissionDate;
        Amount = amount;
        Currency = currency;
        ValueAddedTaxIncluded = valueAddedTaxIncluded;
        InitialAmount = initialAmount;
        TenderId = tenderId;
        TendererId = tendererId;

        Id = Guid.NewGuid();
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Prozorro bid ID
    /// </summary>
    public string ExternalId { get; private set; }

    /// <summary>
    /// Bid status
    /// </summary>
    public BidStatus Status { get; private set; } = BidStatus.Draft;

    /// <summary>
    /// Date the bid record was created
    /// </summary>
    public DateTimeWithOffset? BidDate { get; private set; }

    /// <summary>
    /// Date the bid was officially submitted
    /// </summary>
    public DateTimeWithOffset? SubmissionDate { get; private set; }

    /// <summary>
    /// Bid price amount
    /// </summary>
    public decimal? Amount { get; private set; }

    /// <summary>
    /// Bid currency code
    /// </summary>
    public string Currency { get; private set; }

    /// <summary>
    /// Whether the bid amount includes VAT
    /// </summary>
    public bool? ValueAddedTaxIncluded { get; private set; } = true;

    /// <summary>
    /// Initial bid amount before any auction changes
    /// </summary>
    public decimal? InitialAmount { get; private set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid TenderId { get; private set; }

    /// <summary>
    /// Organization that submitted this bid
    /// </summary>
    public Guid TendererId { get; private set; }

    /// <summary>
    /// Navigation to Tender
    /// </summary>
    public Tender Tender { get; } = null!;

    /// <summary>
    /// Navigation to Organization
    /// </summary>
    public Organization Tenderer { get; } = null!;

    /// <summary>
    /// Junction collection: documents attached to this bid
    /// </summary>
    public ICollection<BidDocument> BidDocuments { get; } = new List<BidDocument>(10);

    /// <summary>
    /// Collection of BidItem
    /// </summary>
    public ICollection<BidItem> Items { get; } = new List<BidItem>(10);

    /// <summary>
    /// Timestamp when the entity was created
    /// </summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// Updates Bid with new values
    /// </summary>
    /// <param name="externalId">Prozorro bid ID</param>
    /// <param name="status">Bid status</param>
    /// <param name="bidDate">Date the bid record was created</param>
    /// <param name="submissionDate">Date the bid was officially submitted</param>
    /// <param name="amount">Bid price amount</param>
    /// <param name="currency">Bid currency code</param>
    /// <param name="valueAddedTaxIncluded">Whether the bid amount includes VAT</param>
    /// <param name="initialAmount">Initial bid amount before any auction changes</param>
    public void Update(
        string externalId,
        BidStatus status,
        DateTimeWithOffset? bidDate,
        DateTimeWithOffset? submissionDate,
        decimal? amount,
        string currency,
        bool? valueAddedTaxIncluded,
        decimal? initialAmount
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (currency.Length > 10) throw new ArgumentException("Currency cannot exceed 10 characters", nameof(currency));

        ExternalId = externalId;
        Status = status;
        BidDate = bidDate;
        SubmissionDate = submissionDate;
        Amount = amount;
        Currency = currency;
        ValueAddedTaxIncluded = valueAddedTaxIncluded;
        InitialAmount = initialAmount;

    }

    /// <summary>
    /// Parent tender
    /// </summary>
    /// <param name="tenderId">Tender identifier</param>
    public void SetTender(Guid tenderId)
    {
        TenderId = tenderId;
    }

    /// <summary>
    /// Organization that submitted this bid
    /// </summary>
    /// <param name="tendererId">Organization identifier</param>
    public void SetOrganization(Guid tendererId)
    {
        TendererId = tendererId;
    }

}
