// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Onward.Base.Models;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.BL.Entities;

/// <summary>
/// Procurement contract signed as a result of a tender award
/// </summary>
public class Contract : BaseEntity
{
    /// <summary>
    /// Private parameterless constructor for EF Core
    /// </summary>
    private Contract() { }

    /// <summary>
    /// Creates a new instance of Contract
    /// </summary>
    /// <param name="externalId">Prozorro contract ID</param>
    /// <param name="contractNumber">Human-readable contract number (contractID from Prozorro)</param>
    /// <param name="title">Contract title</param>
    /// <param name="description">Contract description</param>
    /// <param name="status">Contract status</param>
    /// <param name="contractDate">Date the contract was signed</param>
    /// <param name="amount">Contract monetary value</param>
    /// <param name="currency">Contract currency code</param>
    /// <param name="awardExternalId">External ID of the related award (awardID from Prozorro)</param>
    /// <param name="tenderId">Parent tender</param>
    public Contract(
        string externalId,
        string contractNumber,
        string title,
        string description,
        ContractStatus status,
        DateTimeWithOffset? contractDate,
        decimal? amount,
        string currency,
        string awardExternalId,
        Guid tenderId
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (contractNumber.Length > 100) throw new ArgumentException("ContractNumber cannot exceed 100 characters", nameof(contractNumber));
        if (title.Length > 1000) throw new ArgumentException("Title cannot exceed 1000 characters", nameof(title));
        if (description.Length > 4000) throw new ArgumentException("Description cannot exceed 4000 characters", nameof(description));
        if (currency.Length > 10) throw new ArgumentException("Currency cannot exceed 10 characters", nameof(currency));
        if (awardExternalId.Length > 100) throw new ArgumentException("AwardExternalId cannot exceed 100 characters", nameof(awardExternalId));

        ExternalId = externalId;
        ContractNumber = contractNumber;
        Title = title;
        Description = description;
        Status = status;
        ContractDate = contractDate;
        Amount = amount;
        Currency = currency;
        AwardExternalId = awardExternalId;
        TenderId = tenderId;

        Id = Guid.NewGuid();
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Prozorro contract ID
    /// </summary>
    public string ExternalId { get; private set; }

    /// <summary>
    /// Human-readable contract number (contractID from Prozorro)
    /// </summary>
    public string ContractNumber { get; private set; }

    /// <summary>
    /// Contract title
    /// </summary>
    public string Title { get; private set; }

    /// <summary>
    /// Contract description
    /// </summary>
    public string Description { get; private set; }

    /// <summary>
    /// Contract status
    /// </summary>
    public ContractStatus Status { get; private set; } = ContractStatus.Pending;

    /// <summary>
    /// Date the contract was signed
    /// </summary>
    public DateTimeWithOffset? ContractDate { get; private set; }

    /// <summary>
    /// Contract monetary value
    /// </summary>
    public decimal? Amount { get; private set; }

    /// <summary>
    /// Contract currency code
    /// </summary>
    public string Currency { get; private set; }

    /// <summary>
    /// External ID of the related award (awardID from Prozorro)
    /// </summary>
    public string AwardExternalId { get; private set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid TenderId { get; private set; }

    /// <summary>
    /// Navigation to Tender
    /// </summary>
    public Tender Tender { get; } = null!;

    /// <summary>
    /// Timestamp when the entity was created
    /// </summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// Updates Contract with new values
    /// </summary>
    /// <param name="externalId">Prozorro contract ID</param>
    /// <param name="contractNumber">Human-readable contract number (contractID from Prozorro)</param>
    /// <param name="title">Contract title</param>
    /// <param name="description">Contract description</param>
    /// <param name="status">Contract status</param>
    /// <param name="contractDate">Date the contract was signed</param>
    /// <param name="amount">Contract monetary value</param>
    /// <param name="currency">Contract currency code</param>
    /// <param name="awardExternalId">External ID of the related award (awardID from Prozorro)</param>
    public void Update(
        string externalId,
        string contractNumber,
        string title,
        string description,
        ContractStatus status,
        DateTimeWithOffset? contractDate,
        decimal? amount,
        string currency,
        string awardExternalId
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (contractNumber.Length > 100) throw new ArgumentException("ContractNumber cannot exceed 100 characters", nameof(contractNumber));
        if (title.Length > 1000) throw new ArgumentException("Title cannot exceed 1000 characters", nameof(title));
        if (description.Length > 4000) throw new ArgumentException("Description cannot exceed 4000 characters", nameof(description));
        if (currency.Length > 10) throw new ArgumentException("Currency cannot exceed 10 characters", nameof(currency));
        if (awardExternalId.Length > 100) throw new ArgumentException("AwardExternalId cannot exceed 100 characters", nameof(awardExternalId));

        ExternalId = externalId;
        ContractNumber = contractNumber;
        Title = title;
        Description = description;
        Status = status;
        ContractDate = contractDate;
        Amount = amount;
        Currency = currency;
        AwardExternalId = awardExternalId;

    }

    /// <summary>
    /// Parent tender
    /// </summary>
    /// <param name="tenderId">Tender identifier</param>
    public void SetTender(Guid tenderId)
    {
        TenderId = tenderId;
    }

}
