// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Onward.Base.Models;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.BL.Entities;

/// <summary>
/// Procuring entity or tenderer organization imported from Prozorro
/// </summary>
public class Organization : BaseEntity
{
    /// <summary>
    /// Private parameterless constructor for EF Core
    /// </summary>
    private Organization() { }

    /// <summary>
    /// Creates a new instance of Organization
    /// </summary>
    /// <param name="externalId">Prozorro organization identifier value (e.g. EDRPOU code)</param>
    /// <param name="identifierScheme">Identifier scheme (e.g. UA-EDR)</param>
    /// <param name="name">Organization name in Ukrainian</param>
    /// <param name="nameEn">Organization name in English</param>
    /// <param name="legalName">Legal registered name</param>
    /// <param name="legalNameEn">Legal name in English</param>
    /// <param name="kind">Procuring entity kind classification</param>
    /// <param name="scale">Business size classification</param>
    /// <param name="streetAddress">Street address</param>
    /// <param name="locality">City or locality</param>
    /// <param name="region">Region or oblast</param>
    /// <param name="postalCode">Postal code</param>
    /// <param name="countryName">Country name</param>
    /// <param name="contactName">Contact person full name</param>
    /// <param name="contactEmail">Contact email address</param>
    /// <param name="contactPhone">Contact telephone number</param>
    /// <param name="contactUrl">Contact or official website URL</param>
    public Organization(
        string externalId,
        string identifierScheme,
        string name,
        string nameEn,
        string legalName,
        string legalNameEn,
        OrganizationKind kind,
        OrganizationScale scale,
        string streetAddress,
        string locality,
        string region,
        string postalCode,
        string countryName,
        string contactName,
        string contactEmail,
        string contactPhone,
        string contactUrl
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (string.IsNullOrWhiteSpace(identifierScheme)) throw new ArgumentException("IdentifierScheme cannot be empty", nameof(identifierScheme));
        if (identifierScheme.Length > 50) throw new ArgumentException("IdentifierScheme cannot exceed 50 characters", nameof(identifierScheme));
        if (string.IsNullOrWhiteSpace(name)) throw new ArgumentException("Name cannot be empty", nameof(name));
        if (name.Length > 500) throw new ArgumentException("Name cannot exceed 500 characters", nameof(name));
        if (nameEn.Length > 500) throw new ArgumentException("NameEn cannot exceed 500 characters", nameof(nameEn));
        if (string.IsNullOrWhiteSpace(legalName)) throw new ArgumentException("LegalName cannot be empty", nameof(legalName));
        if (legalName.Length > 500) throw new ArgumentException("LegalName cannot exceed 500 characters", nameof(legalName));
        if (legalNameEn.Length > 500) throw new ArgumentException("LegalNameEn cannot exceed 500 characters", nameof(legalNameEn));
        if (streetAddress.Length > 500) throw new ArgumentException("StreetAddress cannot exceed 500 characters", nameof(streetAddress));
        if (locality.Length > 200) throw new ArgumentException("Locality cannot exceed 200 characters", nameof(locality));
        if (region.Length > 200) throw new ArgumentException("Region cannot exceed 200 characters", nameof(region));
        if (postalCode.Length > 20) throw new ArgumentException("PostalCode cannot exceed 20 characters", nameof(postalCode));
        if (countryName.Length > 100) throw new ArgumentException("CountryName cannot exceed 100 characters", nameof(countryName));
        if (contactName.Length > 300) throw new ArgumentException("ContactName cannot exceed 300 characters", nameof(contactName));
        if (contactEmail.Length > 255) throw new ArgumentException("ContactEmail cannot exceed 255 characters", nameof(contactEmail));
        if (contactPhone.Length > 100) throw new ArgumentException("ContactPhone cannot exceed 100 characters", nameof(contactPhone));
        if (contactUrl.Length > 500) throw new ArgumentException("ContactUrl cannot exceed 500 characters", nameof(contactUrl));

        ExternalId = externalId;
        IdentifierScheme = identifierScheme;
        Name = name;
        NameEn = nameEn;
        LegalName = legalName;
        LegalNameEn = legalNameEn;
        Kind = kind;
        Scale = scale;
        StreetAddress = streetAddress;
        Locality = locality;
        Region = region;
        PostalCode = postalCode;
        CountryName = countryName;
        ContactName = contactName;
        ContactEmail = contactEmail;
        ContactPhone = contactPhone;
        ContactUrl = contactUrl;

        Id = Guid.NewGuid();
        CreatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Prozorro organization identifier value (e.g. EDRPOU code)
    /// </summary>
    public string ExternalId { get; private set; }

    /// <summary>
    /// Identifier scheme (e.g. UA-EDR)
    /// </summary>
    public string IdentifierScheme { get; private set; }

    /// <summary>
    /// Organization name in Ukrainian
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    /// Organization name in English
    /// </summary>
    public string NameEn { get; private set; }

    /// <summary>
    /// Legal registered name
    /// </summary>
    public string LegalName { get; private set; }

    /// <summary>
    /// Legal name in English
    /// </summary>
    public string LegalNameEn { get; private set; }

    /// <summary>
    /// Procuring entity kind classification
    /// </summary>
    public OrganizationKind Kind { get; private set; } = OrganizationKind.General;

    /// <summary>
    /// Business size classification
    /// </summary>
    public OrganizationScale Scale { get; private set; } = OrganizationScale.NotSpecified;

    /// <summary>
    /// Street address
    /// </summary>
    public string StreetAddress { get; private set; }

    /// <summary>
    /// City or locality
    /// </summary>
    public string Locality { get; private set; }

    /// <summary>
    /// Region or oblast
    /// </summary>
    public string Region { get; private set; }

    /// <summary>
    /// Postal code
    /// </summary>
    public string PostalCode { get; private set; }

    /// <summary>
    /// Country name
    /// </summary>
    public string CountryName { get; private set; }

    /// <summary>
    /// Contact person full name
    /// </summary>
    public string ContactName { get; private set; }

    /// <summary>
    /// Contact email address
    /// </summary>
    public string ContactEmail { get; private set; }

    /// <summary>
    /// Contact telephone number
    /// </summary>
    public string ContactPhone { get; private set; }

    /// <summary>
    /// Contact or official website URL
    /// </summary>
    public string ContactUrl { get; private set; }

    /// <summary>
    /// Collection of Tender
    /// </summary>
    public ICollection<Tender> ProcuredTenders { get; } = new List<Tender>(10);

    /// <summary>
    /// Collection of Bid
    /// </summary>
    public ICollection<Bid> SubmittedBids { get; } = new List<Bid>(10);

    /// <summary>
    /// Collection of Award
    /// </summary>
    public ICollection<Award> ReceivedAwards { get; } = new List<Award>(10);

    /// <summary>
    /// Timestamp when the entity was created
    /// </summary>
    public DateTime CreatedAt { get; private set; }

    /// <summary>
    /// Updates Organization with new values
    /// </summary>
    /// <param name="externalId">Prozorro organization identifier value (e.g. EDRPOU code)</param>
    /// <param name="identifierScheme">Identifier scheme (e.g. UA-EDR)</param>
    /// <param name="name">Organization name in Ukrainian</param>
    /// <param name="nameEn">Organization name in English</param>
    /// <param name="legalName">Legal registered name</param>
    /// <param name="legalNameEn">Legal name in English</param>
    /// <param name="kind">Procuring entity kind classification</param>
    /// <param name="scale">Business size classification</param>
    /// <param name="streetAddress">Street address</param>
    /// <param name="locality">City or locality</param>
    /// <param name="region">Region or oblast</param>
    /// <param name="postalCode">Postal code</param>
    /// <param name="countryName">Country name</param>
    /// <param name="contactName">Contact person full name</param>
    /// <param name="contactEmail">Contact email address</param>
    /// <param name="contactPhone">Contact telephone number</param>
    /// <param name="contactUrl">Contact or official website URL</param>
    public void Update(
        string externalId,
        string identifierScheme,
        string name,
        string nameEn,
        string legalName,
        string legalNameEn,
        OrganizationKind kind,
        OrganizationScale scale,
        string streetAddress,
        string locality,
        string region,
        string postalCode,
        string countryName,
        string contactName,
        string contactEmail,
        string contactPhone,
        string contactUrl
    )
    {
        if (string.IsNullOrWhiteSpace(externalId)) throw new ArgumentException("ExternalId cannot be empty", nameof(externalId));
        if (externalId.Length > 100) throw new ArgumentException("ExternalId cannot exceed 100 characters", nameof(externalId));
        if (string.IsNullOrWhiteSpace(identifierScheme)) throw new ArgumentException("IdentifierScheme cannot be empty", nameof(identifierScheme));
        if (identifierScheme.Length > 50) throw new ArgumentException("IdentifierScheme cannot exceed 50 characters", nameof(identifierScheme));
        if (string.IsNullOrWhiteSpace(name)) throw new ArgumentException("Name cannot be empty", nameof(name));
        if (name.Length > 500) throw new ArgumentException("Name cannot exceed 500 characters", nameof(name));
        if (nameEn.Length > 500) throw new ArgumentException("NameEn cannot exceed 500 characters", nameof(nameEn));
        if (string.IsNullOrWhiteSpace(legalName)) throw new ArgumentException("LegalName cannot be empty", nameof(legalName));
        if (legalName.Length > 500) throw new ArgumentException("LegalName cannot exceed 500 characters", nameof(legalName));
        if (legalNameEn.Length > 500) throw new ArgumentException("LegalNameEn cannot exceed 500 characters", nameof(legalNameEn));
        if (streetAddress.Length > 500) throw new ArgumentException("StreetAddress cannot exceed 500 characters", nameof(streetAddress));
        if (locality.Length > 200) throw new ArgumentException("Locality cannot exceed 200 characters", nameof(locality));
        if (region.Length > 200) throw new ArgumentException("Region cannot exceed 200 characters", nameof(region));
        if (postalCode.Length > 20) throw new ArgumentException("PostalCode cannot exceed 20 characters", nameof(postalCode));
        if (countryName.Length > 100) throw new ArgumentException("CountryName cannot exceed 100 characters", nameof(countryName));
        if (contactName.Length > 300) throw new ArgumentException("ContactName cannot exceed 300 characters", nameof(contactName));
        if (contactEmail.Length > 255) throw new ArgumentException("ContactEmail cannot exceed 255 characters", nameof(contactEmail));
        if (contactPhone.Length > 100) throw new ArgumentException("ContactPhone cannot exceed 100 characters", nameof(contactPhone));
        if (contactUrl.Length > 500) throw new ArgumentException("ContactUrl cannot exceed 500 characters", nameof(contactUrl));

        ExternalId = externalId;
        IdentifierScheme = identifierScheme;
        Name = name;
        NameEn = nameEn;
        LegalName = legalName;
        LegalNameEn = legalNameEn;
        Kind = kind;
        Scale = scale;
        StreetAddress = streetAddress;
        Locality = locality;
        Region = region;
        PostalCode = postalCode;
        CountryName = countryName;
        ContactName = contactName;
        ContactEmail = contactEmail;
        ContactPhone = contactPhone;
        ContactUrl = contactUrl;

    }

}
