// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Entities;

/// <summary>
/// Junction entity representing the many-to-many relationship between Tender and ContractChangeRationaleType
/// </summary>
public class TenderChangeRationale : JunctionEntityBase<Guid, Guid>
{
    /// <summary>
    /// Private parameterless constructor for EF Core
    /// </summary>
    private TenderChangeRationale() : base(default(Guid)!, default(Guid)!) { }

    /// <summary>
    /// Creates a new instance of TenderChangeRationale
    /// </summary>
    /// <param name="tenderId">ID of the Tender</param>
    /// <param name="contractChangeRationaleTypeId">ID of the ContractChangeRationaleType</param>
    public TenderChangeRationale(
        Guid tenderId,
        Guid contractChangeRationaleTypeId
    ) : base(tenderId, contractChangeRationaleTypeId)
    {
    }

    /// <summary>
    /// Gets the Tender ID (alias for EntityId)
    /// </summary>
    public Guid TenderId => EntityId;

    /// <summary>
    /// Gets the ContractChangeRationaleType ID (alias for RelatedEntityId)
    /// </summary>
    public Guid ContractChangeRationaleTypeId => RelatedEntityId;

    /// <summary>
    /// Navigation property to Tender
    /// </summary>
    public Tender Tender { get; } = null!;

    /// <summary>
    /// Navigation property to ContractChangeRationaleType
    /// </summary>
    public ContractChangeRationaleType ContractChangeRationaleType { get; } = null!;
}
