// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Category;

/// <summary>
/// DTO for searching/filtering Category entities
/// </summary>
public class CategorySearchDTO : SearchDTO
{
    /// <summary>
    /// Category name
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Category description
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Whether the category is active
    /// </summary>
    public bool? IsActive { get; set; }

}
