// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-38d150ed
//     Generated: 2026-02-15 09:53:00 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Category;

/// <summary>
/// DTO for creating a new Category
/// </summary>
public class CreateCategoryDTO : CreateDTO
{
    /// <summary>
    /// Category name
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Category description
    /// </summary>
    [StringLength(500)]
    public string Description { get; set; }

    /// <summary>
    /// Whether the category is active
    /// </summary>
    public bool IsActive { get; set; } = true;

}
