// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-717476ad
//     Generated: 2026-02-15 18:29:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Category;

/// <summary>
/// DTO for init operation on Category
/// </summary>
public record InitCategoryDTO(
    Guid Id,
    string Name,
    bool IsActive
) : InitDTO(Id);
