// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-b67fcc4b
//     Generated: 2026-02-14 16:17:38 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Category;

/// <summary>
/// DTO for updating an existing Category
/// </summary>
public class UpdateCategoryDTO : UpdateDTO
{
    /// <summary>
    /// Category name
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// Category description
    /// </summary>
    [StringLength(500)]
    public string Description { get; set; }

    /// <summary>
    /// Whether the category is active
    /// </summary>
    public bool IsActive { get; set; }

}
