// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.BL.Mappers;
using Inventorization.Commerce.DTO.Customer;

namespace Inventorization.Commerce.API.Tests.Mappers;

public class CustomerMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new CustomerMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.FirstName.Should().Be(entity.FirstName);
        result.LastName.Should().Be(entity.LastName);
        result.Email.Should().Be(entity.Email);
        result.Phone.Should().Be(entity.Phone);
        result.IsActive.Should().Be(entity.IsActive);
    }

    private static Customer CreateEntity()
    {
        return new Customer(
            new string('a', 1),
            new string('a', 1),
            "user@example.com",
            new string('a', 1),
            true
        );
    }
}
