// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.BL.Mappers;
using Inventorization.Commerce.DTO.OrderItem;

namespace Inventorization.Commerce.API.Tests.Mappers;

public class OrderItemMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new OrderItemMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.Quantity.Should().Be(entity.Quantity);
        result.UnitPrice.Should().Be(entity.UnitPrice);
        result.TotalPrice.Should().Be(entity.TotalPrice);
    }

    private static OrderItem CreateEntity()
    {
        return new OrderItem(
            Guid.NewGuid(),
            Guid.NewGuid(),
            1,
            0m,
            0m
        );
    }
}
