// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Criterion;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Mappers;

/// <summary>
/// Mapper for Criterion entities
/// </summary>
public class CriterionMapper : IMapper<Criterion, CriterionDetailsDTO>
{
    /// <summary>
    /// Maps Criterion entity to DetailsDTO
    /// </summary>
    public CriterionDetailsDTO Map(Criterion entity)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        return new CriterionDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Description = entity.Description,
            Source = entity.Source,
            RelatesTo = entity.RelatesTo,
            RelatedItem = entity.RelatedItem,
            ClassificationScheme = entity.ClassificationScheme,
            ClassificationId = entity.ClassificationId,
        };
    }

    /// <summary>
    /// Gets LINQ projection expression for Criterion
    /// </summary>
    public Expression<Func<Criterion, CriterionDetailsDTO>> GetProjection()
    {
        return entity => new CriterionDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Description = entity.Description,
            Source = entity.Source,
            RelatesTo = entity.RelatesTo,
            RelatedItem = entity.RelatedItem,
            ClassificationScheme = entity.ClassificationScheme,
            ClassificationId = entity.ClassificationId,
        };
    }
}
