// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Document;
using Onward.Base.Abstractions;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Mappers;

/// <summary>
/// Mapper for Document entities
/// </summary>
public class DocumentMapper : IMapper<Document, DocumentDetailsDTO>
{
    /// <summary>
    /// Maps Document entity to DetailsDTO
    /// </summary>
    public DocumentDetailsDTO Map(Document entity)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        return new DocumentDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Format = entity.Format,
            Url = entity.Url,
            Hash = entity.Hash,
            DocumentType = entity.DocumentType,
            Confidentiality = entity.Confidentiality,
            DocumentOf = entity.DocumentOf,
            RelatedItem = entity.RelatedItem,
            Author = entity.Author,
            Language = entity.Language,
            DatePublished = entity.DatePublished?.ToIso8601(),
            DateModified = entity.DateModified?.ToIso8601(),
        };
    }

    /// <summary>
    /// Gets LINQ projection expression for Document
    /// </summary>
    public Expression<Func<Document, DocumentDetailsDTO>> GetProjection()
    {
        return entity => new DocumentDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Format = entity.Format,
            Url = entity.Url,
            Hash = entity.Hash,
            DocumentType = entity.DocumentType,
            Confidentiality = entity.Confidentiality,
            DocumentOf = entity.DocumentOf,
            RelatedItem = entity.RelatedItem,
            Author = entity.Author,
            Language = entity.Language,
            DatePublished = null,
            DateModified = null,
        };
    }
}
