// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Milestone;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Mappers;

/// <summary>
/// Mapper for Milestone entities
/// </summary>
public class MilestoneMapper : IMapper<Milestone, MilestoneDetailsDTO>
{
    /// <summary>
    /// Maps Milestone entity to DetailsDTO
    /// </summary>
    public MilestoneDetailsDTO Map(Milestone entity)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        return new MilestoneDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Description = entity.Description,
            Type = entity.Type,
            Code = entity.Code,
            Percentage = entity.Percentage,
            DurationDays = entity.DurationDays,
            DurationType = entity.DurationType,
            SequenceNumber = entity.SequenceNumber,
        };
    }

    /// <summary>
    /// Gets LINQ projection expression for Milestone
    /// </summary>
    public Expression<Func<Milestone, MilestoneDetailsDTO>> GetProjection()
    {
        return entity => new MilestoneDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            Title = entity.Title,
            Description = entity.Description,
            Type = entity.Type,
            Code = entity.Code,
            Percentage = entity.Percentage,
            DurationDays = entity.DurationDays,
            DurationType = entity.DurationType,
            SequenceNumber = entity.SequenceNumber,
        };
    }
}
