// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Tender;
using Onward.Base.Abstractions;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Mappers;

/// <summary>
/// Mapper for Tender entities
/// </summary>
public class TenderMapper : IMapper<Tender, TenderDetailsDTO>
{
    /// <summary>
    /// Maps Tender entity to DetailsDTO
    /// </summary>
    public TenderDetailsDTO Map(Tender entity)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        return new TenderDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            TenderNumber = entity.TenderNumber,
            Title = entity.Title,
            Description = entity.Description,
            Owner = entity.Owner,
            Status = entity.Status,
            ProcurementMethodType = entity.ProcurementMethodType,
            AwardCriteria = entity.AwardCriteria,
            ProcurementMethod = entity.ProcurementMethod,
            MainProcurementCategory = entity.MainProcurementCategory,
            TotalAmount = entity.TotalAmount,
            Currency = entity.Currency,
            ValueAddedTaxIncluded = entity.ValueAddedTaxIncluded,
            TenderPeriodStart = entity.TenderPeriodStart?.ToIso8601(),
            TenderPeriodEnd = entity.TenderPeriodEnd?.ToIso8601(),
            AwardPeriodStart = entity.AwardPeriodStart?.ToIso8601(),
            AwardPeriodEnd = entity.AwardPeriodEnd?.ToIso8601(),
            NoticePublicationDate = entity.NoticePublicationDate?.ToIso8601(),
            TenderDate = entity.TenderDate?.ToIso8601(),
            AgreementId = entity.AgreementId,
        };
    }

    /// <summary>
    /// Gets LINQ projection expression for Tender
    /// </summary>
    public Expression<Func<Tender, TenderDetailsDTO>> GetProjection()
    {
        return entity => new TenderDetailsDTO
        {
            Id = entity.Id,
            ExternalId = entity.ExternalId,
            TenderNumber = entity.TenderNumber,
            Title = entity.Title,
            Description = entity.Description,
            Owner = entity.Owner,
            Status = entity.Status,
            ProcurementMethodType = entity.ProcurementMethodType,
            AwardCriteria = entity.AwardCriteria,
            ProcurementMethod = entity.ProcurementMethod,
            MainProcurementCategory = entity.MainProcurementCategory,
            TotalAmount = entity.TotalAmount,
            Currency = entity.Currency,
            ValueAddedTaxIncluded = entity.ValueAddedTaxIncluded,
            TenderPeriodStart = null,
            TenderPeriodEnd = null,
            AwardPeriodStart = null,
            AwardPeriodEnd = null,
            NoticePublicationDate = null,
            TenderDate = null,
            AgreementId = entity.AgreementId,
        };
    }
}
