// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-76e7efc9
//     Generated: 2026-02-14 15:34:46 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Product;

/// <summary>
/// DTO for deleting a Product
/// </summary>
public class DeleteProductDTO : DeleteDTO
{
    // Inherits Id from DeleteDTO base class
}
