// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;
using Inventorization.Commerce.Common.Enums;

namespace Inventorization.Commerce.DTO.Product;

/// <summary>
/// DTO for init operation on Product
/// </summary>
public record InitProductDTO(
    Guid Id,
    string Name,
    string SKU,
    decimal Price,
    int StockQuantity,
    Guid CategoryId,
    ProductStatus Status,
    bool IsActive
) : InitDTO(Id);
