// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
//     Custom endpoints can be added in a separate partial class file.
// </auto-generated>

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Onward.Base.API.Controllers;
using Onward.Base.Abstractions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.API.Controllers;

/// <summary>
/// Controller for executing flexible queries on Awards
/// Inherits all query logic from BaseQueryController
/// </summary>
[ApiController]
[Route("api/awards/query")]
[AllowAnonymous]
public class AwardsQueryController : BaseQueryController<Award, AwardProjection>
{
    public AwardsQueryController(
        ISearchService<Award, AwardProjection> searchService,
        ILogger<AwardsQueryController> logger)
        : base(searchService, logger)
    {
    }
}
