// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;
using EnergyBrockerage.Prozorro.BL.DataServices;
using Onward.Base.API.Controllers;

namespace EnergyBrockerage.Prozorro.API.Controllers;

/// <summary>
/// Controller for ContractChangeRationaleType operations
/// </summary>
[ApiController]
[Route("api/[controller]")]
[AllowAnonymous]
public partial class ContractChangeRationaleTypesController : DataController<ContractChangeRationaleType, CreateContractChangeRationaleTypeDTO, UpdateContractChangeRationaleTypeDTO, DeleteContractChangeRationaleTypeDTO, InitContractChangeRationaleTypeDTO, ContractChangeRationaleTypeDetailsDTO, ContractChangeRationaleTypeSearchDTO, IContractChangeRationaleTypeDataService, Guid>
{
    public ContractChangeRationaleTypesController(
        IContractChangeRationaleTypeDataService service,
        ILogger<ServiceController> logger
    ) : base(service, logger)
    {
    }
}
