// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.DTO.Order;
using Inventorization.Commerce.BL.DataServices;
using InventorySystem.API.Base.Controllers;
using Inventorization.Base.Abstractions;
using Inventorization.Base.Ownership;

namespace Inventorization.Commerce.API.Controllers;

/// <summary>
/// Controller for Order operations
/// </summary>
[ApiController]
[Route("api/[controller]")]
[Authorize]
public partial class OrdersController : DataController<Order, CreateOrderDTO, UpdateOrderDTO, DeleteOrderDTO, InitOrderDTO, OrderDetailsDTO, OrderSearchDTO, IOrderDataService>
{
    private readonly ICurrentUserService<UserTenantOwnership> _currentUserService;

    public OrdersController(
        IOrderDataService service,
        ICurrentUserService<UserTenantOwnership> currentUserService,
        ILogger<ServiceController> logger
    ) : base(service, logger)
    {
        _currentUserService = currentUserService;
    }
    // _currentUserService is available for developer-authored partial-class overrides.
    // Ownership stamping (creation & update) is handled automatically by DataServiceBase.
}
