// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.OrderItem;
using Inventorization.Commerce.Domain.DataServices;
using InventorySystem.API.Base.Controllers;

namespace Inventorization.Commerce.API.Controllers;

/// <summary>
/// Controller for OrderItem operations
/// </summary>
[ApiController]
[Route("api/[controller]")]
[Authorize]
public partial class OrderItemsController : DataController<OrderItem, CreateOrderItemDTO, UpdateOrderItemDTO, DeleteOrderItemDTO, OrderItemDetailsDTO, OrderItemSearchDTO, IOrderItemDataService>
{
    public OrderItemsController(
        IOrderItemDataService service,
        ILogger<ServiceController> logger
    ) : base(service, logger)
    {
    }
}
