// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-618b8d7c
//     Generated: 2026-02-14 15:54:12 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
//     Custom endpoints can be added in a separate partial class file.
// </auto-generated>

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using InventorySystem.API.Base.Controllers;
using Inventorization.Base.Abstractions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.ADTs;

namespace Inventorization.Commerce.API.Controllers;

/// <summary>
/// Controller for executing flexible queries on Orders
/// Inherits all query logic from BaseQueryController
/// </summary>
[ApiController]
[Route("api/orders/query")]
[AllowAnonymous]
public class OrdersQueryController : BaseQueryController<Order, OrderProjection>
{
    public OrdersQueryController(
        ISearchService<Order, OrderProjection> searchService,
        ILogger<OrdersQueryController> logger)
        : base(searchService, logger)
    {
    }
    
    // Add custom query endpoints here if needed
}
