// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.Product;
using Inventorization.Commerce.Domain.DataServices;
using Inventorization.Base.Controllers;

namespace Inventorization.Commerce.API.Controllers;

/// <summary>
/// Controller for Product operations
/// </summary>
[ApiController]
[Route("api/[controller]")]
[Authorize]
public partial class ProductsController : DataController<Product, CreateProductDTO, UpdateProductDTO, DeleteProductDTO, ProductDetailsDTO, ProductSearchDTO, IProductDataService>
{
    public ProductsController(
        IProductDataService service,
        ILogger<ServiceController> logger
    ) : base(service, logger)
    {
    }
}
