// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.DTO.Product;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.BL.Modifiers;

/// <summary>
/// Modifier for Product entities
/// </summary>
public class ProductModifier : IEntityModifier<Product, UpdateProductDTO>
{
    /// <summary>
    /// Modifies an existing Product entity with data from a DTO
    /// </summary>
    public void Modify(Product entity, UpdateProductDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            name: dto.Name,
            sKU: dto.SKU,
            description: dto.Description,
            price: dto.Price,
            stockQuantity: dto.StockQuantity,
            status: dto.Status,
            isActive: dto.IsActive
        );

    }
}
