// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.Award;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class AwardValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateAwardValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateAwardDTO dto)
    {
        var validator = new CreateAwardValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateAwardValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateAwardDTO dto)
    {
        var validator = new UpdateAwardValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Currency = new string('a', 11)) },
        new object[] { CreateValidCreateDto(dto => dto.BidExternalId = new string('a', 101)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Currency = new string('a', 11)) },
        new object[] { CreateValidUpdateDto(dto => dto.BidExternalId = new string('a', 101)) },
    };

    private static CreateAwardDTO CreateValidCreateDto(Action<CreateAwardDTO>? mutate = null)
    {
        var dto = new CreateAwardDTO
        {
            ExternalId = new string('a', 1),
            Status = AwardStatus.Pending,
            AwardDate = default!,
            Amount = 1m,
            Currency = new string('a', 1),
            Qualified = true,
            PeriodStart = default!,
            PeriodEnd = default!,
            BidExternalId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateAwardDTO CreateValidUpdateDto(Action<UpdateAwardDTO>? mutate = null)
    {
        var dto = new UpdateAwardDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            Status = AwardStatus.Pending,
            AwardDate = default!,
            Amount = 1m,
            Currency = new string('a', 1),
            Qualified = true,
            PeriodStart = default!,
            PeriodEnd = default!,
            BidExternalId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
