// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.Bid;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class BidValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateBidValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateBidDTO dto)
    {
        var validator = new CreateBidValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateBidValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateBidDTO dto)
    {
        var validator = new UpdateBidValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Currency = new string('a', 11)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Currency = new string('a', 11)) },
    };

    private static CreateBidDTO CreateValidCreateDto(Action<CreateBidDTO>? mutate = null)
    {
        var dto = new CreateBidDTO
        {
            ExternalId = new string('a', 1),
            Status = BidStatus.Draft,
            BidDate = default!,
            SubmissionDate = default!,
            Amount = 1m,
            Currency = new string('a', 1),
            ValueAddedTaxIncluded = true,
            InitialAmount = 1m,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateBidDTO CreateValidUpdateDto(Action<UpdateBidDTO>? mutate = null)
    {
        var dto = new UpdateBidDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            Status = BidStatus.Draft,
            BidDate = default!,
            SubmissionDate = default!,
            Amount = 1m,
            Currency = new string('a', 1),
            ValueAddedTaxIncluded = true,
            InitialAmount = 1m,
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
