// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class ContractChangeRationaleTypeValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateContractChangeRationaleTypeValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateContractChangeRationaleTypeDTO dto)
    {
        var validator = new CreateContractChangeRationaleTypeValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateContractChangeRationaleTypeValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateContractChangeRationaleTypeDTO dto)
    {
        var validator = new UpdateContractChangeRationaleTypeValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.Code = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.Code = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.TitleEn = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.TitleUk = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.DescriptionEn = new string('a', 2001)) },
        new object[] { CreateValidCreateDto(dto => dto.DescriptionUk = new string('a', 2001)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Code = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Code = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.TitleEn = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.TitleUk = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.DescriptionEn = new string('a', 2001)) },
        new object[] { CreateValidUpdateDto(dto => dto.DescriptionUk = new string('a', 2001)) },
    };

    private static CreateContractChangeRationaleTypeDTO CreateValidCreateDto(Action<CreateContractChangeRationaleTypeDTO>? mutate = null)
    {
        var dto = new CreateContractChangeRationaleTypeDTO
        {
            Code = new string('a', 1),
            TitleEn = new string('a', 1),
            TitleUk = new string('a', 1),
            DescriptionEn = new string('a', 1),
            DescriptionUk = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateContractChangeRationaleTypeDTO CreateValidUpdateDto(Action<UpdateContractChangeRationaleTypeDTO>? mutate = null)
    {
        var dto = new UpdateContractChangeRationaleTypeDTO
        {
            Id = Guid.NewGuid(),
            Code = new string('a', 1),
            TitleEn = new string('a', 1),
            TitleUk = new string('a', 1),
            DescriptionEn = new string('a', 1),
            DescriptionUk = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
