// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.Organization;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class OrganizationValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateOrganizationValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateOrganizationDTO dto)
    {
        var validator = new CreateOrganizationValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateOrganizationValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateOrganizationDTO dto)
    {
        var validator = new UpdateOrganizationValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.IdentifierScheme = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.IdentifierScheme = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.Name = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.Name = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.NameEn = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.LegalName = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.LegalName = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.LegalNameEn = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.StreetAddress = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.Locality = new string('a', 201)) },
        new object[] { CreateValidCreateDto(dto => dto.Region = new string('a', 201)) },
        new object[] { CreateValidCreateDto(dto => dto.PostalCode = new string('a', 21)) },
        new object[] { CreateValidCreateDto(dto => dto.CountryName = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.ContactName = new string('a', 301)) },
        new object[] { CreateValidCreateDto(dto => dto.ContactEmail = new string('a', 256)) },
        new object[] { CreateValidCreateDto(dto => dto.ContactEmail = "invalid-email") },
        new object[] { CreateValidCreateDto(dto => dto.ContactPhone = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.ContactUrl = new string('a', 501)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.IdentifierScheme = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.IdentifierScheme = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.Name = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Name = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.NameEn = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.LegalName = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.LegalName = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.LegalNameEn = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.StreetAddress = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.Locality = new string('a', 201)) },
        new object[] { CreateValidUpdateDto(dto => dto.Region = new string('a', 201)) },
        new object[] { CreateValidUpdateDto(dto => dto.PostalCode = new string('a', 21)) },
        new object[] { CreateValidUpdateDto(dto => dto.CountryName = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.ContactName = new string('a', 301)) },
        new object[] { CreateValidUpdateDto(dto => dto.ContactEmail = new string('a', 256)) },
        new object[] { CreateValidUpdateDto(dto => dto.ContactEmail = "invalid-email") },
        new object[] { CreateValidUpdateDto(dto => dto.ContactPhone = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.ContactUrl = new string('a', 501)) },
    };

    private static CreateOrganizationDTO CreateValidCreateDto(Action<CreateOrganizationDTO>? mutate = null)
    {
        var dto = new CreateOrganizationDTO
        {
            ExternalId = new string('a', 1),
            IdentifierScheme = new string('a', 1),
            Name = new string('a', 1),
            NameEn = new string('a', 1),
            LegalName = new string('a', 1),
            LegalNameEn = new string('a', 1),
            Kind = OrganizationKind.General,
            Scale = OrganizationScale.Micro,
            StreetAddress = new string('a', 1),
            Locality = new string('a', 1),
            Region = new string('a', 1),
            PostalCode = new string('a', 1),
            CountryName = new string('a', 1),
            ContactName = new string('a', 1),
            ContactEmail = "user@example.com",
            ContactPhone = new string('a', 1),
            ContactUrl = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateOrganizationDTO CreateValidUpdateDto(Action<UpdateOrganizationDTO>? mutate = null)
    {
        var dto = new UpdateOrganizationDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            IdentifierScheme = new string('a', 1),
            Name = new string('a', 1),
            NameEn = new string('a', 1),
            LegalName = new string('a', 1),
            LegalNameEn = new string('a', 1),
            Kind = OrganizationKind.General,
            Scale = OrganizationScale.Micro,
            StreetAddress = new string('a', 1),
            Locality = new string('a', 1),
            Region = new string('a', 1),
            PostalCode = new string('a', 1),
            CountryName = new string('a', 1),
            ContactName = new string('a', 1),
            ContactEmail = "user@example.com",
            ContactPhone = new string('a', 1),
            ContactUrl = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
