// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.RequirementGroup;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class RequirementGroupValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateRequirementGroupValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateRequirementGroupDTO dto)
    {
        var validator = new CreateRequirementGroupValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateRequirementGroupValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateRequirementGroupDTO dto)
    {
        var validator = new UpdateRequirementGroupValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Description = new string('a', 2001)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Description = new string('a', 2001)) },
    };

    private static CreateRequirementGroupDTO CreateValidCreateDto(Action<CreateRequirementGroupDTO>? mutate = null)
    {
        var dto = new CreateRequirementGroupDTO
        {
            ExternalId = new string('a', 1),
            Description = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateRequirementGroupDTO CreateValidUpdateDto(Action<UpdateRequirementGroupDTO>? mutate = null)
    {
        var dto = new UpdateRequirementGroupDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            Description = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
