// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.TenderPlan;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class TenderPlanValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateTenderPlanValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateTenderPlanDTO dto)
    {
        var validator = new CreateTenderPlanValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateTenderPlanValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateTenderPlanDTO dto)
    {
        var validator = new UpdateTenderPlanValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.PlanExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.PlanExternalId = new string('a', 101)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.PlanExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.PlanExternalId = new string('a', 101)) },
    };

    private static CreateTenderPlanDTO CreateValidCreateDto(Action<CreateTenderPlanDTO>? mutate = null)
    {
        var dto = new CreateTenderPlanDTO
        {
            PlanExternalId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateTenderPlanDTO CreateValidUpdateDto(Action<UpdateTenderPlanDTO>? mutate = null)
    {
        var dto = new UpdateTenderPlanDTO
        {
            Id = Guid.NewGuid(),
            PlanExternalId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
