// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.Tender;

namespace EnergyBrockerage.Prozorro.API.Tests.Validators;

public class TenderValidatorTests
{
    [Fact]
    public async Task CreateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new CreateTenderValidator();
        var dto = CreateValidCreateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task CreateValidator_ReturnsErrors_WhenDtoInvalid(CreateTenderDTO dto)
    {
        var validator = new CreateTenderValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateValidator_ReturnsOk_WhenDtoValid()
    {
        var validator = new UpdateTenderValidator();
        var dto = CreateValidUpdateDto();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeTrue();
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateValidator_ReturnsErrors_WhenDtoInvalid(UpdateTenderDTO dto)
    {
        var validator = new UpdateTenderValidator();

        var result = await validator.ValidateAsync(dto);

        result.IsValid.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.TenderNumber = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Title = new string('a', 1001)) },
        new object[] { CreateValidCreateDto(dto => dto.Description = new string('a', 4001)) },
        new object[] { CreateValidCreateDto(dto => dto.Owner = new string('a', 201)) },
        new object[] { CreateValidCreateDto(dto => dto.ProcurementMethod = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.MainProcurementCategory = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Currency = new string('a', 11)) },
        new object[] { CreateValidCreateDto(dto => dto.AgreementId = new string('a', 101)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.TenderNumber = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Title = new string('a', 1001)) },
        new object[] { CreateValidUpdateDto(dto => dto.Description = new string('a', 4001)) },
        new object[] { CreateValidUpdateDto(dto => dto.Owner = new string('a', 201)) },
        new object[] { CreateValidUpdateDto(dto => dto.ProcurementMethod = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.MainProcurementCategory = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Currency = new string('a', 11)) },
        new object[] { CreateValidUpdateDto(dto => dto.AgreementId = new string('a', 101)) },
    };

    private static CreateTenderDTO CreateValidCreateDto(Action<CreateTenderDTO>? mutate = null)
    {
        var dto = new CreateTenderDTO
        {
            ExternalId = new string('a', 1),
            TenderNumber = new string('a', 1),
            Title = new string('a', 1),
            Description = new string('a', 1),
            Owner = new string('a', 1),
            Status = TenderStatus.Draft,
            ProcurementMethodType = ProcurementMethodType.PriceQuotation,
            AwardCriteria = AwardCriteria.LowestCost,
            ProcurementMethod = new string('a', 1),
            MainProcurementCategory = new string('a', 1),
            TotalAmount = 1m,
            Currency = new string('a', 1),
            ValueAddedTaxIncluded = true,
            TenderPeriodStart = default!,
            TenderPeriodEnd = default!,
            AwardPeriodStart = default!,
            AwardPeriodEnd = default!,
            NoticePublicationDate = default!,
            TenderDate = default!,
            AgreementId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateTenderDTO CreateValidUpdateDto(Action<UpdateTenderDTO>? mutate = null)
    {
        var dto = new UpdateTenderDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            TenderNumber = new string('a', 1),
            Title = new string('a', 1),
            Description = new string('a', 1),
            Owner = new string('a', 1),
            Status = TenderStatus.Draft,
            ProcurementMethodType = ProcurementMethodType.PriceQuotation,
            AwardCriteria = AwardCriteria.LowestCost,
            ProcurementMethod = new string('a', 1),
            MainProcurementCategory = new string('a', 1),
            TotalAmount = 1m,
            Currency = new string('a', 1),
            ValueAddedTaxIncluded = true,
            TenderPeriodStart = default!,
            TenderPeriodEnd = default!,
            AwardPeriodStart = default!,
            AwardPeriodEnd = default!,
            NoticePublicationDate = default!,
            TenderDate = default!,
            AgreementId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }
}
