/**
 * DataAccess generator - creates DbContext and UnitOfWork
 */

import { BaseGenerator } from './BaseGenerator';
import { DataModel } from '../models/DataModel';
import * as path from 'path';

export class DataAccessGenerator extends BaseGenerator {
  async generate(model: DataModel): Promise<void> {
    const contextName = model.boundedContext.name;
    const namespace = model.boundedContext.namespace;
    const baseNamespace = this.metadata?.baseNamespace || 'Inventorization';

    const blProjectPath = `${baseNamespace}.${contextName}.BL`;

    await this.generateDbContext(model, blProjectPath, namespace, baseNamespace, contextName);
    await this.generateUnitOfWork(model, blProjectPath, namespace, baseNamespace, contextName);
    // DataModelRelationships now generated by MetadataGenerator in Meta project
  }

  private async generateDbContext(
    model: DataModel,
    blProjectPath: string,
    namespace: string,
    baseNamespace: string,
    contextName: string
  ): Promise<void> {
    const dbContextsDir = path.join(blProjectPath, 'DbContexts');

    const context = {
      baseNamespace,
      namespace,
      contextName,
      entities: model.entities.map((e) => ({
        name: e.name,
        pluralName: this.pluralize(e.name),
        description: e.description || e.name,
      })),
    };

    const filePath = path.join(dbContextsDir, `${contextName}DbContext.cs`);
    await this.writeRenderedTemplate(
      ['bl/db-context/ef-core.generated.cs.hbs', 'db-context.generated.cs.hbs'],
      context,
      filePath,
      true
    );
  }

  private async generateUnitOfWork(
    _model: DataModel,
    blProjectPath: string,
    namespace: string,
    baseNamespace: string,
    contextName: string
  ): Promise<void> {
    const dataAccessDir = path.join(blProjectPath, 'DataAccess');

    const context = {
      baseNamespace,
      namespace,
      contextName,
    };

    const filePath = path.join(dataAccessDir, `${contextName}UnitOfWork.cs`);
    await this.writeRenderedTemplate(
      ['bl/unit-of-work/ef-core.generated.cs.hbs', 'unit-of-work.generated.cs.hbs'],
      context,
      filePath,
      true
    );
  }

  private pluralize(word: string): string {
    // Simple pluralization
    if (word.endsWith('y')) {
      return word.slice(0, -1) + 'ies';
    } else if (word.endsWith('s') || word.endsWith('x') || word.endsWith('ch')) {
      return word + 'es';
    } else {
      return word + 's';
    }
  }
}
