// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Onward.Base.DTOs;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.DTO.Award;

/// <summary>
/// DTO for updating an existing Award
/// </summary>
public class UpdateAwardDTO : UpdateDTO<Guid>
{
    /// <summary>
    /// Prozorro award ID
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ExternalId { get; set; }

    /// <summary>
    /// Award status
    /// </summary>
    public AwardStatus Status { get; set; }

    /// <summary>
    /// Date the award was issued
    /// </summary>
    public string AwardDate { get; set; }

    /// <summary>
    /// Awarded contract value
    /// </summary>
    public decimal? Amount { get; set; }

    /// <summary>
    /// Award currency code
    /// </summary>
    [StringLength(10)]
    public string Currency { get; set; }

    /// <summary>
    /// Whether the award passed qualification check
    /// </summary>
    public bool? Qualified { get; set; }

    /// <summary>
    /// Start of the award acceptance period
    /// </summary>
    public string PeriodStart { get; set; }

    /// <summary>
    /// End of the award acceptance period
    /// </summary>
    public string PeriodEnd { get; set; }

    /// <summary>
    /// External ID of the winning bid (from Prozorro)
    /// </summary>
    [StringLength(100)]
    public string BidExternalId { get; set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid TenderId { get; set; }

    /// <summary>
    /// Organization that received this award
    /// </summary>
    public Guid SupplierId { get; set; }

}
