// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Onward.Base.DTOs;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.DTO.Organization;

/// <summary>
/// DTO for updating an existing Organization
/// </summary>
public class UpdateOrganizationDTO : UpdateDTO<Guid>
{
    /// <summary>
    /// Prozorro organization identifier value (e.g. EDRPOU code)
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ExternalId { get; set; }

    /// <summary>
    /// Identifier scheme (e.g. UA-EDR)
    /// </summary>
    [Required]
    [StringLength(50)]
    public string IdentifierScheme { get; set; }

    /// <summary>
    /// Organization name in Ukrainian
    /// </summary>
    [Required]
    [StringLength(500)]
    public string Name { get; set; }

    /// <summary>
    /// Organization name in English
    /// </summary>
    [StringLength(500)]
    public string NameEn { get; set; }

    /// <summary>
    /// Legal registered name
    /// </summary>
    [Required]
    [StringLength(500)]
    public string LegalName { get; set; }

    /// <summary>
    /// Legal name in English
    /// </summary>
    [StringLength(500)]
    public string LegalNameEn { get; set; }

    /// <summary>
    /// Procuring entity kind classification
    /// </summary>
    public OrganizationKind Kind { get; set; }

    /// <summary>
    /// Business size classification
    /// </summary>
    public OrganizationScale Scale { get; set; }

    /// <summary>
    /// Street address
    /// </summary>
    [StringLength(500)]
    public string StreetAddress { get; set; }

    /// <summary>
    /// City or locality
    /// </summary>
    [StringLength(200)]
    public string Locality { get; set; }

    /// <summary>
    /// Region or oblast
    /// </summary>
    [StringLength(200)]
    public string Region { get; set; }

    /// <summary>
    /// Postal code
    /// </summary>
    [StringLength(20)]
    public string PostalCode { get; set; }

    /// <summary>
    /// Country name
    /// </summary>
    [StringLength(100)]
    public string CountryName { get; set; }

    /// <summary>
    /// Contact person full name
    /// </summary>
    [StringLength(300)]
    public string ContactName { get; set; }

    /// <summary>
    /// Contact email address
    /// </summary>
    [StringLength(255)]
    public string ContactEmail { get; set; }

    /// <summary>
    /// Contact telephone number
    /// </summary>
    [StringLength(100)]
    public string ContactPhone { get; set; }

    /// <summary>
    /// Contact or official website URL
    /// </summary>
    [StringLength(500)]
    public string ContactUrl { get; set; }

}
