// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Award;
using Onward.Base.Abstractions;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Modifiers;

/// <summary>
/// Modifier for Award entities
/// </summary>
public class AwardModifier : IEntityModifier<Award, UpdateAwardDTO>
{
    /// <summary>
    /// Modifies an existing Award entity with data from a DTO
    /// </summary>
    public void Modify(Award entity, UpdateAwardDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            externalId: dto.ExternalId,
            status: dto.Status,
            awardDate: dto.AwardDate != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.AwardDate)) : null,
            amount: dto.Amount,
            currency: dto.Currency,
            qualified: dto.Qualified,
            periodStart: dto.PeriodStart != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.PeriodStart)) : null,
            periodEnd: dto.PeriodEnd != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.PeriodEnd)) : null,
            bidExternalId: dto.BidExternalId
        );

    }
}
