// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Modifiers;

/// <summary>
/// Modifier for ContractChangeRationaleType entities
/// </summary>
public class ContractChangeRationaleTypeModifier : IEntityModifier<ContractChangeRationaleType, UpdateContractChangeRationaleTypeDTO>
{
    /// <summary>
    /// Modifies an existing ContractChangeRationaleType entity with data from a DTO
    /// </summary>
    public void Modify(ContractChangeRationaleType entity, UpdateContractChangeRationaleTypeDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            code: dto.Code,
            titleEn: dto.TitleEn,
            titleUk: dto.TitleUk,
            descriptionEn: dto.DescriptionEn,
            descriptionUk: dto.DescriptionUk
        );

    }
}
