// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Criterion;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Modifiers;

/// <summary>
/// Modifier for Criterion entities
/// </summary>
public class CriterionModifier : IEntityModifier<Criterion, UpdateCriterionDTO>
{
    /// <summary>
    /// Modifies an existing Criterion entity with data from a DTO
    /// </summary>
    public void Modify(Criterion entity, UpdateCriterionDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            externalId: dto.ExternalId,
            title: dto.Title,
            description: dto.Description,
            source: dto.Source,
            relatesTo: dto.RelatesTo,
            relatedItem: dto.RelatedItem,
            classificationScheme: dto.ClassificationScheme,
            classificationId: dto.ClassificationId
        );

    }
}
