// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Document;
using Onward.Base.Abstractions;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Modifiers;

/// <summary>
/// Modifier for Document entities
/// </summary>
public class DocumentModifier : IEntityModifier<Document, UpdateDocumentDTO>
{
    /// <summary>
    /// Modifies an existing Document entity with data from a DTO
    /// </summary>
    public void Modify(Document entity, UpdateDocumentDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            externalId: dto.ExternalId,
            title: dto.Title,
            format: dto.Format,
            url: dto.Url,
            hash: dto.Hash,
            documentType: dto.DocumentType,
            confidentiality: dto.Confidentiality,
            documentOf: dto.DocumentOf,
            relatedItem: dto.RelatedItem,
            author: dto.Author,
            language: dto.Language,
            datePublished: dto.DatePublished != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.DatePublished)) : null,
            dateModified: dto.DateModified != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.DateModified)) : null
        );

    }
}
