// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Milestone;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Modifiers;

/// <summary>
/// Modifier for Milestone entities
/// </summary>
public class MilestoneModifier : IEntityModifier<Milestone, UpdateMilestoneDTO>
{
    /// <summary>
    /// Modifies an existing Milestone entity with data from a DTO
    /// </summary>
    public void Modify(Milestone entity, UpdateMilestoneDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            externalId: dto.ExternalId,
            title: dto.Title,
            description: dto.Description,
            type: dto.Type,
            code: dto.Code,
            percentage: dto.Percentage,
            durationDays: dto.DurationDays,
            durationType: dto.DurationType,
            sequenceNumber: dto.SequenceNumber
        );

    }
}
