// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.TenderPlan;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Modifiers;

/// <summary>
/// Modifier for TenderPlan entities
/// </summary>
public class TenderPlanModifier : IEntityModifier<TenderPlan, UpdateTenderPlanDTO>
{
    /// <summary>
    /// Modifies an existing TenderPlan entity with data from a DTO
    /// </summary>
    public void Modify(TenderPlan entity, UpdateTenderPlanDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            planExternalId: dto.PlanExternalId
        );

    }
}
