// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Document;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.SearchProviders;

/// <summary>
/// Search query provider for Document
/// </summary>
public class DocumentSearchProvider : ISearchQueryProvider<Document, DocumentSearchDTO>
{
    /// <summary>
    /// Builds search expression from search DTO
    /// </summary>
    public Expression<Func<Document, bool>> GetSearchExpression(DocumentSearchDTO searchDto)
    {
        if (searchDto == null)
            throw new ArgumentNullException(nameof(searchDto));

        return entity =>
            (searchDto.ExternalId == null || entity.ExternalId.Contains(searchDto.ExternalId)) &&
                        (searchDto.Title == null || entity.Title.Contains(searchDto.Title)) &&
                        (searchDto.Format == null || entity.Format.Contains(searchDto.Format)) &&
                        (searchDto.Url == null || entity.Url.Contains(searchDto.Url)) &&
                        (searchDto.Hash == null || entity.Hash.Contains(searchDto.Hash)) &&
                        (searchDto.DocumentType == null || entity.DocumentType.Contains(searchDto.DocumentType)) &&
                        (searchDto.Confidentiality == null || entity.Confidentiality.Contains(searchDto.Confidentiality)) &&
                        (searchDto.DocumentOf == null || entity.DocumentOf.Contains(searchDto.DocumentOf)) &&
                        (searchDto.RelatedItem == null || entity.RelatedItem.Contains(searchDto.RelatedItem)) &&
                        (searchDto.Author == null || entity.Author.Contains(searchDto.Author)) &&
                        (searchDto.Language == null || entity.Language.Contains(searchDto.Language))
            ;
    }
}
