// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Requirement;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.SearchProviders;

/// <summary>
/// Search query provider for Requirement
/// </summary>
public class RequirementSearchProvider : ISearchQueryProvider<Requirement, RequirementSearchDTO>
{
    /// <summary>
    /// Builds search expression from search DTO
    /// </summary>
    public Expression<Func<Requirement, bool>> GetSearchExpression(RequirementSearchDTO searchDto)
    {
        if (searchDto == null)
            throw new ArgumentNullException(nameof(searchDto));

        return entity =>
            (searchDto.ExternalId == null || entity.ExternalId.Contains(searchDto.ExternalId)) &&
                        (searchDto.Title == null || entity.Title.Contains(searchDto.Title)) &&
                        (searchDto.DataType == null || entity.DataType.Contains(searchDto.DataType)) &&
                        (searchDto.Status == null || entity.Status.Contains(searchDto.Status)) &&
                        (searchDto.ExpectedValue == null || entity.ExpectedValue.Contains(searchDto.ExpectedValue)) &&
                        (searchDto.ExpectedValuesJson == null || entity.ExpectedValuesJson.Contains(searchDto.ExpectedValuesJson))
            ;
    }
}
