// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Inventorization.Base.DataAccess;
using Inventorization.Base.Abstractions;
using Inventorization.Base.Ownership;
using Inventorization.Commerce.BL.Entities;

namespace Inventorization.Commerce.BL.DataAccess;

/// <summary>
/// Converts SearchQuery ADT to IQueryable for Order entity.
/// Ownership-aware: extends BaseQueryBuilder&lt;Order, UserTenantOwnership&gt;.
/// Appends an ownership predicate derived from ICurrentIdentityContext&lt;UserTenantOwnership&gt;.
/// Uses default ParameterName (first letter of entity name in lowercase).
/// </summary>
public class OrderQueryBuilder : BaseQueryBuilder<Order, UserTenantOwnership>
{
    public OrderQueryBuilder(ICurrentIdentityContext<UserTenantOwnership> identityContext)
        : base(identityContext)
    {
    }

    // Override BuildOwnershipPredicate(UserTenantOwnership ownership) to customise visibility rules.
    // Default: exact-match on the Ownership VO (all fields must match).
}
