// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using EnergyBrockerage.Prozorro.DI;
using EnergyBrockerage.Prozorro.BL.DataServices;
using EnergyBrockerage.Prozorro.BL.Services;

namespace EnergyBrockerage.Prozorro.API.Tests.Instantiation;

public class ProzorroInstantiationTests
{
    [Fact]
    public void ServiceProvider_Resolves_HighLevelServices()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddProzorroServices(options =>
            options.UseInMemoryDatabase("Prozorro_Tests"));

        var provider = services.BuildServiceProvider();

        provider.GetRequiredService<IOrganizationDataService>();
        provider.GetRequiredService<OrganizationSearchService>();
        provider.GetRequiredService<ITenderDataService>();
        provider.GetRequiredService<TenderSearchService>();
        provider.GetRequiredService<ITenderItemDataService>();
        provider.GetRequiredService<TenderItemSearchService>();
        provider.GetRequiredService<IBidDataService>();
        provider.GetRequiredService<BidSearchService>();
        provider.GetRequiredService<IBidItemDataService>();
        provider.GetRequiredService<BidItemSearchService>();
        provider.GetRequiredService<IAwardDataService>();
        provider.GetRequiredService<AwardSearchService>();
        provider.GetRequiredService<IContractChangeRationaleTypeDataService>();
        provider.GetRequiredService<ContractChangeRationaleTypeSearchService>();
        provider.GetRequiredService<IContractDataService>();
        provider.GetRequiredService<ContractSearchService>();
        provider.GetRequiredService<ITenderPlanDataService>();
        provider.GetRequiredService<TenderPlanSearchService>();
        provider.GetRequiredService<IDocumentDataService>();
        provider.GetRequiredService<DocumentSearchService>();
        provider.GetRequiredService<IMilestoneDataService>();
        provider.GetRequiredService<MilestoneSearchService>();
        provider.GetRequiredService<ICriterionDataService>();
        provider.GetRequiredService<CriterionSearchService>();
        provider.GetRequiredService<IRequirementGroupDataService>();
        provider.GetRequiredService<RequirementGroupSearchService>();
        provider.GetRequiredService<IRequirementDataService>();
        provider.GetRequiredService<RequirementSearchService>();
    }
}
