// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.DTO.ADTs;

/// <summary>
/// Projection DTO for BidItem entity.
/// All properties are nullable to support selective projection.
/// </summary>
public class BidItemProjection
{
    [JsonPropertyName("id")]
    public Guid? Id { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTime? CreatedAt { get; set; }

    [JsonPropertyName("externalId")]
    public string? ExternalId { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("quantity")]
    public decimal? Quantity { get; set; }

    [JsonPropertyName("unitName")]
    public string? UnitName { get; set; }

    [JsonPropertyName("unitCode")]
    public string? UnitCode { get; set; }

    [JsonPropertyName("unitPrice")]
    public decimal? UnitPrice { get; set; }

    [JsonPropertyName("unitPriceCurrency")]
    public string? UnitPriceCurrency { get; set; }

    [JsonPropertyName("bid")]
    public BidProjection? Bid { get; set; }

}
