// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace EnergyBrockerage.Prozorro.BL.Constants;

/// <summary>
/// Searchable field names for Criterion entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class CriterionSearchFields
{
    // Direct properties
    public const string ExternalId = "ExternalId";
    public const string Title = "Title";
    public const string Description = "Description";
    public const string Source = "Source";
    public const string RelatesTo = "RelatesTo";
    public const string RelatedItem = "RelatedItem";
    public const string ClassificationScheme = "ClassificationScheme";
    public const string ClassificationId = "ClassificationId";
    public const string TenderId = "TenderId";


    /// <summary>
    /// All valid search fields for Criterion.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        ExternalId,
        Title,
        Description,
        Source,
        RelatesTo,
        RelatedItem,
        ClassificationScheme,
        ClassificationId,
        TenderId,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
