// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;

namespace EnergyBrockerage.Prozorro.DTO.ADTs;

/// <summary>
/// Projection DTO for Milestone entity.
/// All properties are nullable to support selective projection.
/// </summary>
public class MilestoneProjection
{
    [JsonPropertyName("id")]
    public Guid? Id { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTime? CreatedAt { get; set; }

    [JsonPropertyName("externalId")]
    public string? ExternalId { get; set; }

    [JsonPropertyName("title")]
    public string? Title { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("type")]
    public string? Type { get; set; }

    [JsonPropertyName("code")]
    public string? Code { get; set; }

    [JsonPropertyName("percentage")]
    public decimal? Percentage { get; set; }

    [JsonPropertyName("durationDays")]
    public int? DurationDays { get; set; }

    [JsonPropertyName("durationType")]
    public string? DurationType { get; set; }

    [JsonPropertyName("sequenceNumber")]
    public int? SequenceNumber { get; set; }

    [JsonPropertyName("tender")]
    public TenderProjection? Tender { get; set; }

}
