// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace EnergyBrockerage.Prozorro.BL.Constants;

/// <summary>
/// Searchable field names for Milestone entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class MilestoneSearchFields
{
    // Direct properties
    public const string ExternalId = "ExternalId";
    public const string Title = "Title";
    public const string Description = "Description";
    public const string Type = "Type";
    public const string Code = "Code";
    public const string Percentage = "Percentage";
    public const string DurationDays = "DurationDays";
    public const string DurationType = "DurationType";
    public const string SequenceNumber = "SequenceNumber";
    public const string TenderId = "TenderId";


    /// <summary>
    /// All valid search fields for Milestone.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        ExternalId,
        Title,
        Description,
        Type,
        Code,
        Percentage,
        DurationDays,
        DurationType,
        SequenceNumber,
        TenderId,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
