// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

namespace EnergyBrockerage.Prozorro.BL.Constants;

/// <summary>
/// Searchable field names for Requirement entity.
/// Includes direct properties and nested relationship paths.
/// </summary>
public static class RequirementSearchFields
{
    // Direct properties
    public const string ExternalId = "ExternalId";
    public const string Title = "Title";
    public const string DataType = "DataType";
    public const string Status = "Status";
    public const string ExpectedValue = "ExpectedValue";
    public const string ExpectedValuesJson = "ExpectedValuesJson";
    public const string ExpectedMinItems = "ExpectedMinItems";
    public const string ExpectedMaxItems = "ExpectedMaxItems";
    public const string DatePublished = "DatePublished";
    public const string RequirementGroupId = "RequirementGroupId";


    /// <summary>
    /// All valid search fields for Requirement.
    /// </summary>
    public static readonly HashSet<string> AllFields = new(StringComparer.OrdinalIgnoreCase)
    {
        ExternalId,
        Title,
        DataType,
        Status,
        ExpectedValue,
        ExpectedValuesJson,
        ExpectedMinItems,
        ExpectedMaxItems,
        DatePublished,
        RequirementGroupId,
    };

    /// <summary>
    /// Validates if a field name is searchable.
    /// </summary>
    public static bool IsValidField(string fieldName)
    {
        return AllFields.Contains(fieldName);
    }
}
