// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

#nullable enable

using System.Text.Json.Serialization;
using EnergyBrockerage.Prozorro.Common.Enums;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.DTO.ADTs;

/// <summary>
/// Projection DTO for Tender entity.
/// All properties are nullable to support selective projection.
/// </summary>
public class TenderProjection
{
    [JsonPropertyName("id")]
    public Guid? Id { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTime? CreatedAt { get; set; }

    [JsonPropertyName("updatedAt")]
    public DateTime? UpdatedAt { get; set; }

    [JsonPropertyName("externalId")]
    public string? ExternalId { get; set; }

    [JsonPropertyName("tenderNumber")]
    public string? TenderNumber { get; set; }

    [JsonPropertyName("title")]
    public string? Title { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("owner")]
    public string? Owner { get; set; }

    [JsonPropertyName("status")]
    public TenderStatus? Status { get; set; }

    [JsonPropertyName("procurementMethodType")]
    public ProcurementMethodType? ProcurementMethodType { get; set; }

    [JsonPropertyName("awardCriteria")]
    public AwardCriteria? AwardCriteria { get; set; }

    [JsonPropertyName("procurementMethod")]
    public string? ProcurementMethod { get; set; }

    [JsonPropertyName("mainProcurementCategory")]
    public string? MainProcurementCategory { get; set; }

    [JsonPropertyName("totalAmount")]
    public decimal? TotalAmount { get; set; }

    [JsonPropertyName("currency")]
    public string? Currency { get; set; }

    [JsonPropertyName("valueAddedTaxIncluded")]
    public bool? ValueAddedTaxIncluded { get; set; }

    [JsonPropertyName("tenderPeriodStart")]
    public DateTimeWithOffset? TenderPeriodStart { get; set; }

    [JsonPropertyName("tenderPeriodEnd")]
    public DateTimeWithOffset? TenderPeriodEnd { get; set; }

    [JsonPropertyName("awardPeriodStart")]
    public DateTimeWithOffset? AwardPeriodStart { get; set; }

    [JsonPropertyName("awardPeriodEnd")]
    public DateTimeWithOffset? AwardPeriodEnd { get; set; }

    [JsonPropertyName("noticePublicationDate")]
    public DateTimeWithOffset? NoticePublicationDate { get; set; }

    [JsonPropertyName("tenderDate")]
    public DateTimeWithOffset? TenderDate { get; set; }

    [JsonPropertyName("agreementId")]
    public string? AgreementId { get; set; }

    [JsonPropertyName("procuringEntity")]
    public OrganizationProjection? ProcuringEntity { get; set; }

}
