// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.Address;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.Domain.Modifiers;

/// <summary>
/// Modifier for Address entities
/// </summary>
public class AddressModifier : IEntityModifier<Address, UpdateAddressDTO>
{
    /// <summary>
    /// Modifies an existing Address entity with data from a DTO
    /// </summary>
    public void Modify(Address entity, UpdateAddressDTO dto)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        if (dto == null)
            throw new ArgumentNullException(nameof(dto));

        entity.Update(
            addressType: dto.AddressType,
            street: dto.Street,
            city: dto.City,
            state: dto.State,
            postalCode: dto.PostalCode,
            country: dto.Country,
            isDefault: dto.IsDefault
        );

    }
}
