// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.Category;
using Inventorization.Base.Services;
using Inventorization.Base.DataAccess;
using Inventorization.Base.Abstractions;
using Microsoft.Extensions.Logging;

namespace Inventorization.Commerce.Domain.DataServices;

/// <summary>
/// Data service interface for Category
/// </summary>
public interface ICategoryDataService : IDataService<Category, CreateCategoryDTO, UpdateCategoryDTO, DeleteCategoryDTO, InitCategoryDTO, CategoryDetailsDTO, CategorySearchDTO>
{
}

/// <summary>
/// Data service implementation for Category
/// </summary>
public class CategoryDataService : DataServiceBase<Category, CreateCategoryDTO, UpdateCategoryDTO, DeleteCategoryDTO, InitCategoryDTO, CategoryDetailsDTO, CategorySearchDTO>, ICategoryDataService
{
    public CategoryDataService(
        Inventorization.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<Category> repository,
        IServiceProvider serviceProvider,
        ILogger<CategoryDataService> logger)
        : base(unitOfWork, repository, serviceProvider, logger)
    {
    }
}
