// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.Customer;
using Inventorization.Base.Services;
using Inventorization.Base.DataAccess;
using Inventorization.Base.Abstractions;
using Microsoft.Extensions.Logging;

namespace Inventorization.Commerce.Domain.DataServices;

/// <summary>
/// Data service interface for Customer
/// </summary>
public interface ICustomerDataService : IDataService<Customer, CreateCustomerDTO, UpdateCustomerDTO, DeleteCustomerDTO, InitCustomerDTO, CustomerDetailsDTO, CustomerSearchDTO>
{
}

/// <summary>
/// Data service implementation for Customer
/// </summary>
public class CustomerDataService : DataServiceBase<Customer, CreateCustomerDTO, UpdateCustomerDTO, DeleteCustomerDTO, InitCustomerDTO, CustomerDetailsDTO, CustomerSearchDTO>, ICustomerDataService
{
    public CustomerDataService(
        Inventorization.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<Customer> repository,
        IServiceProvider serviceProvider,
        ILogger<CustomerDataService> logger)
        : base(unitOfWork, repository, serviceProvider, logger)
    {
    }
}
