// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Services;
using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.BL.DbContexts;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.API.Tests.Services;

public class ContractSearchServiceTests
{
    [Fact]
    public async Task ExecuteSearchAsync_ReturnsFailure_WhenQueryInvalid()
    {
        var repository = new Mock<IRepository<Contract>>();
        var queryBuilder = new Mock<IQueryBuilder<Contract>>();
        var projectionMapper = new Mock<IProjectionMapper<Contract, ContractProjection>>();
        var expressionBuilder = new ProjectionExpressionBuilder();
        var validator = new ContractSearchQueryValidator();
        var logger = new Mock<ILogger<ContractSearchService>>();

        var service = new ContractSearchService(
            repository.Object,
            queryBuilder.Object,
            projectionMapper.Object,
            expressionBuilder,
            validator,
            logger.Object);

        var invalidQuery = new SearchQuery(pagination: new PageRequest(0, 10));

        var result = await service.ExecuteSearchAsync(invalidQuery);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task ExecuteSearchAsync_ReturnsSuccess_WhenQueryValid()
    {
        var options = new DbContextOptionsBuilder<ProzorroDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        using var context = new ProzorroDbContext(options);

        var entity = CreateEntity();
        context.Set<Contract>().Add(entity);
        context.SaveChanges();

        var queryable = context.Set<Contract>();
        var repository = new Mock<IRepository<Contract>>();
        var queryBuilder = new Mock<IQueryBuilder<Contract>>();
        var projectionMapper = new Mock<IProjectionMapper<Contract, ContractProjection>>();
        var expressionBuilder = new ProjectionExpressionBuilder();
        var validator = new ContractSearchQueryValidator();
        var logger = new Mock<ILogger<ContractSearchService>>();

        repository.Setup(r => r.GetQueryable()).Returns(queryable);
        queryBuilder.Setup(q => q.BuildQuery(queryable, It.IsAny<SearchQuery>())).Returns(queryable);

        Expression<Func<Contract, ContractProjection>> projection = entity => new ContractProjection
        {
            Id = entity.Id
        };
        projectionMapper.Setup(m => m.GetProjectionExpression(It.IsAny<ProjectionRequest?>())).Returns(projection);

        var service = new ContractSearchService(
            repository.Object,
            queryBuilder.Object,
            projectionMapper.Object,
            expressionBuilder,
            validator,
            logger.Object);

        var query = new SearchQuery(pagination: new PageRequest(1, 10));

        var result = await service.ExecuteSearchAsync(query);

        result.IsSuccess.Should().BeTrue();
        result.Data.Should().NotBeNull();
        result.Data!.Items.Should().HaveCount(1);
    }

    private static Contract CreateEntity()
    {
        return new Contract(
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            ContractStatus.Pending,
            default!,
            1m,
            new string('a', 1),
            new string('a', 1),
            Guid.NewGuid()
        );
    }

}
