// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Services;
using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.BL.DbContexts;
using EnergyBrockerage.Prozorro.DTO.ADTs;

namespace EnergyBrockerage.Prozorro.API.Tests.Services;

public class OrganizationSearchServiceTests
{
    [Fact]
    public async Task ExecuteSearchAsync_ReturnsFailure_WhenQueryInvalid()
    {
        var repository = new Mock<IRepository<Organization>>();
        var queryBuilder = new Mock<IQueryBuilder<Organization>>();
        var projectionMapper = new Mock<IProjectionMapper<Organization, OrganizationProjection>>();
        var expressionBuilder = new ProjectionExpressionBuilder();
        var validator = new OrganizationSearchQueryValidator();
        var logger = new Mock<ILogger<OrganizationSearchService>>();

        var service = new OrganizationSearchService(
            repository.Object,
            queryBuilder.Object,
            projectionMapper.Object,
            expressionBuilder,
            validator,
            logger.Object);

        var invalidQuery = new SearchQuery(pagination: new PageRequest(0, 10));

        var result = await service.ExecuteSearchAsync(invalidQuery);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task ExecuteSearchAsync_ReturnsSuccess_WhenQueryValid()
    {
        var options = new DbContextOptionsBuilder<ProzorroDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        using var context = new ProzorroDbContext(options);

        var entity = CreateEntity();
        context.Set<Organization>().Add(entity);
        context.SaveChanges();

        var queryable = context.Set<Organization>();
        var repository = new Mock<IRepository<Organization>>();
        var queryBuilder = new Mock<IQueryBuilder<Organization>>();
        var projectionMapper = new Mock<IProjectionMapper<Organization, OrganizationProjection>>();
        var expressionBuilder = new ProjectionExpressionBuilder();
        var validator = new OrganizationSearchQueryValidator();
        var logger = new Mock<ILogger<OrganizationSearchService>>();

        repository.Setup(r => r.GetQueryable()).Returns(queryable);
        queryBuilder.Setup(q => q.BuildQuery(queryable, It.IsAny<SearchQuery>())).Returns(queryable);

        Expression<Func<Organization, OrganizationProjection>> projection = entity => new OrganizationProjection
        {
            Id = entity.Id
        };
        projectionMapper.Setup(m => m.GetProjectionExpression(It.IsAny<ProjectionRequest?>())).Returns(projection);

        var service = new OrganizationSearchService(
            repository.Object,
            queryBuilder.Object,
            projectionMapper.Object,
            expressionBuilder,
            validator,
            logger.Object);

        var query = new SearchQuery(pagination: new PageRequest(1, 10));

        var result = await service.ExecuteSearchAsync(query);

        result.IsSuccess.Should().BeTrue();
        result.Data.Should().NotBeNull();
        result.Data!.Items.Should().HaveCount(1);
    }

    private static Organization CreateEntity()
    {
        return new Organization(
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            OrganizationKind.General,
            OrganizationScale.Micro,
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            "user@example.com",
            new string('a', 1),
            new string('a', 1)
        );
    }

}
