// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.DataServices;
using EnergyBrockerage.Prozorro.BL.Creators;
using EnergyBrockerage.Prozorro.BL.Modifiers;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.BL.SearchProviders;
using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.RequirementGroup;

namespace EnergyBrockerage.Prozorro.API.Tests.Services;

public class RequirementGroupDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<RequirementGroup, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementGroupDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<RequirementGroup>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new RequirementGroupDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<RequirementGroup>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateRequirementGroupDTO dto)
    {
        var repository = new Mock<IRepository<RequirementGroup, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementGroupDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementGroupDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<RequirementGroup>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<RequirementGroup, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementGroupDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementGroupDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<RequirementGroup, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementGroupDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<RequirementGroup>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new RequirementGroupDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<RequirementGroup>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateRequirementGroupDTO dto)
    {
        var repository = new Mock<IRepository<RequirementGroup, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementGroupDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementGroupDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<RequirementGroup>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<RequirementGroup, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementGroupDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementGroupDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Description = new string('a', 2001)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Description = new string('a', 2001)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateRequirementGroupDTO>, CreateRequirementGroupValidator>();
        services.AddScoped<IValidator<UpdateRequirementGroupDTO>, UpdateRequirementGroupValidator>();
        services.AddScoped<IEntityCreator<RequirementGroup, CreateRequirementGroupDTO>, RequirementGroupCreator>();
        services.AddScoped<IEntityModifier<RequirementGroup, UpdateRequirementGroupDTO>, RequirementGroupModifier>();
        services.AddScoped<IMapper<RequirementGroup, RequirementGroupDetailsDTO>, RequirementGroupMapper>();
        services.AddScoped<ISearchQueryProvider<RequirementGroup, RequirementGroupSearchDTO>, RequirementGroupSearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateRequirementGroupDTO CreateValidCreateDto(Action<CreateRequirementGroupDTO>? mutate = null)
    {
        var dto = new CreateRequirementGroupDTO
        {
            ExternalId = new string('a', 1),
            Description = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateRequirementGroupDTO CreateValidUpdateDto(Action<UpdateRequirementGroupDTO>? mutate = null)
    {
        var dto = new UpdateRequirementGroupDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            Description = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static RequirementGroup CreateEntity()
    {
        return new RequirementGroup(
            new string('a', 1),
            new string('a', 1),
            Guid.NewGuid()
        );
    }
}
