// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.DataServices;
using EnergyBrockerage.Prozorro.BL.Creators;
using EnergyBrockerage.Prozorro.BL.Modifiers;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.BL.SearchProviders;
using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.Requirement;

namespace EnergyBrockerage.Prozorro.API.Tests.Services;

public class RequirementDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<Requirement, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<Requirement>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new RequirementDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<Requirement>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateRequirementDTO dto)
    {
        var repository = new Mock<IRepository<Requirement, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<Requirement>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<Requirement, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<Requirement, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<Requirement>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new RequirementDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<Requirement>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateRequirementDTO dto)
    {
        var repository = new Mock<IRepository<Requirement, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<Requirement>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<Requirement, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<RequirementDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new RequirementDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Title = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.DataType = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.Status = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.ExpectedValue = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.ExpectedValuesJson = new string('a', 4001)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Title = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.DataType = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.Status = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.ExpectedValue = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.ExpectedValuesJson = new string('a', 4001)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateRequirementDTO>, CreateRequirementValidator>();
        services.AddScoped<IValidator<UpdateRequirementDTO>, UpdateRequirementValidator>();
        services.AddScoped<IEntityCreator<Requirement, CreateRequirementDTO>, RequirementCreator>();
        services.AddScoped<IEntityModifier<Requirement, UpdateRequirementDTO>, RequirementModifier>();
        services.AddScoped<IMapper<Requirement, RequirementDetailsDTO>, RequirementMapper>();
        services.AddScoped<ISearchQueryProvider<Requirement, RequirementSearchDTO>, RequirementSearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateRequirementDTO CreateValidCreateDto(Action<CreateRequirementDTO>? mutate = null)
    {
        var dto = new CreateRequirementDTO
        {
            ExternalId = new string('a', 1),
            Title = new string('a', 1),
            DataType = new string('a', 1),
            Status = new string('a', 1),
            ExpectedValue = new string('a', 1),
            ExpectedValuesJson = new string('a', 1),
            ExpectedMinItems = 1,
            ExpectedMaxItems = 1,
            DatePublished = default!,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateRequirementDTO CreateValidUpdateDto(Action<UpdateRequirementDTO>? mutate = null)
    {
        var dto = new UpdateRequirementDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            Title = new string('a', 1),
            DataType = new string('a', 1),
            Status = new string('a', 1),
            ExpectedValue = new string('a', 1),
            ExpectedValuesJson = new string('a', 1),
            ExpectedMinItems = 1,
            ExpectedMaxItems = 1,
            DatePublished = default!,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static Requirement CreateEntity()
    {
        return new Requirement(
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            1,
            1,
            default!,
            Guid.NewGuid()
        );
    }
}
