// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.DataServices;
using EnergyBrockerage.Prozorro.BL.Creators;
using EnergyBrockerage.Prozorro.BL.Modifiers;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.BL.SearchProviders;
using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.TenderItem;

namespace EnergyBrockerage.Prozorro.API.Tests.Services;

public class TenderItemDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<TenderItem, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<TenderItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new TenderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<TenderItem>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateTenderItemDTO dto)
    {
        var repository = new Mock<IRepository<TenderItem, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<TenderItem>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<TenderItem, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<TenderItem, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<TenderItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new TenderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<TenderItem>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateTenderItemDTO dto)
    {
        var repository = new Mock<IRepository<TenderItem, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<TenderItem>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<TenderItem, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Description = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.Description = new string('a', 2001)) },
        new object[] { CreateValidCreateDto(dto => dto.UnitName = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.UnitCode = new string('a', 21)) },
        new object[] { CreateValidCreateDto(dto => dto.ClassificationId = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.ClassificationScheme = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.ClassificationDescription = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.DeliveryStreetAddress = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.DeliveryLocality = new string('a', 201)) },
        new object[] { CreateValidCreateDto(dto => dto.DeliveryRegion = new string('a', 201)) },
        new object[] { CreateValidCreateDto(dto => dto.DeliveryCountry = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Profile = new string('a', 501)) },
        new object[] { CreateValidCreateDto(dto => dto.Category = new string('a', 201)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.ExternalId = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Description = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Description = new string('a', 2001)) },
        new object[] { CreateValidUpdateDto(dto => dto.UnitName = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.UnitCode = new string('a', 21)) },
        new object[] { CreateValidUpdateDto(dto => dto.ClassificationId = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.ClassificationScheme = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.ClassificationDescription = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.DeliveryStreetAddress = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.DeliveryLocality = new string('a', 201)) },
        new object[] { CreateValidUpdateDto(dto => dto.DeliveryRegion = new string('a', 201)) },
        new object[] { CreateValidUpdateDto(dto => dto.DeliveryCountry = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Profile = new string('a', 501)) },
        new object[] { CreateValidUpdateDto(dto => dto.Category = new string('a', 201)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateTenderItemDTO>, CreateTenderItemValidator>();
        services.AddScoped<IValidator<UpdateTenderItemDTO>, UpdateTenderItemValidator>();
        services.AddScoped<IEntityCreator<TenderItem, CreateTenderItemDTO>, TenderItemCreator>();
        services.AddScoped<IEntityModifier<TenderItem, UpdateTenderItemDTO>, TenderItemModifier>();
        services.AddScoped<IMapper<TenderItem, TenderItemDetailsDTO>, TenderItemMapper>();
        services.AddScoped<ISearchQueryProvider<TenderItem, TenderItemSearchDTO>, TenderItemSearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateTenderItemDTO CreateValidCreateDto(Action<CreateTenderItemDTO>? mutate = null)
    {
        var dto = new CreateTenderItemDTO
        {
            ExternalId = new string('a', 1),
            Description = new string('a', 1),
            Quantity = 1m,
            UnitName = new string('a', 1),
            UnitCode = new string('a', 1),
            ClassificationId = new string('a', 1),
            ClassificationScheme = new string('a', 1),
            ClassificationDescription = new string('a', 1),
            DeliveryEndDate = default!,
            DeliveryStreetAddress = new string('a', 1),
            DeliveryLocality = new string('a', 1),
            DeliveryRegion = new string('a', 1),
            DeliveryCountry = new string('a', 1),
            Profile = new string('a', 1),
            Category = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateTenderItemDTO CreateValidUpdateDto(Action<UpdateTenderItemDTO>? mutate = null)
    {
        var dto = new UpdateTenderItemDTO
        {
            Id = Guid.NewGuid(),
            ExternalId = new string('a', 1),
            Description = new string('a', 1),
            Quantity = 1m,
            UnitName = new string('a', 1),
            UnitCode = new string('a', 1),
            ClassificationId = new string('a', 1),
            ClassificationScheme = new string('a', 1),
            ClassificationDescription = new string('a', 1),
            DeliveryEndDate = default!,
            DeliveryStreetAddress = new string('a', 1),
            DeliveryLocality = new string('a', 1),
            DeliveryRegion = new string('a', 1),
            DeliveryCountry = new string('a', 1),
            Profile = new string('a', 1),
            Category = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static TenderItem CreateEntity()
    {
        return new TenderItem(
            new string('a', 1),
            new string('a', 1),
            1m,
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            default!,
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            Guid.NewGuid()
        );
    }
}
