// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.DataServices;
using EnergyBrockerage.Prozorro.BL.Creators;
using EnergyBrockerage.Prozorro.BL.Modifiers;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.BL.SearchProviders;
using EnergyBrockerage.Prozorro.BL.Validators;
using EnergyBrockerage.Prozorro.DTO.TenderPlan;

namespace EnergyBrockerage.Prozorro.API.Tests.Services;

public class TenderPlanDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<TenderPlan, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderPlanDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<TenderPlan>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new TenderPlanDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<TenderPlan>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateTenderPlanDTO dto)
    {
        var repository = new Mock<IRepository<TenderPlan, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderPlanDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderPlanDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<TenderPlan>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<TenderPlan, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderPlanDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderPlanDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<TenderPlan, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderPlanDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<TenderPlan>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new TenderPlanDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<TenderPlan>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateTenderPlanDTO dto)
    {
        var repository = new Mock<IRepository<TenderPlan, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderPlanDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderPlanDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<TenderPlan>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<TenderPlan, Guid>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<TenderPlanDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new TenderPlanDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.PlanExternalId = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.PlanExternalId = new string('a', 101)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.PlanExternalId = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.PlanExternalId = new string('a', 101)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateTenderPlanDTO>, CreateTenderPlanValidator>();
        services.AddScoped<IValidator<UpdateTenderPlanDTO>, UpdateTenderPlanValidator>();
        services.AddScoped<IEntityCreator<TenderPlan, CreateTenderPlanDTO>, TenderPlanCreator>();
        services.AddScoped<IEntityModifier<TenderPlan, UpdateTenderPlanDTO>, TenderPlanModifier>();
        services.AddScoped<IMapper<TenderPlan, TenderPlanDetailsDTO>, TenderPlanMapper>();
        services.AddScoped<ISearchQueryProvider<TenderPlan, TenderPlanSearchDTO>, TenderPlanSearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateTenderPlanDTO CreateValidCreateDto(Action<CreateTenderPlanDTO>? mutate = null)
    {
        var dto = new CreateTenderPlanDTO
        {
            PlanExternalId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateTenderPlanDTO CreateValidUpdateDto(Action<UpdateTenderPlanDTO>? mutate = null)
    {
        var dto = new UpdateTenderPlanDTO
        {
            Id = Guid.NewGuid(),
            PlanExternalId = new string('a', 1),
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static TenderPlan CreateEntity()
    {
        return new TenderPlan(
            new string('a', 1),
            Guid.NewGuid()
        );
    }
}
