// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-b67fcc4b
//     Generated: 2026-02-14 16:17:38 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Inventorization.Base.DataAccess;
using Inventorization.Commerce.Domain.Entities;

namespace Inventorization.Commerce.Domain.DataAccess;

/// <summary>
/// Converts SearchQuery ADT to IQueryable for Order entity.
/// Inherits all query building logic from BaseQueryBuilder.
/// Uses default ParameterName (first letter of entity name in lowercase).
/// </summary>
public class OrderQueryBuilder : BaseQueryBuilder<Order>
{
    // Empty body - uses all defaults from base class
    // Override ParameterName property if custom parameter name is needed
}
