// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-d9c2f1c6
//     Generated: 2026-02-14 16:11:52 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Customer;

/// <summary>
/// DTO for creating a new Customer
/// </summary>
public class CreateCustomerDTO : CreateDTO
{
    /// <summary>
    /// Customer first name
    /// </summary>
    [Required]
    [StringLength(100)]
    public string FirstName { get; set; } = default!;

    /// <summary>
    /// Customer last name
    /// </summary>
    [Required]
    [StringLength(100)]
    public string LastName { get; set; } = default!;

    /// <summary>
    /// Customer email address
    /// </summary>
    [Required]
    [StringLength(255)]
    public string Email { get; set; } = default!;

    /// <summary>
    /// Customer phone number
    /// </summary>
    [StringLength(20)]
    public string Phone { get; set; }

    /// <summary>
    /// Whether the customer account is active
    /// </summary>
    public bool IsActive { get; set; } = true;

}
