// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-b67fcc4b
//     Generated: 2026-02-14 16:17:38 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Customer;

/// <summary>
/// DTO with detailed information about a Customer
/// </summary>
public class CustomerDetailsDTO : DetailsDTO
{
    /// <summary>
    /// Customer first name
    /// </summary>
    public string FirstName { get; set; }

    /// <summary>
    /// Customer last name
    /// </summary>
    public string LastName { get; set; }

    /// <summary>
    /// Customer email address
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Customer phone number
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Whether the customer account is active
    /// </summary>
    public bool IsActive { get; set; }

}
