// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-d9c2f1c6
//     Generated: 2026-02-14 16:11:52 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Customer;

/// <summary>
/// DTO for searching/filtering Customer entities
/// </summary>
public class CustomerSearchDTO : SearchDTO
{
    /// <summary>
    /// Customer first name
    /// </summary>
    public string FirstName { get; set; }

    /// <summary>
    /// Customer last name
    /// </summary>
    public string LastName { get; set; }

    /// <summary>
    /// Customer email address
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Customer phone number
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// Whether the customer account is active
    /// </summary>
    public bool? IsActive { get; set; }

}
