// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-e497403a
//     Generated: 2026-02-14 16:34:58 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Customer;

/// <summary>
/// DTO for deleting a Customer
/// </summary>
public class DeleteCustomerDTO : DeleteDTO
{
    // Inherits Id from DeleteDTO base class
}
