// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-717476ad
//     Generated: 2026-02-15 18:29:05 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.Domain.DataServices;
using Inventorization.Commerce.Domain.Creators;
using Inventorization.Commerce.Domain.Modifiers;
using Inventorization.Commerce.Domain.Mappers;
using Inventorization.Commerce.Domain.SearchProviders;
using Inventorization.Commerce.Domain.Validators;
using Inventorization.Commerce.DTO.Category;

namespace Inventorization.Commerce.API.Tests.Services;

public class CategoryDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<Category>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<CategoryDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<Category>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new CategoryDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<Category>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateCategoryDTO dto)
    {
        var repository = new Mock<IRepository<Category>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<CategoryDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new CategoryDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<Category>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<Category>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<CategoryDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new CategoryDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<Category>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<CategoryDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<Category>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new CategoryDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<Category>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateCategoryDTO dto)
    {
        var repository = new Mock<IRepository<Category>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<CategoryDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new CategoryDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<Category>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<Category>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<CategoryDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new CategoryDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.Name = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.Name = new string('a', 101)) },
        new object[] { CreateValidCreateDto(dto => dto.Description = new string('a', 501)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Name = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Name = new string('a', 101)) },
        new object[] { CreateValidUpdateDto(dto => dto.Description = new string('a', 501)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateCategoryDTO>, CreateCategoryValidator>();
        services.AddScoped<IValidator<UpdateCategoryDTO>, UpdateCategoryValidator>();
        services.AddScoped<IEntityCreator<Category, CreateCategoryDTO>, CategoryCreator>();
        services.AddScoped<IEntityModifier<Category, UpdateCategoryDTO>, CategoryModifier>();
        services.AddScoped<IMapper<Category, CategoryDetailsDTO>, CategoryMapper>();
        services.AddScoped<ISearchQueryProvider<Category, CategorySearchDTO>, CategorySearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateCategoryDTO CreateValidCreateDto(Action<CreateCategoryDTO>? mutate = null)
    {
        var dto = new CreateCategoryDTO
        {
            Name = new string('a', 1),
            Description = new string('a', 1),
            IsActive = true,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateCategoryDTO CreateValidUpdateDto(Action<UpdateCategoryDTO>? mutate = null)
    {
        var dto = new UpdateCategoryDTO
        {
            Id = Guid.NewGuid(),
            Name = new string('a', 1),
            Description = new string('a', 1),
            IsActive = true,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static Category CreateEntity()
    {
        return new Category(
            new string('a', 1),
            new string('a', 1),
            true
        );
    }
}
