// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.BL.Services;
using Inventorization.Commerce.BL.Validators;
using Inventorization.Commerce.BL.DbContexts;
using Inventorization.Commerce.DTO.ADTs;

namespace Inventorization.Commerce.API.Tests.Services;

public class CustomerSearchServiceTests
{
    [Fact]
    public async Task ExecuteSearchAsync_ReturnsFailure_WhenQueryInvalid()
    {
        var repository = new Mock<IRepository<Customer>>();
        var queryBuilder = new Mock<IQueryBuilder<Customer>>();
        var projectionMapper = new Mock<IProjectionMapper<Customer, CustomerProjection>>();
        var expressionBuilder = new ProjectionExpressionBuilder();
        var validator = new CustomerSearchQueryValidator();
        var logger = new Mock<ILogger<CustomerSearchService>>();

        var service = new CustomerSearchService(
            repository.Object,
            queryBuilder.Object,
            projectionMapper.Object,
            expressionBuilder,
            validator,
            logger.Object);

        var invalidQuery = new SearchQuery(pagination: new PageRequest(0, 10));

        var result = await service.ExecuteSearchAsync(invalidQuery);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task ExecuteSearchAsync_ReturnsSuccess_WhenQueryValid()
    {
        var options = new DbContextOptionsBuilder<CommerceDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        using var context = new CommerceDbContext(options);

        var entity = CreateEntity();
        context.Set<Customer>().Add(entity);
        context.SaveChanges();

        var queryable = context.Set<Customer>();
        var repository = new Mock<IRepository<Customer>>();
        var queryBuilder = new Mock<IQueryBuilder<Customer>>();
        var projectionMapper = new Mock<IProjectionMapper<Customer, CustomerProjection>>();
        var expressionBuilder = new ProjectionExpressionBuilder();
        var validator = new CustomerSearchQueryValidator();
        var logger = new Mock<ILogger<CustomerSearchService>>();

        repository.Setup(r => r.GetQueryable()).Returns(queryable);
        queryBuilder.Setup(q => q.BuildQuery(queryable, It.IsAny<SearchQuery>())).Returns(queryable);

        Expression<Func<Customer, CustomerProjection>> projection = entity => new CustomerProjection
        {
            Id = entity.Id
        };
        projectionMapper.Setup(m => m.GetProjectionExpression(It.IsAny<ProjectionRequest?>())).Returns(projection);

        var service = new CustomerSearchService(
            repository.Object,
            queryBuilder.Object,
            projectionMapper.Object,
            expressionBuilder,
            validator,
            logger.Object);

        var query = new SearchQuery(pagination: new PageRequest(1, 10));

        var result = await service.ExecuteSearchAsync(query);

        result.IsSuccess.Should().BeTrue();
        result.Data.Should().NotBeNull();
        result.Data!.Items.Should().HaveCount(1);
    }

    private static Customer CreateEntity()
    {
        return new Customer(
            new string('a', 1),
            new string('a', 1),
            "user@example.com",
            new string('a', 1),
            true
        );
    }

}
