// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.Domain.DataServices;
using Inventorization.Commerce.Domain.Creators;
using Inventorization.Commerce.Domain.Modifiers;
using Inventorization.Commerce.Domain.Mappers;
using Inventorization.Commerce.Domain.SearchProviders;
using Inventorization.Commerce.Domain.Validators;
using Inventorization.Commerce.DTO.Order;

namespace Inventorization.Commerce.API.Tests.Services;

public class OrderDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<Order>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<Order>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new OrderDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<Order>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateOrderDTO dto)
    {
        var repository = new Mock<IRepository<Order>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<Order>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<Order>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<Order>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<Order>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new OrderDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<Order>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateOrderDTO dto)
    {
        var repository = new Mock<IRepository<Order>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<Order>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<Order>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.OrderNumber = string.Empty) },
        new object[] { CreateValidCreateDto(dto => dto.OrderNumber = new string('a', 51)) },
        new object[] { CreateValidCreateDto(dto => dto.OrderNumber = "invalid") },
        new object[] { CreateValidCreateDto(dto => dto.TotalAmount = (0m - 1m)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.OrderNumber = string.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.OrderNumber = new string('a', 51)) },
        new object[] { CreateValidUpdateDto(dto => dto.OrderNumber = "invalid") },
        new object[] { CreateValidUpdateDto(dto => dto.TotalAmount = (0m - 1m)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateOrderDTO>, CreateOrderValidator>();
        services.AddScoped<IValidator<UpdateOrderDTO>, UpdateOrderValidator>();
        services.AddScoped<IEntityCreator<Order, CreateOrderDTO>, OrderCreator>();
        services.AddScoped<IEntityModifier<Order, UpdateOrderDTO>, OrderModifier>();
        services.AddScoped<IMapper<Order, OrderDetailsDTO>, OrderMapper>();
        services.AddScoped<ISearchQueryProvider<Order, OrderSearchDTO>, OrderSearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateOrderDTO CreateValidCreateDto(Action<CreateOrderDTO>? mutate = null)
    {
        var dto = new CreateOrderDTO
        {
            OrderNumber = "ORD-00000001",
            OrderDate = DateTime.UtcNow,
            TotalAmount = 0m,
            Status = OrderStatus.Pending,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateOrderDTO CreateValidUpdateDto(Action<UpdateOrderDTO>? mutate = null)
    {
        var dto = new UpdateOrderDTO
        {
            Id = Guid.NewGuid(),
            OrderNumber = "ORD-00000001",
            OrderDate = DateTime.UtcNow,
            TotalAmount = 0m,
            Status = OrderStatus.Pending,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static Order CreateEntity()
    {
        return new Order(
            Guid.NewGuid(),
            "ORD-00000001",
            DateTime.UtcNow,
            0m,
            OrderStatus.Pending,
            Guid.NewGuid()
        );
    }
}
