// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-29e15abc
//     Generated: 2026-02-14 20:07:27 UTC
//     Source: simple-bounded-context.json
// </auto-generated>

#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.Domain.DataServices;
using Inventorization.Commerce.Domain.Creators;
using Inventorization.Commerce.Domain.Modifiers;
using Inventorization.Commerce.Domain.Mappers;
using Inventorization.Commerce.Domain.SearchProviders;
using Inventorization.Commerce.Domain.Validators;
using Inventorization.Commerce.DTO.OrderItem;

namespace Inventorization.Commerce.API.Tests.Services;

public class OrderItemDataServiceTests
{
    [Fact]
    public async Task AddAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<OrderItem>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var createdEntity = CreateEntity();
        repository
            .Setup(r => r.CreateAsync(It.IsAny<OrderItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(createdEntity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new OrderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidCreateDto();

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.CreateAsync(It.IsAny<OrderItem>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidCreateDtos))]
    public async Task AddAsync_ReturnsFailure_WhenDtoInvalid(CreateOrderItemDTO dto)
    {
        var repository = new Mock<IRepository<OrderItem>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.CreateAsync(It.IsAny<OrderItem>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task AddAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<OrderItem>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.AddAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public async Task UpdateAsync_ReturnsSuccess_WhenDtoValid()
    {
        var repository = new Mock<IRepository<OrderItem>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var entity = CreateEntity();
        repository
            .Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        repository
            .Setup(r => r.UpdateAsync(It.IsAny<OrderItem>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(entity);
        unitOfWork
            .Setup(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var service = new OrderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);
        var dto = CreateValidUpdateDto();

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeTrue();
        repository.Verify(r => r.UpdateAsync(It.IsAny<OrderItem>(), It.IsAny<CancellationToken>()), Times.Once);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [MemberData(nameof(InvalidUpdateDtos))]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoInvalid(UpdateOrderItemDTO dto)
    {
        var repository = new Mock<IRepository<OrderItem>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(dto);

        result.IsSuccess.Should().BeFalse();
        repository.Verify(r => r.UpdateAsync(It.IsAny<OrderItem>(), It.IsAny<CancellationToken>()), Times.Never);
        unitOfWork.Verify(u => u.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task UpdateAsync_ReturnsFailure_WhenDtoNull()
    {
        var repository = new Mock<IRepository<OrderItem>>();
        var unitOfWork = new Mock<IUnitOfWork>();
        var logger = new Mock<ILogger<OrderItemDataService>>();
        var serviceProvider = BuildServiceProvider();

        var service = new OrderItemDataService(unitOfWork.Object, repository.Object, serviceProvider, logger.Object);

        var result = await service.UpdateAsync(null!);

        result.IsSuccess.Should().BeFalse();
    }

    public static IEnumerable<object[]> InvalidCreateDtos => new List<object[]>
    {
        new object[] { CreateValidCreateDto(dto => dto.Quantity = (1 - 1)) },
        new object[] { CreateValidCreateDto(dto => dto.UnitPrice = (0m - 1m)) },
        new object[] { CreateValidCreateDto(dto => dto.TotalPrice = (0m - 1m)) },
    };

    public static IEnumerable<object[]> InvalidUpdateDtos => new List<object[]>
    {
        new object[] { CreateValidUpdateDto(dto => dto.Id = Guid.Empty) },
        new object[] { CreateValidUpdateDto(dto => dto.Quantity = (1 - 1)) },
        new object[] { CreateValidUpdateDto(dto => dto.UnitPrice = (0m - 1m)) },
        new object[] { CreateValidUpdateDto(dto => dto.TotalPrice = (0m - 1m)) },
    };

    private static IServiceProvider BuildServiceProvider()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddScoped<IValidator<CreateOrderItemDTO>, CreateOrderItemValidator>();
        services.AddScoped<IValidator<UpdateOrderItemDTO>, UpdateOrderItemValidator>();
        services.AddScoped<IEntityCreator<OrderItem, CreateOrderItemDTO>, OrderItemCreator>();
        services.AddScoped<IEntityModifier<OrderItem, UpdateOrderItemDTO>, OrderItemModifier>();
        services.AddScoped<IMapper<OrderItem, OrderItemDetailsDTO>, OrderItemMapper>();
        services.AddScoped<ISearchQueryProvider<OrderItem, OrderItemSearchDTO>, OrderItemSearchProvider>();
        return services.BuildServiceProvider();
    }

    private static CreateOrderItemDTO CreateValidCreateDto(Action<CreateOrderItemDTO>? mutate = null)
    {
        var dto = new CreateOrderItemDTO
        {
            Quantity = 1,
            UnitPrice = 0m,
            TotalPrice = 0m,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static UpdateOrderItemDTO CreateValidUpdateDto(Action<UpdateOrderItemDTO>? mutate = null)
    {
        var dto = new UpdateOrderItemDTO
        {
            Id = Guid.NewGuid(),
            Quantity = 1,
            UnitPrice = 0m,
            TotalPrice = 0m,
        };

        mutate?.Invoke(dto);
        return dto;
    }

    private static OrderItem CreateEntity()
    {
        return new OrderItem(
            Guid.NewGuid(),
            Guid.NewGuid(),
            1,
            0m,
            0m
        );
    }
}
