// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.DTOs;

namespace EnergyBrockerage.Prozorro.DTO.TenderItem;

/// <summary>
/// DTO for searching/filtering TenderItem entities
/// </summary>
public class TenderItemSearchDTO : SearchDTO
{
    /// <summary>
    /// Prozorro item ID
    /// </summary>
    public string ExternalId { get; set; }

    /// <summary>
    /// Item or service description
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Required quantity
    /// </summary>
    public decimal? Quantity { get; set; }

    /// <summary>
    /// Unit of measurement name
    /// </summary>
    public string UnitName { get; set; }

    /// <summary>
    /// UN/CEFACT unit code (e.g. KWH, KGM)
    /// </summary>
    public string UnitCode { get; set; }

    /// <summary>
    /// Classification code (CPV, UA-road, ДК021, etc.)
    /// </summary>
    public string ClassificationId { get; set; }

    /// <summary>
    /// Classification scheme name
    /// </summary>
    public string ClassificationScheme { get; set; }

    /// <summary>
    /// Human-readable classification description
    /// </summary>
    public string ClassificationDescription { get; set; }

    /// <summary>
    /// Required delivery completion date
    /// </summary>
    public string DeliveryEndDate { get; set; }

    /// <summary>
    /// Delivery street address
    /// </summary>
    public string DeliveryStreetAddress { get; set; }

    /// <summary>
    /// Delivery city or locality
    /// </summary>
    public string DeliveryLocality { get; set; }

    /// <summary>
    /// Delivery region or oblast
    /// </summary>
    public string DeliveryRegion { get; set; }

    /// <summary>
    /// Delivery country name
    /// </summary>
    public string DeliveryCountry { get; set; }

    /// <summary>
    /// Market profile reference (e.g. energy tariff profile ID)
    /// </summary>
    public string Profile { get; set; }

    /// <summary>
    /// Item category code or slug
    /// </summary>
    public string Category { get; set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid? TenderId { get; set; }

}
