// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260222-f94ae12e
//     Generated: 2026-02-22 17:37:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Inventorization.Base.Abstractions;
using Inventorization.Base.ADTs;
using Inventorization.Base.DataAccess;
using Inventorization.Base.Services;
using Inventorization.Base.Ownership;
using Inventorization.Commerce.BL.Entities;
using Inventorization.Commerce.BL.Validators;
using Inventorization.Commerce.DTO.ADTs;
using Microsoft.Extensions.Logging;

namespace Inventorization.Commerce.BL.Services;

/// <summary>
/// Service for executing ADT-based search queries on Order entities.
/// Ownership-aware: extends BaseSearchService&lt;Order, OrderProjection, UserTenantOwnership&gt;.
/// Exposes ExecuteOwnedSearchAsync which scopes results to the caller's identity.
/// Supports both regular projections and field transformations.
/// </summary>
public class OrderSearchService : BaseSearchService<Order, OrderProjection, UserTenantOwnership>
{
    public OrderSearchService(
        IRepository<Order> repository,
        IQueryBuilder<Order, UserTenantOwnership> queryBuilder,
        IProjectionMapper<Order, OrderProjection> projectionMapper,
        ProjectionExpressionBuilder expressionBuilder,
        OrderSearchQueryValidator validator,
        ICurrentIdentityContext<UserTenantOwnership> identityContext,
        ILogger<OrderSearchService> logger)
        : base(repository, queryBuilder, projectionMapper, expressionBuilder, validator, identityContext, logger)
    {
    }

    // Override ExecuteOwnedSearchAsync to apply custom owned-query logic if needed.
}
