// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.DTO.Product;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.Domain.Validators;

/// <summary>
/// Validator for UpdateProductDTO
/// </summary>
public class UpdateProductValidator : IValidator<UpdateProductDTO>
{
    public async Task<ValidationResult> ValidateAsync(
        UpdateProductDTO dto,
        CancellationToken cancellationToken = default)
    {
        if (dto == null)
            return ValidationResult.WithErrors("DTO cannot be null");

        var errors = new List<string>();

        if (dto.Id == Guid.Empty)
    errors.Add("Id is required");

        if (string.IsNullOrWhiteSpace(dto.Name))
    errors.Add("Name is required");

        if (!string.IsNullOrEmpty(dto.Name) && dto.Name.Length > 200)
    errors.Add("Name cannot exceed 200 characters");

        if (string.IsNullOrWhiteSpace(dto.SKU))
    errors.Add("SKU is required");

        if (!string.IsNullOrEmpty(dto.SKU) && dto.SKU.Length > 50)
    errors.Add("SKU cannot exceed 50 characters");

        if (!string.IsNullOrEmpty(dto.SKU) && !System.Text.RegularExpressions.Regex.IsMatch(dto.SKU, @"^[A-Z0-9-]+$"))
    errors.Add("SKU format is invalid");

        if (!string.IsNullOrEmpty(dto.Description) && dto.Description.Length > 2000)
    errors.Add("Description cannot exceed 2000 characters");

        if (dto.Price < 0)
    errors.Add("Price must be at least 0");

        if (dto.StockQuantity < 0)
    errors.Add("StockQuantity must be at least 0");


        return errors.Any()
            ? ValidationResult.WithErrors(errors.ToArray())
            : ValidationResult.Ok();
    }
}
