// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Inventorization.Commerce.DTO.OrderItem;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.Domain.Validators;

/// <summary>
/// Validator for UpdateOrderItemDTO
/// </summary>
public class UpdateOrderItemValidator : IValidator<UpdateOrderItemDTO>
{
    public Task<ValidationResult> ValidateAsync(
        UpdateOrderItemDTO dto,
        CancellationToken cancellationToken = default)
    {
        if (dto == null)
            return Task.FromResult(ValidationResult.WithErrors("DTO cannot be null"));

        var errors = new List<string>();

        if (dto.Id == Guid.Empty)
    errors.Add("Id is required");

        if (dto.Quantity < 1)
    errors.Add("Quantity must be at least 1");

        if (dto.UnitPrice < 0)
    errors.Add("UnitPrice must be at least 0");

        if (dto.TotalPrice < 0)
    errors.Add("TotalPrice must be at least 0");


        return Task.FromResult(errors.Any()
            ? ValidationResult.WithErrors(errors.ToArray())
            : ValidationResult.Ok());
    }
}
