// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.Order;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.Domain.SearchProviders;

/// <summary>
/// Search query provider for Order
/// </summary>
public class OrderSearchProvider : ISearchQueryProvider<Order, OrderSearchDTO>
{
    /// <summary>
    /// Builds search expression from search DTO
    /// </summary>
    public Expression<Func<Order, bool>> GetSearchExpression(OrderSearchDTO searchDto)
    {
        if (searchDto == null)
            throw new ArgumentNullException(nameof(searchDto));

        return entity =>
            (searchDto.OrderNumber == null || entity.OrderNumber.Contains(searchDto.OrderNumber)) &&
                        (searchDto.OrderDate == null || entity.OrderDate == searchDto.OrderDate) &&
                        (searchDto.Status == null || entity.Status == searchDto.Status)
            ;
    }
}
