// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.Product;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.Domain.SearchProviders;

/// <summary>
/// Search query provider for Product
/// </summary>
public class ProductSearchProvider : ISearchQueryProvider<Product, ProductSearchDTO>
{
    /// <summary>
    /// Builds search expression from search DTO
    /// </summary>
    public Expression<Func<Product, bool>> GetSearchExpression(ProductSearchDTO searchDto)
    {
        if (searchDto == null)
            throw new ArgumentNullException(nameof(searchDto));

        return entity =>
            (searchDto.Name == null || entity.Name.Contains(searchDto.Name)) &&
                        (searchDto.SKU == null || entity.SKU.Contains(searchDto.SKU)) &&
                        (searchDto.Description == null || entity.Description.Contains(searchDto.Description)) &&
                        (searchDto.Status == null || entity.Status == searchDto.Status) &&
                        (searchDto.IsActive == null || entity.IsActive == searchDto.IsActive)
            ;
    }
}
