// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Onward.Base.DTOs;

namespace EnergyBrockerage.Prozorro.DTO.Milestone;

/// <summary>
/// DTO for creating a new Milestone
/// </summary>
public class CreateMilestoneDTO : CreateDTO
{
    /// <summary>
    /// Prozorro milestone ID
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ExternalId { get; set; } = default!;

    /// <summary>
    /// Milestone title
    /// </summary>
    [StringLength(500)]
    public string Title { get; set; }

    /// <summary>
    /// Milestone description
    /// </summary>
    [StringLength(2000)]
    public string Description { get; set; }

    /// <summary>
    /// Milestone type (e.g. prepayment, postpayment)
    /// </summary>
    [StringLength(100)]
    public string Type { get; set; }

    /// <summary>
    /// Milestone code
    /// </summary>
    [StringLength(100)]
    public string Code { get; set; }

    /// <summary>
    /// Percentage of contract value for this milestone
    /// </summary>
    public decimal? Percentage { get; set; }

    /// <summary>
    /// Duration in days
    /// </summary>
    public int? DurationDays { get; set; }

    /// <summary>
    /// Duration type (working, banking, calendar)
    /// </summary>
    [StringLength(50)]
    public string DurationType { get; set; }

    /// <summary>
    /// Ordering sequence number
    /// </summary>
    public int? SequenceNumber { get; set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid TenderId { get; set; }

}
