// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Bid;
using Onward.Base.Services;
using Onward.Base.DataAccess;
using Onward.Base.Abstractions;
using Microsoft.Extensions.Logging;

namespace EnergyBrockerage.Prozorro.BL.DataServices;

/// <summary>
/// Data service interface for Bid
/// </summary>
public interface IBidDataService : IDataService<Bid, CreateBidDTO, UpdateBidDTO, DeleteBidDTO, InitBidDTO, BidDetailsDTO, BidSearchDTO, Guid>
{
}

/// <summary>
/// Data service implementation for Bid
/// </summary>
public class BidDataService : DataServiceBase<Bid, CreateBidDTO, UpdateBidDTO, DeleteBidDTO, InitBidDTO, BidDetailsDTO, BidSearchDTO>, IBidDataService
{
    public BidDataService(
        Onward.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<Bid, Guid> repository,
        IServiceProvider serviceProvider,
        ILogger<BidDataService> logger)
        : base(unitOfWork, repository, serviceProvider, logger)
    {
    }
}
