// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;
using Onward.Base.Services;
using Onward.Base.DataAccess;
using Onward.Base.Abstractions;
using Microsoft.Extensions.Logging;

namespace EnergyBrockerage.Prozorro.BL.DataServices;

/// <summary>
/// Data service interface for ContractChangeRationaleType
/// </summary>
public interface IContractChangeRationaleTypeDataService : IDataService<ContractChangeRationaleType, CreateContractChangeRationaleTypeDTO, UpdateContractChangeRationaleTypeDTO, DeleteContractChangeRationaleTypeDTO, InitContractChangeRationaleTypeDTO, ContractChangeRationaleTypeDetailsDTO, ContractChangeRationaleTypeSearchDTO, Guid>
{
}

/// <summary>
/// Data service implementation for ContractChangeRationaleType
/// </summary>
public class ContractChangeRationaleTypeDataService : DataServiceBase<ContractChangeRationaleType, CreateContractChangeRationaleTypeDTO, UpdateContractChangeRationaleTypeDTO, DeleteContractChangeRationaleTypeDTO, InitContractChangeRationaleTypeDTO, ContractChangeRationaleTypeDetailsDTO, ContractChangeRationaleTypeSearchDTO>, IContractChangeRationaleTypeDataService
{
    public ContractChangeRationaleTypeDataService(
        Onward.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<ContractChangeRationaleType, Guid> repository,
        IServiceProvider serviceProvider,
        ILogger<ContractChangeRationaleTypeDataService> logger)
        : base(unitOfWork, repository, serviceProvider, logger)
    {
    }
}
