// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Requirement;
using Onward.Base.Services;
using Onward.Base.DataAccess;
using Onward.Base.Abstractions;
using Microsoft.Extensions.Logging;

namespace EnergyBrockerage.Prozorro.BL.DataServices;

/// <summary>
/// Data service interface for Requirement
/// </summary>
public interface IRequirementDataService : IDataService<Requirement, CreateRequirementDTO, UpdateRequirementDTO, DeleteRequirementDTO, InitRequirementDTO, RequirementDetailsDTO, RequirementSearchDTO, Guid>
{
}

/// <summary>
/// Data service implementation for Requirement
/// </summary>
public class RequirementDataService : DataServiceBase<Requirement, CreateRequirementDTO, UpdateRequirementDTO, DeleteRequirementDTO, InitRequirementDTO, RequirementDetailsDTO, RequirementSearchDTO>, IRequirementDataService
{
    public RequirementDataService(
        Onward.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<Requirement, Guid> repository,
        IServiceProvider serviceProvider,
        ILogger<RequirementDataService> logger)
        : base(unitOfWork, repository, serviceProvider, logger)
    {
    }
}
