// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.TenderPlan;
using Onward.Base.Services;
using Onward.Base.DataAccess;
using Onward.Base.Abstractions;
using Microsoft.Extensions.Logging;

namespace EnergyBrockerage.Prozorro.BL.DataServices;

/// <summary>
/// Data service interface for TenderPlan
/// </summary>
public interface ITenderPlanDataService : IDataService<TenderPlan, CreateTenderPlanDTO, UpdateTenderPlanDTO, DeleteTenderPlanDTO, InitTenderPlanDTO, TenderPlanDetailsDTO, TenderPlanSearchDTO, Guid>
{
}

/// <summary>
/// Data service implementation for TenderPlan
/// </summary>
public class TenderPlanDataService : DataServiceBase<TenderPlan, CreateTenderPlanDTO, UpdateTenderPlanDTO, DeleteTenderPlanDTO, InitTenderPlanDTO, TenderPlanDetailsDTO, TenderPlanSearchDTO>, ITenderPlanDataService
{
    public TenderPlanDataService(
        Onward.Base.DataAccess.IUnitOfWork unitOfWork,
        IRepository<TenderPlan, Guid> repository,
        IServiceProvider serviceProvider,
        ILogger<TenderPlanDataService> logger)
        : base(unitOfWork, repository, serviceProvider, logger)
    {
    }
}
