// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-b67fcc4b
//     Generated: 2026-02-14 16:17:38 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

#nullable enable

using Inventorization.Base.Models;

namespace Inventorization.Commerce.Meta;

/// <summary>
/// Centralized repository of all entity metadata for Commerce bounded context.
/// Single source of truth for entity structure, validation rules, and EF configuration.
/// Use this metadata for:
/// - Generating validators
/// - Configuring EF Core models
/// - Generating UI forms
/// - API documentation
/// - Code generation
/// All metadata is string-based and does not reference domain entities.
/// </summary>
public static class DataModelMetadata
{
    #region Category Entity Metadata

    /// <summary>
    /// Complete metadata for the Category entity
    /// </summary>
    public static readonly EntityMetadata Category = new EntityMetadata
    {
        EntityName = "Category",
        TableName = "Categories",
        
        DisplayName = "Category",
        Description = "Product category",
        HasAuditing = true,
        Properties = new PropertyMetadata[]
        {
            new PropertyMetadata
            {
                PropertyName = "Name",
                PropertyType = "string",
                DisplayName = "Category Name",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 100,
                Description = "Category name"
            },
            new PropertyMetadata
            {
                PropertyName = "Description",
                PropertyType = "string",
                DisplayName = "Description",
                IsRequired = false,
                IsNullable = true,
                MaxLength = 500,
                Description = "Category description"
            },
            new PropertyMetadata
            {
                PropertyName = "IsActive",
                PropertyType = "bool",
                DisplayName = "IsActive",
                IsRequired = true,
                IsNullable = false,
                IsIndexed = true,
                DefaultValue = "true",
                Description = "Whether the category is active"
            }
        },
        Indexes = new IndexMetadata[]
        {
            new IndexMetadata
            {
                Name = "IX_Categories_Name",
                Columns = new[] { "Name" },
                IsUnique = true
            },
            new IndexMetadata
            {
                Name = "IX_Categories_IsActive",
                Columns = new[] { "IsActive" },
                IsUnique = false
            }
        },
        UniqueConstraints = new UniqueConstraintMetadata[]
        {
            new UniqueConstraintMetadata
            {
                Name = "IX_Categories_Name",
                Columns = new[] { "Name" }
            }
        }
    };

    #endregion

    #region Product Entity Metadata

    /// <summary>
    /// Complete metadata for the Product entity
    /// </summary>
    public static readonly EntityMetadata Product = new EntityMetadata
    {
        EntityName = "Product",
        TableName = "Products",
        
        DisplayName = "Product",
        Description = "Product in the catalog",
        HasAuditing = true,
        Properties = new PropertyMetadata[]
        {
            new PropertyMetadata
            {
                PropertyName = "Name",
                PropertyType = "string",
                DisplayName = "Product Name",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 200,
                Description = "Product name",
                ValidationMessage = "Product name is required and must not exceed 200 characters"
            },
            new PropertyMetadata
            {
                PropertyName = "SKU",
                PropertyType = "string",
                DisplayName = "SKU",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 50,
                IsUnique = true,
                RegexPattern = @"^[A-Z0-9-]+$",
                Description = "Stock keeping unit (unique identifier)"
            },
            new PropertyMetadata
            {
                PropertyName = "Description",
                PropertyType = "string",
                DisplayName = "Description",
                IsRequired = false,
                IsNullable = true,
                MaxLength = 2000,
                Description = "Product description"
            },
            new PropertyMetadata
            {
                PropertyName = "Price",
                PropertyType = "decimal",
                DisplayName = "Price",
                IsRequired = true,
                IsNullable = false,
                Precision = 18,
                Scale = 2,
                ColumnType = "decimal(18,2)",
                Description = "Product price"
            },
            new PropertyMetadata
            {
                PropertyName = "StockQuantity",
                PropertyType = "int",
                DisplayName = "StockQuantity",
                IsRequired = true,
                IsNullable = false,
                DefaultValue = "0",
                Description = "Available stock quantity"
            },
            new PropertyMetadata
            {
                PropertyName = "CategoryId",
                PropertyType = "Guid",
                DisplayName = "CategoryId",
                IsRequired = true,
                IsNullable = false,
                IsForeignKey = true,
                IsIndexed = true,
                Description = "Category ID"
            },
            new PropertyMetadata
            {
                PropertyName = "Status",
                PropertyType = "int",
                DisplayName = "Status",
                IsRequired = true,
                IsNullable = false,
                DefaultValue = "ProductStatus.Draft",
                Description = "Product status"
            },
            new PropertyMetadata
            {
                PropertyName = "IsActive",
                PropertyType = "bool",
                DisplayName = "IsActive",
                IsRequired = true,
                IsNullable = false,
                IsIndexed = true,
                DefaultValue = "true",
                Description = "Whether the product is active"
            }
        },
        Indexes = new IndexMetadata[]
        {
            new IndexMetadata
            {
                Name = "IX_Products_SKU",
                Columns = new[] { "SKU" },
                IsUnique = true
            },
            new IndexMetadata
            {
                Name = "IX_Products_Name",
                Columns = new[] { "Name" },
                IsUnique = false
            },
            new IndexMetadata
            {
                Name = "IX_Products_CategoryId",
                Columns = new[] { "CategoryId" },
                IsUnique = false
            },
            new IndexMetadata
            {
                Name = "IX_Products_IsActive",
                Columns = new[] { "IsActive" },
                IsUnique = false
            }
        },
        UniqueConstraints = new UniqueConstraintMetadata[]
        {
            new UniqueConstraintMetadata
            {
                Name = "IX_Products_SKU",
                Columns = new[] { "SKU" }
            }
        }
    };

    #endregion

    #region Customer Entity Metadata

    /// <summary>
    /// Complete metadata for the Customer entity
    /// </summary>
    public static readonly EntityMetadata Customer = new EntityMetadata
    {
        EntityName = "Customer",
        TableName = "Customers",
        
        DisplayName = "Customer",
        Description = "Customer account",
        HasAuditing = true,
        Properties = new PropertyMetadata[]
        {
            new PropertyMetadata
            {
                PropertyName = "FirstName",
                PropertyType = "string",
                DisplayName = "First Name",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 100,
                Description = "Customer first name"
            },
            new PropertyMetadata
            {
                PropertyName = "LastName",
                PropertyType = "string",
                DisplayName = "Last Name",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 100,
                Description = "Customer last name"
            },
            new PropertyMetadata
            {
                PropertyName = "Email",
                PropertyType = "string",
                DisplayName = "Email",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 255,
                IsUnique = true,
                Description = "Customer email address"
            },
            new PropertyMetadata
            {
                PropertyName = "Phone",
                PropertyType = "string",
                DisplayName = "Phone",
                IsRequired = false,
                IsNullable = true,
                MaxLength = 20,
                Description = "Customer phone number"
            },
            new PropertyMetadata
            {
                PropertyName = "IsActive",
                PropertyType = "bool",
                DisplayName = "IsActive",
                IsRequired = true,
                IsNullable = false,
                IsIndexed = true,
                DefaultValue = "true",
                Description = "Whether the customer account is active"
            }
        },
        Indexes = new IndexMetadata[]
        {
            new IndexMetadata
            {
                Name = "IX_Customers_Email",
                Columns = new[] { "Email" },
                IsUnique = true
            },
            new IndexMetadata
            {
                Name = "IX_Customers_IsActive",
                Columns = new[] { "IsActive" },
                IsUnique = false
            }
        },
        UniqueConstraints = new UniqueConstraintMetadata[]
        {
            new UniqueConstraintMetadata
            {
                Name = "IX_Customers_Email",
                Columns = new[] { "Email" }
            }
        }
    };

    #endregion

    #region Address Entity Metadata

    /// <summary>
    /// Complete metadata for the Address entity
    /// </summary>
    public static readonly EntityMetadata Address = new EntityMetadata
    {
        EntityName = "Address",
        TableName = "Addresses",
        
        DisplayName = "Address",
        Description = "Customer address",
        HasAuditing = false,
        Properties = new PropertyMetadata[]
        {
            new PropertyMetadata
            {
                PropertyName = "CustomerId",
                PropertyType = "Guid",
                DisplayName = "CustomerId",
                IsRequired = true,
                IsNullable = false,
                IsForeignKey = true,
                IsIndexed = true,
                Description = "Customer ID"
            },
            new PropertyMetadata
            {
                PropertyName = "AddressType",
                PropertyType = "int",
                DisplayName = "AddressType",
                IsRequired = true,
                IsNullable = false,
                DefaultValue = "AddressType.Shipping",
                Description = "Address type (Shipping or Billing)"
            },
            new PropertyMetadata
            {
                PropertyName = "Street",
                PropertyType = "string",
                DisplayName = "Street",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 200,
                Description = "Street address"
            },
            new PropertyMetadata
            {
                PropertyName = "City",
                PropertyType = "string",
                DisplayName = "City",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 100,
                Description = "City"
            },
            new PropertyMetadata
            {
                PropertyName = "State",
                PropertyType = "string",
                DisplayName = "State",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 100,
                Description = "State or province"
            },
            new PropertyMetadata
            {
                PropertyName = "PostalCode",
                PropertyType = "string",
                DisplayName = "PostalCode",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 20,
                Description = "Postal or ZIP code"
            },
            new PropertyMetadata
            {
                PropertyName = "Country",
                PropertyType = "string",
                DisplayName = "Country",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 100,
                Description = "Country"
            },
            new PropertyMetadata
            {
                PropertyName = "IsDefault",
                PropertyType = "bool",
                DisplayName = "IsDefault",
                IsRequired = true,
                IsNullable = false,
                DefaultValue = "false",
                Description = "Whether this is the default address"
            }
        },
        Indexes = new IndexMetadata[]
        {
            new IndexMetadata
            {
                Name = "IX_Addresses_CustomerId",
                Columns = new[] { "CustomerId" },
                IsUnique = false
            }
        },
        UniqueConstraints = new UniqueConstraintMetadata[]
        {
        }
    };

    #endregion

    #region Order Entity Metadata

    /// <summary>
    /// Complete metadata for the Order entity
    /// </summary>
    public static readonly EntityMetadata Order = new EntityMetadata
    {
        EntityName = "Order",
        TableName = "Orders",
        
        DisplayName = "Order",
        Description = "Customer order",
        HasAuditing = true,
        Properties = new PropertyMetadata[]
        {
            new PropertyMetadata
            {
                PropertyName = "CustomerId",
                PropertyType = "Guid",
                DisplayName = "CustomerId",
                IsRequired = true,
                IsNullable = false,
                IsForeignKey = true,
                IsIndexed = true,
                Description = "Customer ID"
            },
            new PropertyMetadata
            {
                PropertyName = "OrderNumber",
                PropertyType = "string",
                DisplayName = "OrderNumber",
                IsRequired = true,
                IsNullable = false,
                MaxLength = 50,
                RegexPattern = @"^ORD-[0-9]{8}$",
                Description = "Unique order number"
            },
            new PropertyMetadata
            {
                PropertyName = "OrderDate",
                PropertyType = "DateTime",
                DisplayName = "OrderDate",
                IsRequired = true,
                IsNullable = false,
                Description = "Order date and time"
            },
            new PropertyMetadata
            {
                PropertyName = "TotalAmount",
                PropertyType = "decimal",
                DisplayName = "TotalAmount",
                IsRequired = true,
                IsNullable = false,
                Precision = 18,
                Scale = 2,
                ColumnType = "decimal(18,2)",
                Description = "Total order amount"
            },
            new PropertyMetadata
            {
                PropertyName = "Status",
                PropertyType = "int",
                DisplayName = "Status",
                IsRequired = true,
                IsNullable = false,
                DefaultValue = "OrderStatus.Pending",
                Description = "Order status"
            },
            new PropertyMetadata
            {
                PropertyName = "ShippingAddressId",
                PropertyType = "Guid",
                DisplayName = "ShippingAddressId",
                IsRequired = true,
                IsNullable = false,
                IsForeignKey = true,
                IsIndexed = true,
                Description = "Shipping address ID"
            }
        },
        Indexes = new IndexMetadata[]
        {
            new IndexMetadata
            {
                Name = "IX_Orders_OrderNumber",
                Columns = new[] { "OrderNumber" },
                IsUnique = true
            },
            new IndexMetadata
            {
                Name = "IX_Orders_CustomerId",
                Columns = new[] { "CustomerId" },
                IsUnique = false
            },
            new IndexMetadata
            {
                Name = "IX_Orders_OrderDate",
                Columns = new[] { "OrderDate" },
                IsUnique = false
            },
            new IndexMetadata
            {
                Name = "IX_Orders_ShippingAddressId",
                Columns = new[] { "ShippingAddressId" },
                IsUnique = false
            }
        },
        UniqueConstraints = new UniqueConstraintMetadata[]
        {
            new UniqueConstraintMetadata
            {
                Name = "IX_Orders_OrderNumber",
                Columns = new[] { "OrderNumber" }
            }
        }
    };

    #endregion

    #region OrderItem Entity Metadata

    /// <summary>
    /// Complete metadata for the OrderItem entity
    /// </summary>
    public static readonly EntityMetadata OrderItem = new EntityMetadata
    {
        EntityName = "OrderItem",
        TableName = "OrderItems",
        
        DisplayName = "OrderItem",
        Description = "Order line item",
        HasAuditing = false,
        Properties = new PropertyMetadata[]
        {
            new PropertyMetadata
            {
                PropertyName = "OrderId",
                PropertyType = "Guid",
                DisplayName = "OrderId",
                IsRequired = true,
                IsNullable = false,
                IsForeignKey = true,
                IsIndexed = true,
                Description = "Order ID"
            },
            new PropertyMetadata
            {
                PropertyName = "ProductId",
                PropertyType = "Guid",
                DisplayName = "ProductId",
                IsRequired = true,
                IsNullable = false,
                IsForeignKey = true,
                IsIndexed = true,
                Description = "Product ID"
            },
            new PropertyMetadata
            {
                PropertyName = "Quantity",
                PropertyType = "int",
                DisplayName = "Quantity",
                IsRequired = true,
                IsNullable = false,
                MinValue = 1,
                Description = "Quantity ordered"
            },
            new PropertyMetadata
            {
                PropertyName = "UnitPrice",
                PropertyType = "decimal",
                DisplayName = "UnitPrice",
                IsRequired = true,
                IsNullable = false,
                Precision = 18,
                Scale = 2,
                ColumnType = "decimal(18,2)",
                Description = "Price per unit at time of order"
            },
            new PropertyMetadata
            {
                PropertyName = "TotalPrice",
                PropertyType = "decimal",
                DisplayName = "TotalPrice",
                IsRequired = true,
                IsNullable = false,
                Precision = 18,
                Scale = 2,
                ColumnType = "decimal(18,2)",
                Description = "Total price for this line item"
            }
        },
        Indexes = new IndexMetadata[]
        {
            new IndexMetadata
            {
                Name = "IX_OrderItems_OrderId",
                Columns = new[] { "OrderId" },
                IsUnique = false
            },
            new IndexMetadata
            {
                Name = "IX_OrderItems_ProductId",
                Columns = new[] { "ProductId" },
                IsUnique = false
            }
        },
        UniqueConstraints = new UniqueConstraintMetadata[]
        {
        }
    };

    #endregion

    #region Helper Methods

    /// <summary>
    /// Get all entity metadata in this bounded context
    /// </summary>
    public static IReadOnlyList<EntityMetadata> GetAllEntityMetadata() => new List<EntityMetadata>
    {
        Category,
        Product,
        Customer,
        Address,
        Order,
        OrderItem
    };

    /// <summary>
    /// Get metadata for a specific entity by name
    /// </summary>
    public static EntityMetadata? GetEntityMetadata(string entityName) => entityName switch
    {
        "Category" => Category,
        "Product" => Product,
        "Customer" => Customer,
        "Address" => Address,
        "Order" => Order,
        "OrderItem" => OrderItem,
        _ => null
    };

    #endregion
}
