// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-717476ad
//     Generated: 2026-02-15 18:29:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.Models;
using System.Text.Json.Serialization;

namespace Inventorization.Commerce.Common.Enums;

/// <summary>
/// Address type classification - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<AddressType>))]
public sealed class AddressType : Enumeration
{
    /// <summary>
    /// Shipping address
    /// </summary>
    public static readonly AddressType Shipping = new(nameof(Shipping), 0);

    /// <summary>
    /// Billing address
    /// </summary>
    public static readonly AddressType Billing = new(nameof(Billing), 1);

    private AddressType(string name, int value) : base(name, value) { }

    public static AddressType FromName(string name) => FromNameOrThrow<AddressType>(name);
    public static AddressType FromValue(int value) => FromValueOrThrow<AddressType>(value);
    public static IEnumerable<AddressType> GetAll() => Enumeration.GetAll<AddressType>();
}
