// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-717476ad
//     Generated: 2026-02-15 18:29:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.Models;
using System.Text.Json.Serialization;

namespace Inventorization.Commerce.Common.Enums;

/// <summary>
/// Product availability status - Smart Enum (stores as int, serializes as string)
/// </summary>
[JsonConverter(typeof(EnumerationJsonConverter<ProductStatus>))]
public sealed class ProductStatus : Enumeration
{
    /// <summary>
    /// Product is being prepared
    /// </summary>
    public static readonly ProductStatus Draft = new(nameof(Draft), 0);

    /// <summary>
    /// Product is available for sale
    /// </summary>
    public static readonly ProductStatus Active = new(nameof(Active), 1);

    /// <summary>
    /// Product is temporarily unavailable
    /// </summary>
    public static readonly ProductStatus OutOfStock = new(nameof(OutOfStock), 2);

    /// <summary>
    /// Product is no longer available
    /// </summary>
    public static readonly ProductStatus Discontinued = new(nameof(Discontinued), 3);

    private ProductStatus(string name, int value) : base(name, value) { }

    public static ProductStatus FromName(string name) => FromNameOrThrow<ProductStatus>(name);
    public static ProductStatus FromValue(int value) => FromValueOrThrow<ProductStatus>(value);
    public static IEnumerable<ProductStatus> GetAll() => Enumeration.GetAll<ProductStatus>();
}
