// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EnergyBrockerage.Prozorro.BL.Entities;
using Onward.Base.DataAccess;

namespace EnergyBrockerage.Prozorro.BL.EntityConfigurations;

/// <summary>
/// Entity configuration for BidItem
/// </summary>
public class BidItemConfiguration : BaseEntityConfiguration<BidItem, Guid>
{
    protected override void ConfigureEntity(EntityTypeBuilder<BidItem> builder)
    {
        builder.ToTable("BidItems");

        builder.Property(e => e.ExternalId)
    .IsRequired()
    .HasMaxLength(100)
;

        builder.Property(e => e.Description)
    .HasMaxLength(2000)
;

        builder.Property(e => e.Quantity)
    .HasPrecision(18, 4)
;

        builder.Property(e => e.UnitName)
    .HasMaxLength(100)
;

        builder.Property(e => e.UnitCode)
    .HasMaxLength(20)
;

        builder.Property(e => e.UnitPrice)
    .HasPrecision(18, 6)
;

        builder.Property(e => e.UnitPriceCurrency)
    .HasMaxLength(10)
;

        builder.HasIndex(e => e.BidId);

        builder.HasIndex(e => new { e.ExternalId, e.BidId })
    .IsUnique();

        builder.HasOne(e => e.Bid)
    .WithMany(p => p.Items)
    .HasForeignKey(e => e.BidId)
    .OnDelete(DeleteBehavior.Restrict);

    }
}
