// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.Common.Enums;
using Onward.Base.DataAccess;

namespace EnergyBrockerage.Prozorro.BL.EntityConfigurations;

/// <summary>
/// Entity configuration for Contract
/// </summary>
public class ContractConfiguration : BaseEntityConfiguration<Contract, Guid>
{
    protected override void ConfigureEntity(EntityTypeBuilder<Contract> builder)
    {
        builder.ToTable("Contracts");

        builder.Property(e => e.ExternalId)
    .IsRequired()
    .HasMaxLength(100)
;

        builder.Property(e => e.ContractNumber)
    .HasMaxLength(100)
;

        builder.Property(e => e.Title)
    .HasMaxLength(1000)
;

        builder.Property(e => e.Description)
    .HasMaxLength(4000)
;

        builder.Property(e => e.Status)
    .IsRequired()
    .HasDefaultValue(ContractStatus.Pending)
    .HasConversion(new EnumerationConverter<ContractStatus>())
;

        builder.OwnsOne(e => e.ContractDate, b =>
{
    b.Property(x => x.UtcTicks).HasColumnName("ContractDate_UtcTicks").HasColumnType("bigint").IsRequired(false);
    b.Property(x => x.OffsetMinutes).HasColumnName("ContractDate_OffsetMinutes").HasColumnType("smallint").IsRequired(false);
});

        builder.Property(e => e.Amount)
    .HasPrecision(18, 2)
;

        builder.Property(e => e.Currency)
    .HasMaxLength(10)
;

        builder.Property(e => e.AwardExternalId)
    .HasMaxLength(100)
;

        builder.HasIndex(e => e.ExternalId)
    .IsUnique();

        builder.HasIndex(e => e.TenderId);

        builder.HasOne(e => e.Tender)
    .WithMany(p => p.Contracts)
    .HasForeignKey(e => e.TenderId)
    .OnDelete(DeleteBehavior.Restrict);

    }
}
