// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EnergyBrockerage.Prozorro.BL.Entities;
using Onward.Base.DataAccess;

namespace EnergyBrockerage.Prozorro.BL.EntityConfigurations;

/// <summary>
/// Entity configuration for Criterion
/// </summary>
public class CriterionConfiguration : BaseEntityConfiguration<Criterion, Guid>
{
    protected override void ConfigureEntity(EntityTypeBuilder<Criterion> builder)
    {
        builder.ToTable("Criteria");

        builder.Property(e => e.ExternalId)
    .IsRequired()
    .HasMaxLength(100)
;

        builder.Property(e => e.Title)
    .HasMaxLength(500)
;

        builder.Property(e => e.Description)
    .HasMaxLength(2000)
;

        builder.Property(e => e.Source)
    .HasMaxLength(100)
;

        builder.Property(e => e.RelatesTo)
    .HasMaxLength(100)
;

        builder.Property(e => e.RelatedItem)
    .HasMaxLength(100)
;

        builder.Property(e => e.ClassificationScheme)
    .HasMaxLength(100)
;

        builder.Property(e => e.ClassificationId)
    .HasMaxLength(100)
;

        builder.HasIndex(e => e.TenderId);

        builder.HasOne(e => e.Tender)
    .WithMany(p => p.Criteria)
    .HasForeignKey(e => e.TenderId)
    .OnDelete(DeleteBehavior.Restrict);

    }
}
