// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.Common.Enums;
using Onward.Base.DataAccess;

namespace EnergyBrockerage.Prozorro.BL.EntityConfigurations;

/// <summary>
/// Entity configuration for Organization
/// </summary>
public class OrganizationConfiguration : BaseEntityConfiguration<Organization, Guid>
{
    protected override void ConfigureEntity(EntityTypeBuilder<Organization> builder)
    {
        builder.ToTable("Organizations");

        builder.Property(e => e.ExternalId)
    .IsRequired()
    .HasMaxLength(100)
;

        builder.Property(e => e.IdentifierScheme)
    .IsRequired()
    .HasMaxLength(50)
;

        builder.Property(e => e.Name)
    .IsRequired()
    .HasMaxLength(500)
;

        builder.Property(e => e.NameEn)
    .HasMaxLength(500)
;

        builder.Property(e => e.LegalName)
    .IsRequired()
    .HasMaxLength(500)
;

        builder.Property(e => e.LegalNameEn)
    .HasMaxLength(500)
;

        builder.Property(e => e.Kind)
    .HasDefaultValue(OrganizationKind.General)
    .HasConversion(new EnumerationConverter<OrganizationKind>())
;

        builder.Property(e => e.Scale)
    .HasDefaultValue(OrganizationScale.NotSpecified)
    .HasConversion(new EnumerationConverter<OrganizationScale>())
;

        builder.Property(e => e.StreetAddress)
    .HasMaxLength(500)
;

        builder.Property(e => e.Locality)
    .HasMaxLength(200)
;

        builder.Property(e => e.Region)
    .HasMaxLength(200)
;

        builder.Property(e => e.PostalCode)
    .HasMaxLength(20)
;

        builder.Property(e => e.CountryName)
    .HasMaxLength(100)
;

        builder.Property(e => e.ContactName)
    .HasMaxLength(300)
;

        builder.Property(e => e.ContactEmail)
    .HasMaxLength(255)
;

        builder.Property(e => e.ContactPhone)
    .HasMaxLength(100)
;

        builder.Property(e => e.ContactUrl)
    .HasMaxLength(500)
;

        builder.HasIndex(e => new { e.ExternalId, e.IdentifierScheme })
    .IsUnique();

    }
}
