// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EnergyBrockerage.Prozorro.BL.Entities;
using Onward.Base.DataAccess;

namespace EnergyBrockerage.Prozorro.BL.EntityConfigurations;

/// <summary>
/// Entity configuration for Requirement
/// </summary>
public class RequirementConfiguration : BaseEntityConfiguration<Requirement, Guid>
{
    protected override void ConfigureEntity(EntityTypeBuilder<Requirement> builder)
    {
        builder.ToTable("Requirements");

        builder.Property(e => e.ExternalId)
    .IsRequired()
    .HasMaxLength(100)
;

        builder.Property(e => e.Title)
    .HasMaxLength(500)
;

        builder.Property(e => e.DataType)
    .HasMaxLength(50)
;

        builder.Property(e => e.Status)
    .HasMaxLength(50)
;

        builder.Property(e => e.ExpectedValue)
    .HasMaxLength(500)
;

        builder.Property(e => e.ExpectedValuesJson)
    .HasMaxLength(4000)
;

        builder.Property(e => e.ExpectedMinItems)
;

        builder.Property(e => e.ExpectedMaxItems)
;

        builder.OwnsOne(e => e.DatePublished, b =>
{
    b.Property(x => x.UtcTicks).HasColumnName("DatePublished_UtcTicks").HasColumnType("bigint").IsRequired(false);
    b.Property(x => x.OffsetMinutes).HasColumnName("DatePublished_OffsetMinutes").HasColumnType("smallint").IsRequired(false);
});

        builder.HasIndex(e => e.RequirementGroupId);

        builder.HasOne(e => e.RequirementGroup)
    .WithMany(p => p.Requirements)
    .HasForeignKey(e => e.RequirementGroupId)
    .OnDelete(DeleteBehavior.Restrict);

    }
}
