// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using EnergyBrockerage.Prozorro.BL.Entities;
using Onward.Base.DataAccess;

namespace EnergyBrockerage.Prozorro.BL.EntityConfigurations;

/// <summary>
/// Entity configuration for TenderItem
/// </summary>
public class TenderItemConfiguration : BaseEntityConfiguration<TenderItem, Guid>
{
    protected override void ConfigureEntity(EntityTypeBuilder<TenderItem> builder)
    {
        builder.ToTable("TenderItems");

        builder.Property(e => e.ExternalId)
    .IsRequired()
    .HasMaxLength(100)
;

        builder.Property(e => e.Description)
    .IsRequired()
    .HasMaxLength(2000)
;

        builder.Property(e => e.Quantity)
    .HasPrecision(18, 4)
;

        builder.Property(e => e.UnitName)
    .HasMaxLength(100)
;

        builder.Property(e => e.UnitCode)
    .HasMaxLength(20)
;

        builder.Property(e => e.ClassificationId)
    .HasMaxLength(50)
;

        builder.Property(e => e.ClassificationScheme)
    .HasMaxLength(50)
;

        builder.Property(e => e.ClassificationDescription)
    .HasMaxLength(500)
;

        builder.OwnsOne(e => e.DeliveryEndDate, b =>
{
    b.Property(x => x.UtcTicks).HasColumnName("DeliveryEndDate_UtcTicks").HasColumnType("bigint").IsRequired(false);
    b.Property(x => x.OffsetMinutes).HasColumnName("DeliveryEndDate_OffsetMinutes").HasColumnType("smallint").IsRequired(false);
});

        builder.Property(e => e.DeliveryStreetAddress)
    .HasMaxLength(500)
;

        builder.Property(e => e.DeliveryLocality)
    .HasMaxLength(200)
;

        builder.Property(e => e.DeliveryRegion)
    .HasMaxLength(200)
;

        builder.Property(e => e.DeliveryCountry)
    .HasMaxLength(100)
;

        builder.Property(e => e.Profile)
    .HasMaxLength(500)
;

        builder.Property(e => e.Category)
    .HasMaxLength(200)
;

        builder.HasIndex(e => e.TenderId);

        builder.HasIndex(e => new { e.ExternalId, e.TenderId })
    .IsUnique();

        builder.HasOne(e => e.Tender)
    .WithMany(p => p.Items)
    .HasForeignKey(e => e.TenderId)
    .OnDelete(DeleteBehavior.Restrict);

    }
}
