// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using System.ComponentModel.DataAnnotations;
using Onward.Base.DTOs;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.DTO.Tender;

/// <summary>
/// DTO for creating a new Tender
/// </summary>
public class CreateTenderDTO : CreateDTO
{
    /// <summary>
    /// Prozorro unique tender identifier
    /// </summary>
    [Required]
    [StringLength(50)]
    public string ExternalId { get; set; } = default!;

    /// <summary>
    /// Human-readable tender number (UA-YYYY-MM-DD-XXXXXX-X)
    /// </summary>
    [StringLength(100)]
    public string TenderNumber { get; set; }

    /// <summary>
    /// Tender title
    /// </summary>
    [StringLength(1000)]
    public string Title { get; set; }

    /// <summary>
    /// Detailed tender description
    /// </summary>
    [StringLength(4000)]
    public string Description { get; set; }

    /// <summary>
    /// Platform owner or source system slug
    /// </summary>
    [StringLength(200)]
    public string Owner { get; set; }

    /// <summary>
    /// Current tender lifecycle status
    /// </summary>
    public TenderStatus Status { get; set; } = TenderStatus.Draft;

    /// <summary>
    /// Prozorro procurement method type
    /// </summary>
    public ProcurementMethodType ProcurementMethodType { get; set; } = ProcurementMethodType.BelowThreshold;

    /// <summary>
    /// Criteria for selecting the winning bid
    /// </summary>
    public AwardCriteria AwardCriteria { get; set; } = AwardCriteria.LowestCost;

    /// <summary>
    /// Procurement method string (open, limited, selective)
    /// </summary>
    [StringLength(100)]
    public string ProcurementMethod { get; set; }

    /// <summary>
    /// Main procurement category (goods, services, works)
    /// </summary>
    [StringLength(100)]
    public string MainProcurementCategory { get; set; }

    /// <summary>
    /// Expected total procurement value
    /// </summary>
    public decimal? TotalAmount { get; set; }

    /// <summary>
    /// Currency code (UAH, EUR, USD)
    /// </summary>
    [StringLength(10)]
    public string Currency { get; set; }

    /// <summary>
    /// Whether the total amount includes VAT
    /// </summary>
    public bool? ValueAddedTaxIncluded { get; set; } = true;

    /// <summary>
    /// Start of the tender acceptance period
    /// </summary>
    public string TenderPeriodStart { get; set; }

    /// <summary>
    /// Deadline for bid submission
    /// </summary>
    public string TenderPeriodEnd { get; set; }

    /// <summary>
    /// Start of the award evaluation period
    /// </summary>
    public string AwardPeriodStart { get; set; }

    /// <summary>
    /// End of the award evaluation period
    /// </summary>
    public string AwardPeriodEnd { get; set; }

    /// <summary>
    /// Date the tender notice was published in Prozorro
    /// </summary>
    public string NoticePublicationDate { get; set; }

    /// <summary>
    /// Tender object creation timestamp from Prozorro
    /// </summary>
    public string TenderDate { get; set; }

    /// <summary>
    /// Related framework agreement ID from Prozorro
    /// </summary>
    [StringLength(100)]
    public string AgreementId { get; set; }

    /// <summary>
    /// Organization acting as the procuring entity
    /// </summary>
    public Guid ProcuringEntityId { get; set; }

}
