// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.DTOs;
using EnergyBrockerage.Prozorro.Common.Enums;

namespace EnergyBrockerage.Prozorro.DTO.Tender;

/// <summary>
/// DTO for searching/filtering Tender entities
/// </summary>
public class TenderSearchDTO : SearchDTO
{
    /// <summary>
    /// Prozorro unique tender identifier
    /// </summary>
    public string ExternalId { get; set; }

    /// <summary>
    /// Human-readable tender number (UA-YYYY-MM-DD-XXXXXX-X)
    /// </summary>
    public string TenderNumber { get; set; }

    /// <summary>
    /// Tender title
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Detailed tender description
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Platform owner or source system slug
    /// </summary>
    public string Owner { get; set; }

    /// <summary>
    /// Current tender lifecycle status
    /// </summary>
    public TenderStatus Status { get; set; }

    /// <summary>
    /// Prozorro procurement method type
    /// </summary>
    public ProcurementMethodType ProcurementMethodType { get; set; }

    /// <summary>
    /// Criteria for selecting the winning bid
    /// </summary>
    public AwardCriteria AwardCriteria { get; set; }

    /// <summary>
    /// Procurement method string (open, limited, selective)
    /// </summary>
    public string ProcurementMethod { get; set; }

    /// <summary>
    /// Main procurement category (goods, services, works)
    /// </summary>
    public string MainProcurementCategory { get; set; }

    /// <summary>
    /// Expected total procurement value
    /// </summary>
    public decimal? TotalAmount { get; set; }

    /// <summary>
    /// Currency code (UAH, EUR, USD)
    /// </summary>
    public string Currency { get; set; }

    /// <summary>
    /// Whether the total amount includes VAT
    /// </summary>
    public bool? ValueAddedTaxIncluded { get; set; }

    /// <summary>
    /// Start of the tender acceptance period
    /// </summary>
    public string TenderPeriodStart { get; set; }

    /// <summary>
    /// Deadline for bid submission
    /// </summary>
    public string TenderPeriodEnd { get; set; }

    /// <summary>
    /// Start of the award evaluation period
    /// </summary>
    public string AwardPeriodStart { get; set; }

    /// <summary>
    /// End of the award evaluation period
    /// </summary>
    public string AwardPeriodEnd { get; set; }

    /// <summary>
    /// Date the tender notice was published in Prozorro
    /// </summary>
    public string NoticePublicationDate { get; set; }

    /// <summary>
    /// Tender object creation timestamp from Prozorro
    /// </summary>
    public string TenderDate { get; set; }

    /// <summary>
    /// Related framework agreement ID from Prozorro
    /// </summary>
    public string AgreementId { get; set; }

    /// <summary>
    /// Organization acting as the procuring entity
    /// </summary>
    public Guid? ProcuringEntityId { get; set; }

    /// <summary>
    /// Junction collection: contract change rationale types applicable to this tender
    /// </summary>
    public object TenderChangeRationales { get; set; }

    /// <summary>
    /// Junction collection: documents attached to this tender
    /// </summary>
    public object TenderDocuments { get; set; }

}
