// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Linq.Expressions;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.OrderItem;
using Inventorization.Base.Abstractions;

namespace Inventorization.Commerce.Domain.Mappers;

/// <summary>
/// Mapper for OrderItem entities
/// </summary>
public class OrderItemMapper : IMapper<OrderItem, OrderItemDetailsDTO>
{
    /// <summary>
    /// Maps OrderItem entity to DetailsDTO
    /// </summary>
    public OrderItemDetailsDTO Map(OrderItem entity)
    {
        if (entity == null)
            throw new ArgumentNullException(nameof(entity));

        return new OrderItemDetailsDTO
        {
            Id = entity.Id,
            Quantity = entity.Quantity,
            UnitPrice = entity.UnitPrice,
            TotalPrice = entity.TotalPrice,
        };
    }

    /// <summary>
    /// Gets LINQ projection expression for OrderItem
    /// </summary>
    public Expression<Func<OrderItem, OrderItemDetailsDTO>> GetProjection()
    {
        return entity => new OrderItemDetailsDTO
        {
            Id = entity.Id,
            Quantity = entity.Quantity,
            UnitPrice = entity.UnitPrice,
            TotalPrice = entity.TotalPrice,
        };
    }
}
