// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-76e7efc9
//     Generated: 2026-02-14 15:34:46 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
//     Custom business logic should be added to separate domain services.
// </auto-generated>

using Inventorization.Base.Abstractions;
using Inventorization.Base.ADTs;
using Inventorization.Base.DataAccess;
using Inventorization.Base.Services;
using Inventorization.Commerce.Domain.Entities;
using Inventorization.Commerce.DTO.ADTs;
using Microsoft.Extensions.Logging;

namespace Inventorization.Commerce.Domain.Services;

/// <summary>
/// Service for executing ADT-based search queries on Category entities.
/// Inherits all search logic from BaseSearchService.
/// Supports both regular projections and field transformations.
/// </summary>
public class CategorySearchService : BaseSearchService<Category, CategoryProjection>
{
    public CategorySearchService(
        IRepository<Category> repository,
        IQueryBuilder<Category> queryBuilder,
        IProjectionMapper<Category, CategoryProjection> projectionMapper,
        ProjectionExpressionBuilder expressionBuilder,
        IValidator<SearchQuery> validator,
        ILogger<CategorySearchService> logger)
        : base(repository, queryBuilder, projectionMapper, expressionBuilder, validator, logger)
    {
    }
    
    // Override ExecuteSearchAsync or ExecuteTransformationSearchAsync if custom logic is needed
}
