// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Creators;

/// <summary>
/// Creator for ContractChangeRationaleType entities
/// </summary>
public class ContractChangeRationaleTypeCreator : IEntityCreator<ContractChangeRationaleType, CreateContractChangeRationaleTypeDTO>
{
    /// <summary>
    /// Creates a new ContractChangeRationaleType entity from a DTO
    /// </summary>
    public ContractChangeRationaleType Create(CreateContractChangeRationaleTypeDTO dto)
    {
        if (dto == null)
            throw new ArgumentNullException(nameof(dto));


        return new ContractChangeRationaleType(
            code: dto.Code,
            titleEn: dto.TitleEn,
            titleUk: dto.TitleUk,
            descriptionEn: dto.DescriptionEn,
            descriptionUk: dto.DescriptionUk
        );
    }
}
