// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Criterion;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Creators;

/// <summary>
/// Creator for Criterion entities
/// </summary>
public class CriterionCreator : IEntityCreator<Criterion, CreateCriterionDTO>
{
    /// <summary>
    /// Creates a new Criterion entity from a DTO
    /// </summary>
    public Criterion Create(CreateCriterionDTO dto)
    {
        if (dto == null)
            throw new ArgumentNullException(nameof(dto));


        return new Criterion(
            externalId: dto.ExternalId,
            title: dto.Title,
            description: dto.Description,
            source: dto.Source,
            relatesTo: dto.RelatesTo,
            relatedItem: dto.RelatedItem,
            classificationScheme: dto.ClassificationScheme,
            classificationId: dto.ClassificationId,
            tenderId: dto.TenderId
        );
    }
}
