// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Document;
using Onward.Base.Abstractions;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Creators;

/// <summary>
/// Creator for Document entities
/// </summary>
public class DocumentCreator : IEntityCreator<Document, CreateDocumentDTO>
{
    /// <summary>
    /// Creates a new Document entity from a DTO
    /// </summary>
    public Document Create(CreateDocumentDTO dto)
    {
        if (dto == null)
            throw new ArgumentNullException(nameof(dto));


        return new Document(
            externalId: dto.ExternalId,
            title: dto.Title,
            format: dto.Format,
            url: dto.Url,
            hash: dto.Hash,
            documentType: dto.DocumentType,
            confidentiality: dto.Confidentiality,
            documentOf: dto.DocumentOf,
            relatedItem: dto.RelatedItem,
            author: dto.Author,
            language: dto.Language,
            datePublished: dto.DatePublished != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.DatePublished)) : null,
            dateModified: dto.DateModified != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.DateModified)) : null
        );
    }
}
