// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.Requirement;
using Onward.Base.Abstractions;
using Onward.Base.Models;

namespace EnergyBrockerage.Prozorro.BL.Creators;

/// <summary>
/// Creator for Requirement entities
/// </summary>
public class RequirementCreator : IEntityCreator<Requirement, CreateRequirementDTO>
{
    /// <summary>
    /// Creates a new Requirement entity from a DTO
    /// </summary>
    public Requirement Create(CreateRequirementDTO dto)
    {
        if (dto == null)
            throw new ArgumentNullException(nameof(dto));


        return new Requirement(
            externalId: dto.ExternalId,
            title: dto.Title,
            dataType: dto.DataType,
            status: dto.Status,
            expectedValue: dto.ExpectedValue,
            expectedValuesJson: dto.ExpectedValuesJson,
            expectedMinItems: dto.ExpectedMinItems,
            expectedMaxItems: dto.ExpectedMaxItems,
            datePublished: dto.DatePublished != null ? DateTimeWithOffset.From(DateTimeOffset.Parse(dto.DatePublished)) : null,
            requirementGroupId: dto.RequirementGroupId
        );
    }
}
