// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.DTO.RequirementGroup;
using Onward.Base.Abstractions;

namespace EnergyBrockerage.Prozorro.BL.Creators;

/// <summary>
/// Creator for RequirementGroup entities
/// </summary>
public class RequirementGroupCreator : IEntityCreator<RequirementGroup, CreateRequirementGroupDTO>
{
    /// <summary>
    /// Creates a new RequirementGroup entity from a DTO
    /// </summary>
    public RequirementGroup Create(CreateRequirementGroupDTO dto)
    {
        if (dto == null)
            throw new ArgumentNullException(nameof(dto));


        return new RequirementGroup(
            externalId: dto.ExternalId,
            description: dto.Description,
            criterionId: dto.CriterionId
        );
    }
}
