// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Onward.Base.DTOs;

namespace EnergyBrockerage.Prozorro.DTO.Criterion;

/// <summary>
/// DTO with detailed information about a Criterion
/// </summary>
public class CriterionDetailsDTO : DetailsDTO<Guid>
{
    /// <summary>
    /// Prozorro criterion ID
    /// </summary>
    public string ExternalId { get; set; }

    /// <summary>
    /// Criterion title
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Criterion description
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// Criterion source (e.g. tenderer, procuringEntity)
    /// </summary>
    public string Source { get; set; }

    /// <summary>
    /// Entity this criterion relates to (lot, item, tender)
    /// </summary>
    public string RelatesTo { get; set; }

    /// <summary>
    /// External ID of the related item
    /// </summary>
    public string RelatedItem { get; set; }

    /// <summary>
    /// Classification scheme of the criterion
    /// </summary>
    public string ClassificationScheme { get; set; }

    /// <summary>
    /// Classification code of the criterion
    /// </summary>
    public string ClassificationId { get; set; }

    /// <summary>
    /// Parent tender
    /// </summary>
    public Guid TenderId { get; set; }

}
