// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-717476ad
//     Generated: 2026-02-15 18:29:05 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;

namespace Inventorization.Commerce.DTO.Order;

/// <summary>
/// DTO for deleting a Order
/// </summary>
public class DeleteOrderDTO : DeleteDTO
{
    // Inherits Id from DeleteDTO base class
}
