// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260215-38d150ed
//     Generated: 2026-02-15 09:53:00 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;
using Inventorization.Commerce.Common.Enums;

namespace Inventorization.Commerce.DTO.Order;

/// <summary>
/// DTO for init operation on Order
/// </summary>
public record InitOrderDTO(
    Guid Id,
    Guid CustomerId,
    string OrderNumber,
    DateTime OrderDate,
    decimal TotalAmount,
    OrderStatus Status,
    Guid ShippingAddressId
) : InitDTO(Id);
