// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260214-76e7efc9
//     Generated: 2026-02-14 15:34:46 UTC
//     Source: simple-bounded-context.json
//
//     Changes to this file will be lost when regenerated.
// </auto-generated>

using Inventorization.Base.DTOs;
using Inventorization.Commerce.Common.Enums;

namespace Inventorization.Commerce.DTO.Order;

/// <summary>
/// DTO for searching/filtering Order entities
/// </summary>
public class OrderSearchDTO : SearchDTO
{
    /// <summary>
    /// Customer ID
    /// </summary>
    public Guid? CustomerId { get; set; }

    /// <summary>
    /// Unique order number
    /// </summary>
    public string OrderNumber { get; set; }

    /// <summary>
    /// Order date and time
    /// </summary>
    public DateTime? OrderDate { get; set; }

    /// <summary>
    /// Total order amount
    /// </summary>
    public decimal? TotalAmount { get; set; }

    /// <summary>
    /// Order status
    /// </summary>
    public OrderStatus Status { get; set; }

    /// <summary>
    /// Shipping address ID
    /// </summary>
    public Guid? ShippingAddressId { get; set; }

}
