// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.DTO.BidItem;

namespace EnergyBrockerage.Prozorro.API.Tests.Mappers;

public class BidItemMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new BidItemMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.ExternalId.Should().Be(entity.ExternalId);
        result.Description.Should().Be(entity.Description);
        result.Quantity.Should().Be(entity.Quantity);
        result.UnitName.Should().Be(entity.UnitName);
        result.UnitCode.Should().Be(entity.UnitCode);
        result.UnitPrice.Should().Be(entity.UnitPrice);
        result.UnitPriceCurrency.Should().Be(entity.UnitPriceCurrency);
    }

    private static BidItem CreateEntity()
    {
        return new BidItem(
            new string('a', 1),
            new string('a', 1),
            1m,
            new string('a', 1),
            new string('a', 1),
            1m,
            new string('a', 1),
            Guid.NewGuid()
        );
    }
}
