// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.DTO.Bid;

namespace EnergyBrockerage.Prozorro.API.Tests.Mappers;

public class BidMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new BidMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.ExternalId.Should().Be(entity.ExternalId);
        result.Status.Should().Be(entity.Status);
        result.BidDate.Should().Be(entity.BidDate);
        result.SubmissionDate.Should().Be(entity.SubmissionDate);
        result.Amount.Should().Be(entity.Amount);
        result.Currency.Should().Be(entity.Currency);
        result.ValueAddedTaxIncluded.Should().Be(entity.ValueAddedTaxIncluded);
        result.InitialAmount.Should().Be(entity.InitialAmount);
    }

    private static Bid CreateEntity()
    {
        return new Bid(
            new string('a', 1),
            BidStatus.Draft,
            default!,
            default!,
            1m,
            new string('a', 1),
            true,
            1m,
            Guid.NewGuid(),
            Guid.NewGuid()
        );
    }
}
