// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.DTO.ContractChangeRationaleType;

namespace EnergyBrockerage.Prozorro.API.Tests.Mappers;

public class ContractChangeRationaleTypeMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new ContractChangeRationaleTypeMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.Code.Should().Be(entity.Code);
        result.TitleEn.Should().Be(entity.TitleEn);
        result.TitleUk.Should().Be(entity.TitleUk);
        result.DescriptionEn.Should().Be(entity.DescriptionEn);
        result.DescriptionUk.Should().Be(entity.DescriptionUk);
    }

    private static ContractChangeRationaleType CreateEntity()
    {
        return new ContractChangeRationaleType(
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1)
        );
    }
}
