// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.DTO.Organization;

namespace EnergyBrockerage.Prozorro.API.Tests.Mappers;

public class OrganizationMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new OrganizationMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.ExternalId.Should().Be(entity.ExternalId);
        result.IdentifierScheme.Should().Be(entity.IdentifierScheme);
        result.Name.Should().Be(entity.Name);
        result.NameEn.Should().Be(entity.NameEn);
        result.LegalName.Should().Be(entity.LegalName);
        result.LegalNameEn.Should().Be(entity.LegalNameEn);
        result.Kind.Should().Be(entity.Kind);
        result.Scale.Should().Be(entity.Scale);
        result.StreetAddress.Should().Be(entity.StreetAddress);
        result.Locality.Should().Be(entity.Locality);
        result.Region.Should().Be(entity.Region);
        result.PostalCode.Should().Be(entity.PostalCode);
        result.CountryName.Should().Be(entity.CountryName);
        result.ContactName.Should().Be(entity.ContactName);
        result.ContactEmail.Should().Be(entity.ContactEmail);
        result.ContactPhone.Should().Be(entity.ContactPhone);
        result.ContactUrl.Should().Be(entity.ContactUrl);
    }

    private static Organization CreateEntity()
    {
        return new Organization(
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            OrganizationKind.General,
            OrganizationScale.Micro,
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            new string('a', 1),
            "user@example.com",
            new string('a', 1),
            new string('a', 1)
        );
    }
}
