// <auto-generated>
//     This code was generated by the BoundedContext Code Generator.
//     Generation Stamp: 20260411-7ded7da9
//     Generated: 2026-04-11 15:49:38 UTC
//     Source: procurement.json
// </auto-generated>

#nullable enable

using EnergyBrockerage.Prozorro.BL.Entities;
using EnergyBrockerage.Prozorro.BL.Mappers;
using EnergyBrockerage.Prozorro.DTO.RequirementGroup;

namespace EnergyBrockerage.Prozorro.API.Tests.Mappers;

public class RequirementGroupMapperTests
{
    [Fact]
    public void Map_ReturnsDetailsDto_WithExpectedValues()
    {
        var mapper = new RequirementGroupMapper();
        var entity = CreateEntity();

        var result = mapper.Map(entity);

        result.Should().NotBeNull();
        result.ExternalId.Should().Be(entity.ExternalId);
        result.Description.Should().Be(entity.Description);
    }

    private static RequirementGroup CreateEntity()
    {
        return new RequirementGroup(
            new string('a', 1),
            new string('a', 1),
            Guid.NewGuid()
        );
    }
}
